In [1]:
# ============================================================
# PS S6E5 - exp_20260520_046_cat_shared001v2_features_optuna_refit_min
# CatBoost shared001v2-style features + 045 Optuna best params refit
#
# Base model structure:
#   042: exp_20260520_042_cat_shared001v2_features_min
#
# Params source:
#   045: exp_20260520_045_cat_shared001v2_features_optuna_search_min
#   best_params_045.json
#
# Purpose:
#   Apply 045 Optuna best CatBoost params to the exact 042 feature/fold/original policy,
#   then generate formal 5-fold OOF / test pred / submission artifacts.
#
# Do not change:
#   - CV split
#   - feature engineering from 042
#   - original rows concat policy
#   - shared004 full-FE blocks except inherited Race_Year group-stat drop
#   - Normalized_TyreLife prohibition
#   - OOF/pred save format
#   - blend evaluation policy
#
# Important:
#   This is NOT a new feature experiment.
#   039 LOG features are NOT added.
#   Race_Year itself is NOT dropped.
#   IsOriginalData is NOT dropped.
#   TyreAgeRatio_str is NOT dropped.
# ============================================================
# 046 change:
#   Base: 042
#   Replace CatBoost hyperparameters with 045 Optuna best params only.
#   Validate whether 045 CV gain survives formal refit and add046 blend.

In [2]:
import os
import gc
import json
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score, log_loss

from catboost import CatBoostClassifier

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 300)

In [3]:
# ============================================================
# Config
# ============================================================

class CFG:
    EXP_ID = "exp_20260520_046_cat_shared001v2_features_optuna_refit_min"
    COMPETITION = "PS S6E5 Predicting F1 Pit Stops"
    METRIC = "AUC"

    TARGET_CANDIDATES = ["PitNextLap", "PitNextLab"]
    TARGET = "PitNextLap"
    ID_COL = "id"
    DANGER_COL = "Normalized_TyreLife"

    # 046差分:
    # Base model structure is 042.
    # Keep 042 feature engineering / folds / original-row policy unchanged.
    # Apply 045 Optuna best CatBoost params only.
    # Do NOT add 039 LOG features.
    # Do NOT add new FE.
    # Do NOT drop Race_Year itself.
    # Do NOT drop IsOriginalData.
    # Do NOT drop TyreAgeRatio_str.
    DROP_GROUPSTAT_KEYWORDS = [
        "_by_Race_Year",
    ]
    
    COMP_PATHS = [
        "/kaggle/input/competitions/playground-series-s6e5",
        "/kaggle/input/playground-series-s6e5",
        ".",
    ]

    ORIGINAL_PATHS = [
        "/kaggle/input/datasets/aadigupta1601/f1-strategy-dataset-pit-stop-prediction/f1_strategy_dataset_v4.csv",
        "/kaggle/input/f1-strategy-dataset-pit-stop-prediction/f1_strategy_dataset_v4.csv",
        "./f1_strategy_dataset_v4.csv",
    ]

    BEST_PARAMS_PATH = "/kaggle/input/datasets/mizushimatoshihiko/npy-files/exp_20260520_045_cat_shared001v2_features_optuna_search_min/best_params_045.json"
    with open(BEST_PARAMS_PATH, mode="rt", encoding="utf-8") as f:
        best_params_data = json.load(f)

    # Accept both formats:
    #   1) {"learning_rate": ..., "depth": ...}
    #   2) {"best_params": {"learning_rate": ..., "depth": ...}, ...}
    BEST_PARAMS = best_params_data.get("best_params", best_params_data)
    BEST_PARAMS_SOURCE_RAW = best_params_data

    OUTDIR = Path(f"/kaggle/working/{EXP_ID}")

    SEED = 42
    N_SPLITS = 5

    USE_ORIGINAL = True

    # CatBoost
    TASK_TYPE = "GPU"
    DEVICES = "0:1"

    ITERATIONS = 9000
    LEARNING_RATE = 0.033
    DEPTH = 8
    L2_LEAF_REG = 7.0
    RANDOM_STRENGTH = 0.8
    EARLY_STOPPING_ROUNDS = 350

    # GPU hidden-default guard
    # SlideShare note:
    #   GPU default border_count / bootstrap_type can differ from CPU.
    #   Fix these explicitly.
    BOOTSTRAP_TYPE = "Bernoulli"
    SUBSAMPLE = 0.8
    BORDER_COUNT = 254

    AUTO_CLASS_WEIGHTS = "Balanced"

    CLIP_LOW = 1e-6
    CLIP_HIGH = 1.0 - 1e-6

    VERBOSE = 200


CFG.OUTDIR.mkdir(parents=True, exist_ok=True)

In [4]:
# ============================================================
# Utilities
# ============================================================

def seed_everything(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)


def print_section(title: str) -> None:
    print("\n" + "=" * 90)
    print(title)
    print("=" * 90)


def first_existing_dir(paths):
    for p in paths:
        path = Path(p)
        if (path / "train.csv").exists() and (path / "test.csv").exists():
            return path
    raise FileNotFoundError(f"No valid competition path found: {paths}")


def first_existing_file(paths, required=True):
    for p in paths:
        path = Path(p)
        if path.exists():
            return path
    if required:
        raise FileNotFoundError(f"No valid file path found: {paths}")
    return None


def resolve_target_column(df: pd.DataFrame) -> str:
    for c in CFG.TARGET_CANDIDATES:
        if c in df.columns:
            return c
    raise ValueError(f"No target column found among {CFG.TARGET_CANDIDATES}")


def reduce_mem_usage(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()

    for col in out.columns:
        dtype = out[col].dtype

        if pd.api.types.is_integer_dtype(dtype):
            c_min = out[col].min()
            c_max = out[col].max()

            if c_min >= np.iinfo(np.int8).min and c_max <= np.iinfo(np.int8).max:
                out[col] = out[col].astype(np.int8)
            elif c_min >= np.iinfo(np.int16).min and c_max <= np.iinfo(np.int16).max:
                out[col] = out[col].astype(np.int16)
            elif c_min >= np.iinfo(np.int32).min and c_max <= np.iinfo(np.int32).max:
                out[col] = out[col].astype(np.int32)

        elif pd.api.types.is_float_dtype(dtype):
            out[col] = pd.to_numeric(out[col], downcast="float")

    return out


def safe_divide(a, b, eps=1e-6):
    return a / (b + eps)


def clip_pred(x):
    return np.clip(x, CFG.CLIP_LOW, CFG.CLIP_HIGH)


seed_everything(CFG.SEED)

In [5]:
# ============================================================
# 015: Race_Year group-stat drop utility
# ============================================================

def is_race_year_groupstat_feature(col: str) -> bool:
    """
    Drop only features generated by add_light_group_stats
    with Race_Year as group key.

    Expected patterns:
      - LapTime_Delta_mean_by_Race_Year
      - LapTime_Delta_std_by_Race_Year
      - LapTime_Delta_diff_mean_by_Race_Year
      - Position_Change_mean_by_Race_Year
      - Position_Change_std_by_Race_Year
      - Position_Change_diff_mean_by_Race_Year
      - RaceProgress_mean_by_Race_Year
      - RaceProgress_std_by_Race_Year
      - RaceProgress_diff_mean_by_Race_Year
      - TyreLife_mean_by_Race_Year
      - TyreLife_std_by_Race_Year
      - TyreLife_diff_mean_by_Race_Year
    """
    return any(keyword in col for keyword in CFG.DROP_GROUPSTAT_KEYWORDS)


def drop_015_groupstat_features(feature_cols):
    """
    015 is a strict ablation from 012.
    Drop only Race_Year group-stat features.

    Do not drop:
      - Race_Year itself
      - Race_Year_count
      - Race_Year_freq
      - IsOriginalData
      - TyreAgeRatio_str
      - Race_Compound_Stint group stats
    """
    return [c for c in feature_cols if not is_race_year_groupstat_feature(c)]


def assert_015_feature_policy(feature_cols):
    """
    Guardrail for 015.
    This experiment is invalid if Race_Year group-stat features remain.
    It is also invalid if Race_Year itself or other key risk features are accidentally dropped.
    """
    remained = [c for c in feature_cols if is_race_year_groupstat_feature(c)]
    assert len(remained) == 0, (
        "015 policy violation: Race_Year group-stat features still remain: "
        + str(remained[:20])
    )

    assert "Race_Year" in feature_cols, (
        "015 policy violation: Race_Year itself was dropped. "
        "015 should drop only Race_Year group stats."
    )

    assert "IsOriginalData" in feature_cols, (
        "015 policy violation: IsOriginalData was dropped. "
        "015 should keep IsOriginalData."
    )

    assert "TyreAgeRatio_str" in feature_cols, (
        "015 policy violation: TyreAgeRatio_str was dropped. "
        "015 should keep TyreAgeRatio_str."
    )

In [6]:
# ============================================================
# Load data
# ============================================================

print_section("Load Data")

COMP_PATH = first_existing_dir(CFG.COMP_PATHS)

train_raw = pd.read_csv(COMP_PATH / "train.csv")
test_raw = pd.read_csv(COMP_PATH / "test.csv")
sample_submission = pd.read_csv(COMP_PATH / "sample_submission.csv")

target_col_train = resolve_target_column(train_raw)
if target_col_train != CFG.TARGET:
    train_raw = train_raw.rename(columns={target_col_train: CFG.TARGET})

target_col_sub = resolve_target_column(sample_submission)
if target_col_sub != CFG.TARGET:
    sample_submission = sample_submission.rename(columns={target_col_sub: CFG.TARGET})

original_raw = None
original_path = first_existing_file(CFG.ORIGINAL_PATHS, required=False)

if CFG.USE_ORIGINAL and original_path is not None:
    original_raw = pd.read_csv(original_path)

    if CFG.TARGET not in original_raw.columns:
        original_target = resolve_target_column(original_raw)
        original_raw = original_raw.rename(columns={original_target: CFG.TARGET})

    print("Loaded original:", original_path, original_raw.shape)

print("COMP_PATH:", COMP_PATH)
print("train_raw:", train_raw.shape)
print("test_raw :", test_raw.shape)
print("sample_submission:", sample_submission.shape)
print("target mean train:", train_raw[CFG.TARGET].mean())

assert CFG.ID_COL in train_raw.columns
assert CFG.ID_COL in test_raw.columns
assert CFG.ID_COL in sample_submission.columns
assert CFG.TARGET in train_raw.columns
assert CFG.TARGET in sample_submission.columns
assert test_raw[CFG.ID_COL].equals(sample_submission[CFG.ID_COL])

if original_raw is not None:
    assert CFG.TARGET in original_raw.columns
    print("target mean original:", original_raw[CFG.TARGET].mean())

    if CFG.DANGER_COL in original_raw.columns:
        original_raw = original_raw.drop(columns=[CFG.DANGER_COL])
        print(f"Dropped danger column from original: {CFG.DANGER_COL}")

train_raw = reduce_mem_usage(train_raw)
test_raw = reduce_mem_usage(test_raw)

if original_raw is not None:
    original_raw = reduce_mem_usage(original_raw)

train_ids = train_raw[CFG.ID_COL].copy()
test_ids = test_raw[CFG.ID_COL].copy()

==========================================================================================
Load Data
==========================================================================================
Loaded original: /kaggle/input/datasets/aadigupta1601/f1-strategy-dataset-pit-stop-prediction/f1_strategy_dataset_v4.csv (101371, 16)
COMP_PATH: /kaggle/input/competitions/playground-series-s6e5
train_raw: (439140, 16)
test_raw : (188165, 15)
sample_submission: (188165, 2)
target mean train: 0.19898210137996994
target mean original: 0.25479673673930414
Dropped danger column from original: Normalized_TyreLife

In [7]:
# ============================================================
# shared_004 style feature engineering
# ============================================================

BASE_CAT_COLS = ["Driver", "Compound", "Race"]

NUMERIC_BASE_COLS = [
    "Year",
    "PitStop",
    "LapNumber",
    "Stint",
    "TyreLife",
    "Position",
    "LapTime (s)",
    "LapTime_Delta",
    "Cumulative_Degradation",
    "RaceProgress",
    "Position_Change",
]


def add_domain_features(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    eps = 1e-6

    for col in BASE_CAT_COLS:
        if col in out.columns:
            out[col] = out[col].astype("string").fillna("__MISSING__").astype(str)

    if {"LapNumber", "RaceProgress"}.issubset(out.columns):
        out["EstimatedTotalLaps"] = safe_divide(
            out["LapNumber"],
            out["RaceProgress"].clip(lower=eps),
            eps,
        ).replace([np.inf, -np.inf], np.nan).clip(1, 120)

        out["LapsRemaining"] = (
            out["EstimatedTotalLaps"] - out["LapNumber"]
        ).clip(lower=0)

        out["LapProgress_x_LapNumber"] = out["LapNumber"] * out["RaceProgress"]

    if {"TyreLife", "LapNumber"}.issubset(out.columns):
        out["TyreAgeRatio"] = safe_divide(out["TyreLife"], out["LapNumber"].clip(lower=1), eps)
        out["LapPerTyreLife"] = safe_divide(out["LapNumber"], out["TyreLife"] + 1, eps)
        out["LapMinusTyreLife"] = out["LapNumber"] - out["TyreLife"]
        out["TyreLifeMinusLap"] = out["TyreLife"] - out["LapNumber"]

    if {"TyreLife", "EstimatedTotalLaps"}.issubset(out.columns):
        out["TyreAgeVsRace"] = safe_divide(
            out["TyreLife"],
            out["EstimatedTotalLaps"].clip(lower=1),
            eps,
        )

    if {"TyreLife", "RaceProgress"}.issubset(out.columns):
        out["PitWindowPressure"] = out["TyreLife"] * out["RaceProgress"]
        out["TyreLife_x_RaceProgress"] = out["TyreLife"] * out["RaceProgress"]

    if {"TyreLife", "LapsRemaining"}.issubset(out.columns):
        out["TyreLife_to_LapsRemaining"] = safe_divide(out["TyreLife"], out["LapsRemaining"] + 1, eps)
        out["LapsRemaining_to_TyreLife"] = safe_divide(out["LapsRemaining"], out["TyreLife"] + 1, eps)

    if {"Cumulative_Degradation", "TyreLife"}.issubset(out.columns):
        out["DegPerTyreLap"] = safe_divide(
            out["Cumulative_Degradation"],
            out["TyreLife"].clip(lower=1),
            eps,
        )
        out["AbsDegPerTyreLap"] = safe_divide(
            out["Cumulative_Degradation"].abs(),
            out["TyreLife"].clip(lower=1),
            eps,
        )

    if {"Cumulative_Degradation", "LapNumber"}.issubset(out.columns):
        out["DegPerRaceLap"] = safe_divide(
            out["Cumulative_Degradation"],
            out["LapNumber"].clip(lower=1),
            eps,
        )

    if {"LapTime_Delta", "TyreLife"}.issubset(out.columns):
        out["DeltaPerTyreLap"] = safe_divide(
            out["LapTime_Delta"],
            out["TyreLife"].clip(lower=1),
            eps,
        )
        out["AbsDeltaPerTyreLap"] = safe_divide(
            out["LapTime_Delta"].abs(),
            out["TyreLife"].clip(lower=1),
            eps,
        )

    if "LapTime_Delta" in out.columns:
        out["DeltaAbs"] = out["LapTime_Delta"].abs()
        out["LapTimeDeltaPositive"] = (out["LapTime_Delta"] > 0).astype(np.int8)
        out["LapTimeDeltaNegative"] = (out["LapTime_Delta"] < 0).astype(np.int8)

    if "Cumulative_Degradation" in out.columns:
        out["Abs_Cumulative_Degradation"] = out["Cumulative_Degradation"].abs()
        out["Positive_Degradation"] = (out["Cumulative_Degradation"] > 0).astype(np.int8)

    if "Position_Change" in out.columns:
        out["Abs_Position_Change"] = out["Position_Change"].abs()
        out["Gained_Position"] = (out["Position_Change"] > 0).astype(np.int8)
        out["Lost_Position"] = (out["Position_Change"] < 0).astype(np.int8)

    if {"Position", "RaceProgress"}.issubset(out.columns):
        out["PositionPressure"] = out["Position"] * out["RaceProgress"]

    if {"Stint", "TyreLife"}.issubset(out.columns):
        out["StintPressure"] = out["Stint"] * out["TyreLife"]
        out["TyreLife_x_Stint"] = out["TyreLife"] * out["Stint"]

    if {"Stint", "LapNumber"}.issubset(out.columns):
        out["Stint_x_LapNumber"] = out["Stint"] * out["LapNumber"]
        out["Is_First_Stint"] = (out["Stint"] == 1).astype(np.int8)
        out["Is_Late_Stint"] = (out["Stint"] >= 3).astype(np.int8)

    if "RaceProgress" in out.columns:
        out["Early_Race"] = (out["RaceProgress"] <= 0.25).astype(np.int8)
        out["Mid_Race"] = (
            (out["RaceProgress"] > 0.25)
            & (out["RaceProgress"] <= 0.65)
        ).astype(np.int8)
        out["Late_Race"] = (out["RaceProgress"] > 0.65).astype(np.int8)

        out["RacePhase"] = pd.cut(
            out["RaceProgress"],
            bins=[-np.inf, 0.20, 0.40, 0.60, 0.80, np.inf],
            labels=["P1", "P2", "P3", "P4", "P5"],
        ).astype(str)

    if "LapNumber" in out.columns:
        out["LapBin"] = pd.cut(
            out["LapNumber"],
            bins=[-np.inf, 5, 10, 20, 35, 50, np.inf],
            labels=[
                "L_000_005",
                "L_006_010",
                "L_011_020",
                "L_021_035",
                "L_036_050",
                "L_051_plus",
            ],
        ).astype(str)

    if "TyreLife" in out.columns:
        out["TyreLifeBin"] = pd.cut(
            out["TyreLife"],
            bins=[-np.inf, 3, 7, 12, 20, 30, np.inf],
            labels=[
                "T_000_003",
                "T_004_007",
                "T_008_012",
                "T_013_020",
                "T_021_030",
                "T_031_plus",
            ],
        ).astype(str)

    if "Position" in out.columns:
        out["PositionBin"] = pd.cut(
            out["Position"],
            bins=[-np.inf, 3, 8, 14, np.inf],
            labels=["front", "upper_mid", "lower_mid", "back"],
        ).astype(str)

    def make_cross(name, cols):
        if set(cols).issubset(out.columns):
            val = out[cols[0]].astype(str)
            for c in cols[1:]:
                val = val + "_" + out[c].astype(str)
            out[name] = val

    make_cross("Race_Year", ["Race", "Year"])
    make_cross("Compound_Stint", ["Compound", "Stint"])
    make_cross("Driver_Race", ["Driver", "Race"])
    make_cross("Driver_Compound", ["Driver", "Compound"])
    make_cross("Race_Compound", ["Race", "Compound"])
    make_cross("Race_Compound_Stint", ["Race", "Compound", "Stint"])
    make_cross("Compound_RacePhase", ["Compound", "RacePhase"])
    make_cross("Compound_TyreLifeBin", ["Compound", "TyreLifeBin"])
    make_cross("RacePhase_TyreLifeBin", ["RacePhase", "TyreLifeBin"])

    out = out.replace([np.inf, -np.inf], np.nan)

    for col in out.select_dtypes(include=["float64"]).columns:
        out[col] = out[col].astype(np.float32)

    return out


def add_digit_features(df: pd.DataFrame, numeric_cols=None, int_digit_limit=3, decimal_digit_limit=2) -> pd.DataFrame:
    out = df.copy()

    if numeric_cols is None:
        numeric_cols = out.select_dtypes(include=[np.number]).columns.tolist()

    for col in numeric_cols:
        if col not in out.columns:
            continue

        s = out[col].fillna(0).astype(float)
        abs_s = s.abs()

        for i in range(int_digit_limit):
            new_col = f"{col}_int_digit_{i + 1}"
            out[new_col] = ((abs_s // (10 ** i)) % 10).astype(np.int8)

        if pd.api.types.is_float_dtype(out[col]):
            for i in range(1, decimal_digit_limit + 1):
                new_col = f"{col}_dec_digit_{i}"
                out[new_col] = ((abs_s * (10 ** i)).round().astype(int) % 10).astype(np.int8)

    return out


def add_float_signature_features(df: pd.DataFrame, float_cols=None) -> pd.DataFrame:
    out = df.copy()

    selected = [
        "RaceProgress",
        "LapTime (s)",
        "LapTime_Delta",
        "Cumulative_Degradation",
        "TyreAgeRatio",
        "DegPerTyreLap",
        "DegPerRaceLap",
        "DeltaPerTyreLap",
        "DeltaAbs",
        "PitWindowPressure",
        "EstimatedTotalLaps",
        "LapsRemaining",
        "LapMinusTyreLife",
    ]

    float_cols = [c for c in selected if c in out.columns]

    for col in float_cols:
        scaled = (out[col].fillna(0).astype(float) * 100).round().astype(int).abs()

        for i in range(5):
            new_col = f"{col}_sig_{i + 1}"
            digit = ((scaled // (10 ** i)) % 10).astype(np.int8)

            if digit.nunique() > 1:
                out[new_col] = digit.astype(str)

    return out


def add_string_precision_features(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()

    if "RaceProgress" in out.columns:
        out["RaceProgress_str"] = out["RaceProgress"].round(4).astype(str)

    if "EstimatedTotalLaps" in out.columns:
        out["EstimatedTotalLaps_str"] = out["EstimatedTotalLaps"].round(1).astype(str)

    if "TyreAgeRatio" in out.columns:
        out["TyreAgeRatio_str"] = out["TyreAgeRatio"].round(3).astype(str)

    return out


# ============================================================
# 042: shared001v2-style features from 029/038 RealMLP branch
# ============================================================

SHARED001V2_042_NUMERIC_SOURCE_COLS = [
    "Year",
    "PitStop",
    "LapNumber",
    "Stint",
    "TyreLife",
    "Position",
    "LapTime (s)",
    "LapTime_Delta",
    "Cumulative_Degradation",
    "RaceProgress",
    "Position_Change",
]

SHARED001V2_042_CAT_FEATURES = [
    "PitStop_cat_",
    "Race_Year_",
    "Race_Compound_",
    "RaceProgress_200_quantile_bin_",
    "LapTime (s)_7_quantile_bin_",
]

SHARED001V2_042_COUNT_FEATURES = [
    "_PitStop_cat_count",
    "_Race_Year_count",
    "_Race_Compound_count",
    "_RaceProgress_200_quantile_bin_count",
    "_LapTime_s_7_quantile_bin_count",
]


def _to_safe_str_series(s: pd.Series) -> pd.Series:
    return s.astype("string").fillna("__MISSING__").astype(str)


def _floor_cat_series(s: pd.Series) -> pd.Series:
    x = pd.to_numeric(s, errors="coerce")
    # Use a dedicated missing token before flooring to avoid silent imputation.
    floored = np.floor(x).astype("float")
    return floored.astype("Int64").astype("string").fillna("__MISSING__").astype(str)


def add_shared001v2_style_features_042(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add 029/038 RealMLP-style categorical/bin features to CatBoost.
    These are row-wise transformations only; no target is used here.

    Important:
    - 039 LOG features are intentionally not added.
    - Normalized_TyreLife and any endpoint proxy are not reconstructed.
    """
    out = df.copy()

    if "PitStop" in out.columns:
        out["PitStop_cat_"] = _floor_cat_series(out["PitStop"])

    if {"Race", "Year"}.issubset(out.columns):
        out["Race_Year_"] = _to_safe_str_series(out["Race"]) + "_" + _to_safe_str_series(out["Year"])

    if {"Race", "Compound"}.issubset(out.columns):
        out["Race_Compound_"] = _to_safe_str_series(out["Race"]) + "_" + _to_safe_str_series(out["Compound"])

    # 029/038-style quantile bins.
    # qcut is avoided because train/test/original must receive the same deterministic mapping.
    if "RaceProgress" in out.columns:
        rp = pd.to_numeric(out["RaceProgress"], errors="coerce").clip(0, 1)
        bin_idx = np.floor(rp.fillna(-1) * 200).astype(int).clip(-1, 199)
        out["RaceProgress_200_quantile_bin_"] = np.where(
            bin_idx < 0,
            "__MISSING__",
            "rp200_" + pd.Series(bin_idx, index=out.index).astype(str),
        )

    if "LapTime (s)" in out.columns:
        lt = pd.to_numeric(out["LapTime (s)"], errors="coerce")
        # Use deterministic absolute bins rather than qcut.
        # qcut per-frame would make train/test/original bin definitions inconsistent.
        codes = pd.cut(
            lt,
            bins=[-np.inf, 70, 75, 80, 85, 90, 95, np.inf],
            labels=False,
        )
        out["LapTime (s)_7_quantile_bin_"] = (
            "lt7_" + codes.astype("Int64").astype("string")
        ).fillna("__MISSING__").astype(str)

    for col in SHARED001V2_042_NUMERIC_SOURCE_COLS:
        if col in out.columns:
            out[f"{col}_floor_cat_042"] = _floor_cat_series(out[col])

    return out


def add_shared001v2_counts_042(train_df, test_df, original_df=None):
    """
    Count-encode only the newly added shared001v2-style categorical/bin columns.
    Counts are calculated from train + test + original feature space, without target use.
    """
    count_source_cols = [
        "PitStop_cat_",
        "Race_Year_",
        "Race_Compound_",
        "RaceProgress_200_quantile_bin_",
        "LapTime (s)_7_quantile_bin_",
    ] + [
        f"{c}_floor_cat_042"
        for c in SHARED001V2_042_NUMERIC_SOURCE_COLS
        if f"{c}_floor_cat_042" in train_df.columns and f"{c}_floor_cat_042" in test_df.columns
    ]

    count_source_cols = [
        c for c in count_source_cols
        if c in train_df.columns and c in test_df.columns
    ]

    frames = [train_df, test_df]
    if original_df is not None:
        frames.append(original_df)

    base = pd.concat(
        [f[count_source_cols].astype(str) for f in frames],
        axis=0,
        ignore_index=True,
    )
    total = len(base)

    for col in count_source_cols:
        counts = base[col].astype(str).value_counts(dropna=False)
        safe_name = col.replace(" ", "_").replace("(", "").replace(")", "")
        for f in frames:
            f[f"_{safe_name}_count"] = f[col].astype(str).map(counts).fillna(0).astype(np.float32)
            f[f"_{safe_name}_freq"] = (f[f"_{safe_name}_count"] / total).astype(np.float32)

    del base
    gc.collect()

    if original_df is not None:
        return train_df, test_df, original_df

    return train_df, test_df, None



def add_frequency_features(train_df, test_df, original_df=None):
    freq_cols = [
        "Driver",
        "Race",
        "Compound",
        "Race_Year",
        "Compound_Stint",
        "Driver_Race",
        "Driver_Compound",
        "Race_Compound",
        "Race_Compound_Stint",
        "Compound_RacePhase",
        "Compound_TyreLifeBin",
        "RacePhase_TyreLifeBin",
        "LapBin",
        "TyreLifeBin",
        "PositionBin",
    ]

    freq_cols = [c for c in freq_cols if c in train_df.columns and c in test_df.columns]

    frames = [train_df, test_df]
    if original_df is not None:
        frames.append(original_df)

    base = pd.concat([f[freq_cols] for f in frames], axis=0, ignore_index=True)
    total = len(base)

    for col in freq_cols:
        counts = base[col].astype(str).value_counts(dropna=False)

        for f in frames:
            f[f"{col}_count"] = f[col].astype(str).map(counts).fillna(0).astype(np.float32)
            f[f"{col}_freq"] = (f[f"{col}_count"] / total).astype(np.float32)

    del base
    gc.collect()

    if original_df is not None:
        return train_df, test_df, original_df

    return train_df, test_df, None


def add_light_group_stats(train_df, test_df, original_df=None):
    group_cols_list = [
        ["Race_Year"],
        ["Race_Compound_Stint"],
        ["Driver_Race"],
        ["Compound_Stint"],
    ]

    value_cols = [
        "LapTime_Delta",
        "Position_Change",
        "RaceProgress",
        "TyreLife",
    ]

    frames = [train_df, test_df]
    if original_df is not None:
        frames.append(original_df)

    for group_cols in group_cols_list:
        group_cols = [c for c in group_cols if all(c in f.columns for f in frames)]

        if not group_cols:
            continue

        group_name = "_".join(group_cols)

        for value_col in value_cols:
            if not all(value_col in f.columns for f in frames):
                continue

            base = pd.concat(
                [f[group_cols + [value_col]] for f in frames],
                axis=0,
                ignore_index=True,
            )

            stats = (
                base.groupby(group_cols, dropna=False)[value_col]
                .agg(["mean", "std"])
                .reset_index()
            )

            stats.columns = group_cols + [
                f"{value_col}_mean_by_{group_name}",
                f"{value_col}_std_by_{group_name}",
            ]

            for idx, f in enumerate(frames):
                frames[idx] = f.merge(stats, on=group_cols, how="left")

                mean_col = f"{value_col}_mean_by_{group_name}"
                frames[idx][f"{value_col}_diff_mean_by_{group_name}"] = (
                    frames[idx][value_col] - frames[idx][mean_col]
                ).astype(np.float32)

            del base, stats
            gc.collect()

    if original_df is not None:
        return frames[0], frames[1], frames[2]

    return frames[0], frames[1], None


def clean_columns(train_df, test_df, original_df=None):
    train_df = train_df.copy()
    test_df = test_df.copy()

    if original_df is not None:
        original_df = original_df.copy()

    common_cols = [c for c in train_df.columns if c in test_df.columns]

    train_df = train_df[common_cols + [CFG.TARGET]]
    test_df = test_df[common_cols]

    if original_df is not None:
        for c in common_cols:
            if c not in original_df.columns:
                original_df[c] = np.nan

        original_df = original_df[common_cols + [CFG.TARGET]]

    return train_df, test_df, original_df


def fill_missing_and_types(train_df, test_df, original_df=None):
    frames = [train_df, test_df]
    if original_df is not None:
        frames.append(original_df)

    all_feature_cols = [c for c in train_df.columns if c != CFG.TARGET]

    cat_cols = []

    for col in all_feature_cols:
        if any(
            (
                f[col].dtype == "object"
                or str(f[col].dtype).startswith("category")
                or str(f[col].dtype).startswith("string")
            )
            for f in frames
            if col in f.columns
        ):
            cat_cols.append(col)

    num_cols = [c for c in all_feature_cols if c not in cat_cols]

    for col in cat_cols:
        values = pd.concat(
            [f[col].astype("string") for f in frames if col in f.columns],
            axis=0,
        )
        mode_values = values.mode()
        mode_value = mode_values.iloc[0] if len(mode_values) else "__MISSING__"

        for f in frames:
            if col in f.columns:
                f[col] = f[col].astype("string").fillna(mode_value).astype(str)

    for col in num_cols:
        values = pd.concat([f[col] for f in frames if col in f.columns], axis=0)
        fill_value = values.median()

        for f in frames:
            if col in f.columns:
                f[col] = f[col].replace([np.inf, -np.inf], np.nan).fillna(fill_value)
                if f[col].dtype == "float64":
                    f[col] = f[col].astype(np.float32)

    train_df = reduce_mem_usage(train_df)
    test_df = reduce_mem_usage(test_df)

    if original_df is not None:
        original_df = reduce_mem_usage(original_df)

    return train_df, test_df, original_df, cat_cols

In [8]:
# ============================================================
# Feature Engineering
# ============================================================

print_section("Feature Engineering")

train_fe = train_raw.copy()
test_fe = test_raw.copy()

if original_raw is not None and CFG.TARGET in original_raw.columns:
    original_fe = original_raw.copy()
else:
    original_fe = None

if original_fe is not None and CFG.DANGER_COL in original_fe.columns:
    original_fe = original_fe.drop(columns=[CFG.DANGER_COL])
    print(f"Dropped danger column from original_fe: {CFG.DANGER_COL}")

train_fe["IsOriginalData"] = 0
test_fe["IsOriginalData"] = 0

if original_fe is not None:
    original_fe["IsOriginalData"] = 1

train_fe = add_domain_features(train_fe)
test_fe = add_domain_features(test_fe)

if original_fe is not None:
    original_fe = add_domain_features(original_fe)

digit_source_cols = [
    "Year",
    "PitStop",
    "LapNumber",
    "Stint",
    "TyreLife",
    "Position",
    "LapTime (s)",
    "LapTime_Delta",
    "Cumulative_Degradation",
    "RaceProgress",
    "Position_Change",
    "EstimatedTotalLaps",
    "LapsRemaining",
    "TyreAgeRatio",
    "DegPerTyreLap",
    "DegPerRaceLap",
    "DeltaPerTyreLap",
    "DeltaAbs",
    "PositionPressure",
    "StintPressure",
    "PitWindowPressure",
    "LapMinusTyreLife",
]
digit_source_cols = [c for c in digit_source_cols if c in train_fe.columns and c in test_fe.columns]

train_fe = add_digit_features(train_fe, digit_source_cols)
test_fe = add_digit_features(test_fe, digit_source_cols)

if original_fe is not None:
    original_fe = add_digit_features(original_fe, digit_source_cols)

train_fe = add_float_signature_features(train_fe)
test_fe = add_float_signature_features(test_fe)

if original_fe is not None:
    original_fe = add_float_signature_features(original_fe)

train_fe = add_string_precision_features(train_fe)
test_fe = add_string_precision_features(test_fe)

if original_fe is not None:
    original_fe = add_string_precision_features(original_fe)

# 042: add shared001v2-style categorical/bin/count features.
# Keep this before fill_missing/types so CatBoost receives these as categorical columns.
train_fe = add_shared001v2_style_features_042(train_fe)
test_fe = add_shared001v2_style_features_042(test_fe)

if original_fe is not None:
    original_fe = add_shared001v2_style_features_042(original_fe)

train_fe, test_fe, original_fe = add_frequency_features(train_fe, test_fe, original_fe)
train_fe, test_fe, original_fe = add_shared001v2_counts_042(train_fe, test_fe, original_fe)
train_fe, test_fe, original_fe = add_light_group_stats(train_fe, test_fe, original_fe)

train_fe, test_fe, original_fe = clean_columns(train_fe, test_fe, original_fe)
train_fe, test_fe, original_fe, cat_cols = fill_missing_and_types(train_fe, test_fe, original_fe)

print("train_fe:", train_fe.shape)
print("test_fe :", test_fe.shape)

if original_fe is not None:
    print("original_fe:", original_fe.shape)

print("categorical features:", len(cat_cols))

==========================================================================================
Feature Engineering
==========================================================================================
train_fe: (439140, 351)
test_fe : (188165, 350)
original_fe: (101371, 351)
categorical features: 93

In [9]:
# ============================================================
# Prepare matrices
# ============================================================

print_section("Prepare Matrices")

X_comp = train_fe.drop(columns=[CFG.TARGET, CFG.ID_COL], errors="ignore")
y_comp = train_fe[CFG.TARGET].astype(int).reset_index(drop=True)

X_test_final = test_fe.drop(columns=[CFG.ID_COL], errors="ignore")

if original_fe is not None:
    X_orig = original_fe.drop(columns=[CFG.TARGET, CFG.ID_COL], errors="ignore")
    y_orig = original_fe[CFG.TARGET].astype(int).reset_index(drop=True)
else:
    X_orig = None
    y_orig = None

common_features = [c for c in X_comp.columns if c in X_test_final.columns]

# 015差分: Race_Year group-stat featuresだけを除外
dropped_groupstat_features_015 = [
    c for c in common_features
    if is_race_year_groupstat_feature(c)
]

common_features = drop_015_groupstat_features(common_features)
assert_015_feature_policy(common_features)

print("042 inherited-042 inherited-015 dropped Race_Year group-stat features:", dropped_groupstat_features_015)
print("042 inherited-042 inherited-015 dropped feature count:", len(dropped_groupstat_features_015))
print("final feature count after 042 inherited-015 drop:", len(common_features))
print("Race_Year in features:", "Race_Year" in common_features)
print("IsOriginalData in features:", "IsOriginalData" in common_features)
print("TyreAgeRatio_str in features:", "TyreAgeRatio_str" in common_features)
print(
    "Remaining Race_Year group-stat features:",
    [c for c in common_features if is_race_year_groupstat_feature(c)]
)

# 042 guardrails: these shared001v2-style columns should exist unless source columns are missing.
expected_shared001v2_features_042 = [
    c for c in [
        "PitStop_cat_",
        "Race_Year_",
        "Race_Compound_",
        "RaceProgress_200_quantile_bin_",
        "LapTime (s)_7_quantile_bin_",
    ]
    if c in X_comp.columns and c in X_test_final.columns
]
print("042 shared001v2-style base features:", expected_shared001v2_features_042)
print("042 shared001v2-style feature count:", len([
    c for c in common_features
    if c.endswith("_floor_cat_042")
    or c in expected_shared001v2_features_042
    or c.startswith("_PitStop_cat_")
    or c.startswith("_Race_Year_")
    or c.startswith("_Race_Compound_")
    or c.startswith("_RaceProgress_200_quantile_bin_")
    or c.startswith("_LapTime_s_7_quantile_bin_")
]))

X_comp = X_comp[common_features].reset_index(drop=True)
X_test_final = X_test_final[common_features].reset_index(drop=True)

if X_orig is not None:
    for c in common_features:
        if c not in X_orig.columns:
            X_orig[c] = np.nan
    X_orig = X_orig[common_features].reset_index(drop=True)

cat_cols = [c for c in cat_cols if c in common_features]
cat_features = [X_comp.columns.get_loc(c) for c in cat_cols]

==========================================================================================
Prepare Matrices
==========================================================================================
042 inherited-042 inherited-015 dropped Race_Year group-stat features: ['LapTime_Delta_mean_by_Race_Year', 'LapTime_Delta_std_by_Race_Year', 'LapTime_Delta_diff_mean_by_Race_Year', 'Position_Change_mean_by_Race_Year', 'Position_Change_std_by_Race_Year', 'Position_Change_diff_mean_by_Race_Year', 'RaceProgress_mean_by_Race_Year', 'RaceProgress_std_by_Race_Year', 'RaceProgress_diff_mean_by_Race_Year', 'TyreLife_mean_by_Race_Year', 'TyreLife_std_by_Race_Year', 'TyreLife_diff_mean_by_Race_Year']
042 inherited-042 inherited-015 dropped feature count: 12
final feature count after 042 inherited-015 drop: 337
Race_Year in features: True
IsOriginalData in features: True
TyreAgeRatio_str in features: True
Remaining Race_Year group-stat features: []
042 shared001v2-style base features: ['PitStop_cat_', 'Race_Year_', 'Race_Compound_', 'RaceProgress_200_quantile_bin_', 'LapTime (s)_7_quantile_bin_']
042 shared001v2-style feature count: 26

In [10]:
# ============================================================
# CatBoost model
# ============================================================

def get_catboost_params(seed: int, iterations: int, task_type: str):
    params = {
        "iterations": iterations,
        "learning_rate": CFG.LEARNING_RATE,
        "depth": CFG.DEPTH,
        "l2_leaf_reg": CFG.L2_LEAF_REG,
        "random_strength": CFG.RANDOM_STRENGTH,

        # Fixed to avoid CatBoost CPU/GPU hidden-default mismatch.
        "bootstrap_type": CFG.BOOTSTRAP_TYPE,
        "subsample": CFG.SUBSAMPLE,
        "border_count": CFG.BORDER_COUNT,

        "loss_function": "Logloss",
        "eval_metric": "AUC",
        "auto_class_weights": CFG.AUTO_CLASS_WEIGHTS,

        "task_type": task_type,
        "random_seed": seed,
        "early_stopping_rounds": CFG.EARLY_STOPPING_ROUNDS,
        "allow_writing_files": False,
        "verbose": CFG.VERBOSE,
    }

    params.update(CFG.BEST_PARAMS)

    if task_type == "GPU":
        params["devices"] = CFG.DEVICES
    else:
        params["thread_count"] = -1

    return params


def fit_catboost_with_fallback(X_tr, y_tr, X_va, y_va, seed):
    params = get_catboost_params(seed=seed, iterations=CFG.ITERATIONS, task_type=CFG.TASK_TYPE)

    model = CatBoostClassifier(**params)

    try:
        model.fit(
            X_tr,
            y_tr,
            eval_set=(X_va, y_va),
            cat_features=cat_features,
            use_best_model=True,
        )
        used_device = CFG.TASK_TYPE
        return model, used_device

    except Exception as e:
        print("CatBoost GPU/device training failed. Retrying with CPU.")
        print("Error:", repr(e))

        cpu_params = get_catboost_params(seed=seed, iterations=CFG.ITERATIONS, task_type="CPU")
        cpu_model = CatBoostClassifier(**cpu_params)

        cpu_model.fit(
            X_tr,
            y_tr,
            eval_set=(X_va, y_va),
            cat_features=cat_features,
            use_best_model=True,
        )

        return cpu_model, "CPU"

In [11]:
# ============================================================
# 5fold OOF training
# ============================================================

print_section("5fold OOF Training")

folds = list(
    StratifiedKFold(
        n_splits=CFG.N_SPLITS,
        shuffle=True,
        random_state=CFG.SEED,
    ).split(X_comp, y_comp)
)

oof = np.zeros(len(X_comp), dtype=np.float32)
pred = np.zeros(len(X_test_final), dtype=np.float32)

fold_records = []
feature_importance_records = []
used_devices = []

for fold, (tr_idx, va_idx) in enumerate(folds, 1):
    print("\n" + "=" * 90)
    print(f"Fold {fold}/{CFG.N_SPLITS}")
    print("=" * 90)

    X_tr_comp = X_comp.iloc[tr_idx].copy().reset_index(drop=True)
    y_tr_comp = y_comp.iloc[tr_idx].copy().reset_index(drop=True)

    X_va = X_comp.iloc[va_idx].copy().reset_index(drop=True)
    y_va = y_comp.iloc[va_idx].copy().reset_index(drop=True)

    if X_orig is not None and CFG.USE_ORIGINAL:
        X_tr = pd.concat(
            [X_tr_comp, X_orig],
            axis=0,
            ignore_index=True,
        )
        y_tr = pd.concat(
            [y_tr_comp, y_orig],
            axis=0,
            ignore_index=True,
        )
    else:
        X_tr = X_tr_comp
        y_tr = y_tr_comp

    print("X_tr:", X_tr.shape, "target mean:", float(y_tr.mean()))
    print("X_va:", X_va.shape, "target mean:", float(y_va.mean()))
    print("X_test:", X_test_final.shape)

    model, used_device = fit_catboost_with_fallback(
        X_tr=X_tr,
        y_tr=y_tr,
        X_va=X_va,
        y_va=y_va,
        seed=CFG.SEED + fold,
    )

    va_pred = clip_pred(model.predict_proba(X_va)[:, 1]).astype(np.float32)
    te_pred = clip_pred(model.predict_proba(X_test_final)[:, 1]).astype(np.float32)

    oof[va_idx] = va_pred
    pred += te_pred / CFG.N_SPLITS

    fold_auc = roc_auc_score(y_va, va_pred)
    fold_logloss = log_loss(y_va, va_pred)
    best_iter = int(model.get_best_iteration() or -1)

    print(f"Fold {fold} AUC    : {fold_auc:.9f}")
    print(f"Fold {fold} LogLoss: {fold_logloss:.9f}")
    print(f"Fold {fold} best_iter: {best_iter}")
    print(f"Fold {fold} used_device: {used_device}")

    fold_records.append({
        "fold": fold,
        "auc": float(fold_auc),
        "logloss": float(fold_logloss),
        "best_iteration": best_iter,
        "used_device": used_device,
        "n_train_comp": int(len(X_tr_comp)),
        "n_train_orig": int(len(X_orig)) if X_orig is not None and CFG.USE_ORIGINAL else 0,
        "n_valid": int(len(X_va)),
        "n_features": int(X_tr.shape[1]),
        "n_cat_features": int(len(cat_features)),
    })

    fi = pd.DataFrame({
        "feature": X_tr.columns,
        "importance": model.get_feature_importance(),
        "fold": fold,
    })
    feature_importance_records.append(fi)

    used_devices.append(used_device)

    del model, X_tr_comp, y_tr_comp, X_va, y_va, X_tr, y_tr, va_pred, te_pred
    gc.collect()

==========================================================================================
5fold OOF Training
==========================================================================================

==========================================================================================
Fold 1/5
==========================================================================================
X_tr: (452683, 337) target mean: 0.21147911452385001
X_va: (87828, 337) target mean: 0.19899121009245344
X_test: (188165, 337)

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9286063	best: 0.9286063 (0)	total: 452ms	remaining: 1h 7m 46s
200:	test: 0.9453290	best: 0.9453290 (200)	total: 46.7s	remaining: 34m 6s
400:	test: 0.9483466	best: 0.9483466 (400)	total: 1m 34s	remaining: 33m 49s
600:	test: 0.9501563	best: 0.9501563 (600)	total: 2m 23s	remaining: 33m 18s
800:	test: 0.9511303	best: 0.9511303 (800)	total: 3m 11s	remaining: 32m 41s
1000:	test: 0.9518530	best: 0.9518530 (1000)	total: 4m 4s	remaining: 32m 34s
1200:	test: 0.9523494	best: 0.9523494 (1200)	total: 4m 58s	remaining: 32m 18s
1400:	test: 0.9526790	best: 0.9526797 (1399)	total: 5m 51s	remaining: 31m 48s
1600:	test: 0.9529119	best: 0.9529119 (1600)	total: 6m 44s	remaining: 31m 9s
1800:	test: 0.9530852	best: 0.9530852 (1800)	total: 7m 38s	remaining: 30m 31s
2000:	test: 0.9532368	best: 0.9532368 (2000)	total: 8m 30s	remaining: 29m 44s
2200:	test: 0.9533818	best: 0.9533818 (2200)	total: 9m 23s	remaining: 29m 1s
2400:	test: 0.9534931	best: 0.9534931 (2400)	total: 10m 15s	remaining: 28m 12s
2600:	test: 0.9535863	best: 0.9535863 (2600)	total: 11m 8s	remaining: 27m 25s
2800:	test: 0.9536767	best: 0.9536767 (2800)	total: 12m 2s	remaining: 26m 39s
3000:	test: 0.9537244	best: 0.9537254 (2998)	total: 12m 55s	remaining: 25m 50s
3200:	test: 0.9537970	best: 0.9537970 (3198)	total: 13m 48s	remaining: 25m 1s
3400:	test: 0.9538528	best: 0.9538534 (3398)	total: 14m 41s	remaining: 24m 10s
3600:	test: 0.9539078	best: 0.9539078 (3600)	total: 15m 34s	remaining: 23m 20s
3800:	test: 0.9539462	best: 0.9539464 (3798)	total: 16m 28s	remaining: 22m 31s
4000:	test: 0.9539804	best: 0.9539804 (4000)	total: 17m 22s	remaining: 21m 41s
4200:	test: 0.9540119	best: 0.9540125 (4199)	total: 18m 15s	remaining: 20m 51s
4400:	test: 0.9540451	best: 0.9540451 (4400)	total: 19m 8s	remaining: 19m 59s
4600:	test: 0.9540808	best: 0.9540809 (4599)	total: 20m 2s	remaining: 19m 9s
4800:	test: 0.9540952	best: 0.9540963 (4779)	total: 20m 55s	remaining: 18m 18s
5000:	test: 0.9541197	best: 0.9541201 (4983)	total: 21m 49s	remaining: 17m 27s
5200:	test: 0.9541571	best: 0.9541571 (5200)	total: 22m 42s	remaining: 16m 35s
5400:	test: 0.9541844	best: 0.9541844 (5400)	total: 23m 36s	remaining: 15m 43s
5600:	test: 0.9541999	best: 0.9542021 (5579)	total: 24m 30s	remaining: 14m 52s
5800:	test: 0.9542066	best: 0.9542078 (5795)	total: 25m 24s	remaining: 14m
6000:	test: 0.9542170	best: 0.9542183 (5926)	total: 26m 18s	remaining: 13m 8s
6200:	test: 0.9542371	best: 0.9542371 (6200)	total: 27m 11s	remaining: 12m 16s
6400:	test: 0.9542374	best: 0.9542452 (6287)	total: 28m 6s	remaining: 11m 24s
6600:	test: 0.9542450	best: 0.9542459 (6575)	total: 29m	remaining: 10m 32s
6800:	test: 0.9542571	best: 0.9542587 (6795)	total: 29m 54s	remaining: 9m 40s
7000:	test: 0.9542826	best: 0.9542832 (6993)	total: 30m 48s	remaining: 8m 47s
7200:	test: 0.9542934	best: 0.9542937 (7191)	total: 31m 43s	remaining: 7m 55s
7400:	test: 0.9542955	best: 0.9542992 (7373)	total: 32m 37s	remaining: 7m 2s
7600:	test: 0.9542980	best: 0.9543003 (7419)	total: 33m 32s	remaining: 6m 10s
7800:	test: 0.9543021	best: 0.9543038 (7778)	total: 34m 26s	remaining: 5m 17s
8000:	test: 0.9543210	best: 0.9543211 (7999)	total: 35m 20s	remaining: 4m 24s
8200:	test: 0.9543285	best: 0.9543300 (8191)	total: 36m 15s	remaining: 3m 31s
8400:	test: 0.9543236	best: 0.9543300 (8191)	total: 37m 11s	remaining: 2m 39s
bestTest = 0.9543299675
bestIteration = 8191
Shrink model to first 8192 iterations.
Fold 1 AUC    : 0.954329897
Fold 1 LogLoss: 0.259582442
Fold 1 best_iter: 8191
Fold 1 used_device: GPU

==========================================================================================
Fold 2/5
==========================================================================================
X_tr: (452683, 337) target mean: 0.2114813235752171
X_va: (87828, 337) target mean: 0.19897982420184906
X_test: (188165, 337)

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9211724	best: 0.9211724 (0)	total: 307ms	remaining: 46m 3s
200:	test: 0.9430679	best: 0.9430679 (200)	total: 48.3s	remaining: 35m 12s
400:	test: 0.9464172	best: 0.9464172 (400)	total: 1m 36s	remaining: 34m 26s
600:	test: 0.9482272	best: 0.9482272 (600)	total: 2m 23s	remaining: 33m 25s
800:	test: 0.9492300	best: 0.9492300 (800)	total: 3m 11s	remaining: 32m 38s
1000:	test: 0.9499645	best: 0.9499645 (1000)	total: 4m 3s	remaining: 32m 22s
1200:	test: 0.9504101	best: 0.9504101 (1200)	total: 4m 56s	remaining: 32m 4s
1400:	test: 0.9507436	best: 0.9507436 (1400)	total: 5m 48s	remaining: 31m 30s
1600:	test: 0.9510267	best: 0.9510267 (1600)	total: 6m 41s	remaining: 30m 56s
1800:	test: 0.9512215	best: 0.9512215 (1800)	total: 7m 34s	remaining: 30m 17s
2000:	test: 0.9513866	best: 0.9513867 (1999)	total: 8m 26s	remaining: 29m 32s
2200:	test: 0.9515315	best: 0.9515315 (2200)	total: 9m 19s	remaining: 28m 47s
2400:	test: 0.9516298	best: 0.9516298 (2400)	total: 10m 12s	remaining: 28m 2s
2600:	test: 0.9517384	best: 0.9517384 (2600)	total: 11m 4s	remaining: 27m 15s
2800:	test: 0.9518235	best: 0.9518235 (2800)	total: 11m 57s	remaining: 26m 28s
3000:	test: 0.9518952	best: 0.9518958 (2998)	total: 12m 50s	remaining: 25m 40s
3200:	test: 0.9519704	best: 0.9519704 (3200)	total: 13m 43s	remaining: 24m 52s
3400:	test: 0.9520278	best: 0.9520278 (3400)	total: 14m 36s	remaining: 24m 3s
3600:	test: 0.9520840	best: 0.9520844 (3594)	total: 15m 29s	remaining: 23m 13s
3800:	test: 0.9521187	best: 0.9521196 (3796)	total: 16m 23s	remaining: 22m 24s
4000:	test: 0.9521555	best: 0.9521555 (4000)	total: 17m 16s	remaining: 21m 35s
4200:	test: 0.9521828	best: 0.9521835 (4189)	total: 18m 10s	remaining: 20m 45s
4400:	test: 0.9522173	best: 0.9522181 (4398)	total: 19m 4s	remaining: 19m 55s
4600:	test: 0.9522430	best: 0.9522430 (4600)	total: 19m 58s	remaining: 19m 5s
4800:	test: 0.9522813	best: 0.9522813 (4800)	total: 20m 51s	remaining: 18m 14s
5000:	test: 0.9523206	best: 0.9523243 (4944)	total: 21m 45s	remaining: 17m 24s
5200:	test: 0.9523439	best: 0.9523445 (5193)	total: 22m 38s	remaining: 16m 32s
5400:	test: 0.9523605	best: 0.9523608 (5396)	total: 23m 32s	remaining: 15m 41s
5600:	test: 0.9523734	best: 0.9523734 (5600)	total: 24m 26s	remaining: 14m 49s
5800:	test: 0.9523856	best: 0.9523856 (5797)	total: 25m 20s	remaining: 13m 58s
6000:	test: 0.9523994	best: 0.9524003 (5966)	total: 26m 13s	remaining: 13m 6s
6200:	test: 0.9524124	best: 0.9524125 (6186)	total: 27m 8s	remaining: 12m 14s
6400:	test: 0.9524328	best: 0.9524330 (6399)	total: 28m 2s	remaining: 11m 23s
6600:	test: 0.9524528	best: 0.9524562 (6593)	total: 28m 55s	remaining: 10m 30s
6800:	test: 0.9524503	best: 0.9524578 (6697)	total: 29m 50s	remaining: 9m 39s
7000:	test: 0.9524690	best: 0.9524696 (6998)	total: 30m 44s	remaining: 8m 46s
7200:	test: 0.9524676	best: 0.9524731 (7138)	total: 31m 39s	remaining: 7m 54s
7400:	test: 0.9524751	best: 0.9524770 (7396)	total: 32m 34s	remaining: 7m 2s
7600:	test: 0.9524807	best: 0.9524812 (7599)	total: 33m 28s	remaining: 6m 9s
7800:	test: 0.9524698	best: 0.9524829 (7608)	total: 34m 21s	remaining: 5m 16s
bestTest = 0.9524829388
bestIteration = 7608
Shrink model to first 7609 iterations.
Fold 2 AUC    : 0.952482962
Fold 2 LogLoss: 0.262651083
Fold 2 best_iter: 7608
Fold 2 used_device: GPU

==========================================================================================
Fold 3/5
==========================================================================================
X_tr: (452683, 337) target mean: 0.2114813235752171
X_va: (87828, 337) target mean: 0.19897982420184906
X_test: (188165, 337)

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9219781	best: 0.9219781 (0)	total: 340ms	remaining: 50m 55s
200:	test: 0.9448592	best: 0.9448592 (200)	total: 48.6s	remaining: 35m 25s
400:	test: 0.9480288	best: 0.9480288 (400)	total: 1m 35s	remaining: 34m 14s
600:	test: 0.9497244	best: 0.9497244 (600)	total: 2m 23s	remaining: 33m 20s
800:	test: 0.9506305	best: 0.9506305 (800)	total: 3m 10s	remaining: 32m 27s
1000:	test: 0.9512540	best: 0.9512540 (1000)	total: 4m 3s	remaining: 32m 26s
1200:	test: 0.9516889	best: 0.9516889 (1200)	total: 4m 57s	remaining: 32m 11s
1400:	test: 0.9519919	best: 0.9519919 (1400)	total: 5m 50s	remaining: 31m 39s
1600:	test: 0.9522020	best: 0.9522020 (1600)	total: 6m 43s	remaining: 31m 2s
1800:	test: 0.9523697	best: 0.9523697 (1800)	total: 7m 35s	remaining: 30m 20s
2000:	test: 0.9525239	best: 0.9525239 (2000)	total: 8m 28s	remaining: 29m 37s
2200:	test: 0.9526748	best: 0.9526756 (2199)	total: 9m 20s	remaining: 28m 51s
2400:	test: 0.9527827	best: 0.9527832 (2398)	total: 10m 12s	remaining: 28m 3s
2600:	test: 0.9528614	best: 0.9528620 (2596)	total: 11m 4s	remaining: 27m 14s
2800:	test: 0.9529232	best: 0.9529234 (2799)	total: 11m 56s	remaining: 26m 26s
3000:	test: 0.9529786	best: 0.9529786 (2999)	total: 12m 48s	remaining: 25m 36s
3200:	test: 0.9530273	best: 0.9530273 (3199)	total: 13m 40s	remaining: 24m 46s
3400:	test: 0.9530836	best: 0.9530842 (3396)	total: 14m 31s	remaining: 23m 55s
3600:	test: 0.9531165	best: 0.9531173 (3596)	total: 15m 23s	remaining: 23m 4s
3800:	test: 0.9531583	best: 0.9531589 (3786)	total: 16m 14s	remaining: 22m 12s
4000:	test: 0.9531977	best: 0.9531977 (4000)	total: 17m 7s	remaining: 21m 23s
4200:	test: 0.9532297	best: 0.9532297 (4200)	total: 17m 59s	remaining: 20m 33s
4400:	test: 0.9532693	best: 0.9532693 (4400)	total: 18m 52s	remaining: 19m 43s
4600:	test: 0.9533063	best: 0.9533080 (4599)	total: 19m 43s	remaining: 18m 51s
4800:	test: 0.9533334	best: 0.9533342 (4764)	total: 20m 36s	remaining: 18m 1s
5000:	test: 0.9533503	best: 0.9533534 (4996)	total: 21m 28s	remaining: 17m 10s
5200:	test: 0.9533700	best: 0.9533706 (5197)	total: 22m 20s	remaining: 16m 19s
5400:	test: 0.9533877	best: 0.9533884 (5393)	total: 23m 12s	remaining: 15m 28s
5600:	test: 0.9533924	best: 0.9533949 (5511)	total: 24m 5s	remaining: 14m 37s
5800:	test: 0.9534093	best: 0.9534103 (5753)	total: 24m 58s	remaining: 13m 46s
6000:	test: 0.9534233	best: 0.9534304 (5977)	total: 25m 51s	remaining: 12m 55s
6200:	test: 0.9534349	best: 0.9534349 (6200)	total: 26m 43s	remaining: 12m 3s
6400:	test: 0.9534382	best: 0.9534410 (6382)	total: 27m 36s	remaining: 11m 12s
6600:	test: 0.9534475	best: 0.9534485 (6515)	total: 28m 27s	remaining: 10m 20s
6800:	test: 0.9534514	best: 0.9534525 (6778)	total: 29m 20s	remaining: 9m 29s
7000:	test: 0.9534645	best: 0.9534701 (6951)	total: 30m 13s	remaining: 8m 37s
7200:	test: 0.9534757	best: 0.9534791 (7102)	total: 31m 4s	remaining: 7m 45s
7400:	test: 0.9534844	best: 0.9534875 (7311)	total: 31m 57s	remaining: 6m 54s
7600:	test: 0.9534765	best: 0.9534875 (7311)	total: 32m 50s	remaining: 6m 2s
bestTest = 0.9534875154
bestIteration = 7311
Shrink model to first 7312 iterations.
Fold 3 AUC    : 0.953487476
Fold 3 LogLoss: 0.262518212
Fold 3 best_iter: 7311
Fold 3 used_device: GPU

==========================================================================================
Fold 4/5
==========================================================================================
X_tr: (452683, 337) target mean: 0.2114813235752171
X_va: (87828, 337) target mean: 0.19897982420184906
X_test: (188165, 337)

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9292786	best: 0.9292786 (0)	total: 340ms	remaining: 51m 1s
200:	test: 0.9437318	best: 0.9437318 (200)	total: 48.3s	remaining: 35m 13s
400:	test: 0.9465084	best: 0.9465084 (400)	total: 1m 35s	remaining: 34m 17s
600:	test: 0.9482685	best: 0.9482685 (600)	total: 2m 23s	remaining: 33m 22s
800:	test: 0.9491844	best: 0.9491844 (800)	total: 3m 10s	remaining: 32m 32s
1000:	test: 0.9498970	best: 0.9498970 (1000)	total: 4m 3s	remaining: 32m 24s
1200:	test: 0.9503939	best: 0.9503939 (1200)	total: 4m 55s	remaining: 31m 56s
1400:	test: 0.9507328	best: 0.9507328 (1399)	total: 5m 48s	remaining: 31m 32s
1600:	test: 0.9509824	best: 0.9509824 (1600)	total: 6m 41s	remaining: 30m 53s
1800:	test: 0.9511698	best: 0.9511698 (1800)	total: 7m 33s	remaining: 30m 14s
2000:	test: 0.9513271	best: 0.9513271 (2000)	total: 8m 26s	remaining: 29m 31s
2200:	test: 0.9514717	best: 0.9514717 (2200)	total: 9m 19s	remaining: 28m 49s
2400:	test: 0.9515849	best: 0.9515849 (2400)	total: 10m 12s	remaining: 28m 4s
2600:	test: 0.9516964	best: 0.9516965 (2599)	total: 11m 4s	remaining: 27m 15s
2800:	test: 0.9518028	best: 0.9518028 (2800)	total: 11m 56s	remaining: 26m 26s
3000:	test: 0.9518802	best: 0.9518807 (2992)	total: 12m 49s	remaining: 25m 38s
3200:	test: 0.9519494	best: 0.9519494 (3200)	total: 13m 42s	remaining: 24m 50s
3400:	test: 0.9520169	best: 0.9520169 (3400)	total: 14m 35s	remaining: 24m
3600:	test: 0.9520722	best: 0.9520722 (3599)	total: 15m 26s	remaining: 23m 9s
3800:	test: 0.9521303	best: 0.9521303 (3800)	total: 16m 18s	remaining: 22m 17s
4000:	test: 0.9521876	best: 0.9521876 (4000)	total: 17m 9s	remaining: 21m 25s
4200:	test: 0.9522355	best: 0.9522355 (4200)	total: 18m 1s	remaining: 20m 35s
4400:	test: 0.9522609	best: 0.9522610 (4399)	total: 18m 54s	remaining: 19m 45s
4600:	test: 0.9523015	best: 0.9523015 (4597)	total: 19m 46s	remaining: 18m 54s
4800:	test: 0.9523308	best: 0.9523308 (4799)	total: 20m 38s	remaining: 18m 3s
5000:	test: 0.9523609	best: 0.9523612 (4998)	total: 21m 31s	remaining: 17m 13s
5200:	test: 0.9523962	best: 0.9523965 (5198)	total: 22m 23s	remaining: 16m 21s
5400:	test: 0.9524146	best: 0.9524156 (5399)	total: 23m 15s	remaining: 15m 29s
5600:	test: 0.9524441	best: 0.9524441 (5600)	total: 24m 7s	remaining: 14m 38s
5800:	test: 0.9524655	best: 0.9524683 (5790)	total: 24m 58s	remaining: 13m 46s
6000:	test: 0.9524869	best: 0.9524881 (5987)	total: 25m 51s	remaining: 12m 55s
6200:	test: 0.9524989	best: 0.9525016 (6144)	total: 26m 44s	remaining: 12m 4s
6400:	test: 0.9525157	best: 0.9525157 (6400)	total: 27m 36s	remaining: 11m 12s
6600:	test: 0.9525409	best: 0.9525412 (6596)	total: 28m 30s	remaining: 10m 21s
6800:	test: 0.9525442	best: 0.9525451 (6795)	total: 29m 23s	remaining: 9m 30s
7000:	test: 0.9525651	best: 0.9525662 (6930)	total: 30m 14s	remaining: 8m 38s
7200:	test: 0.9525630	best: 0.9525719 (7075)	total: 31m 7s	remaining: 7m 46s
7400:	test: 0.9525755	best: 0.9525813 (7359)	total: 31m 59s	remaining: 6m 54s
7600:	test: 0.9525714	best: 0.9525813 (7359)	total: 32m 51s	remaining: 6m 2s
bestTest = 0.952581346
bestIteration = 7359
Shrink model to first 7360 iterations.
Fold 4 AUC    : 0.952581339
Fold 4 LogLoss: 0.262292019
Fold 4 best_iter: 7359
Fold 4 used_device: GPU

==========================================================================================
Fold 5/5
==========================================================================================
X_tr: (452683, 337) target mean: 0.2114813235752171
X_va: (87828, 337) target mean: 0.19897982420184906
X_test: (188165, 337)

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9289547	best: 0.9289547 (0)	total: 269ms	remaining: 40m 25s
200:	test: 0.9447229	best: 0.9447229 (200)	total: 48.8s	remaining: 35m 37s
400:	test: 0.9478984	best: 0.9478984 (400)	total: 1m 36s	remaining: 34m 24s
600:	test: 0.9496977	best: 0.9496977 (600)	total: 2m 22s	remaining: 33m 11s
800:	test: 0.9506592	best: 0.9506592 (800)	total: 3m 10s	remaining: 32m 30s
1000:	test: 0.9513823	best: 0.9513823 (1000)	total: 4m 2s	remaining: 32m 17s
1200:	test: 0.9518432	best: 0.9518432 (1200)	total: 4m 56s	remaining: 32m 2s
1400:	test: 0.9521804	best: 0.9521804 (1400)	total: 5m 49s	remaining: 31m 34s
1600:	test: 0.9524302	best: 0.9524302 (1600)	total: 6m 42s	remaining: 30m 57s
1800:	test: 0.9526328	best: 0.9526333 (1799)	total: 7m 34s	remaining: 30m 17s
2000:	test: 0.9528000	best: 0.9528007 (1999)	total: 8m 28s	remaining: 29m 38s
2200:	test: 0.9529361	best: 0.9529361 (2200)	total: 9m 21s	remaining: 28m 53s
2400:	test: 0.9530369	best: 0.9530369 (2400)	total: 10m 13s	remaining: 28m 6s
2600:	test: 0.9531429	best: 0.9531431 (2597)	total: 11m 6s	remaining: 27m 19s
2800:	test: 0.9532297	best: 0.9532298 (2799)	total: 11m 58s	remaining: 26m 29s
3000:	test: 0.9533025	best: 0.9533026 (2999)	total: 12m 50s	remaining: 25m 40s
3200:	test: 0.9533760	best: 0.9533760 (3197)	total: 13m 42s	remaining: 24m 50s
3400:	test: 0.9534543	best: 0.9534543 (3400)	total: 14m 34s	remaining: 23m 59s
3600:	test: 0.9534943	best: 0.9534946 (3591)	total: 15m 26s	remaining: 23m 9s
3800:	test: 0.9535419	best: 0.9535419 (3800)	total: 16m 19s	remaining: 22m 19s
4000:	test: 0.9535639	best: 0.9535649 (3962)	total: 17m 11s	remaining: 21m 28s
4200:	test: 0.9536116	best: 0.9536120 (4199)	total: 18m 3s	remaining: 20m 38s
4400:	test: 0.9536361	best: 0.9536372 (4381)	total: 18m 55s	remaining: 19m 46s
4600:	test: 0.9536725	best: 0.9536752 (4587)	total: 19m 48s	remaining: 18m 56s
4800:	test: 0.9536929	best: 0.9536950 (4728)	total: 20m 41s	remaining: 18m 5s
5000:	test: 0.9537240	best: 0.9537268 (4993)	total: 21m 33s	remaining: 17m 14s
5200:	test: 0.9537565	best: 0.9537565 (5200)	total: 22m 25s	remaining: 16m 23s
5400:	test: 0.9537851	best: 0.9537858 (5340)	total: 23m 17s	remaining: 15m 31s
5600:	test: 0.9538090	best: 0.9538095 (5599)	total: 24m 9s	remaining: 14m 39s
5800:	test: 0.9538239	best: 0.9538242 (5799)	total: 25m 1s	remaining: 13m 48s
6000:	test: 0.9538521	best: 0.9538525 (5999)	total: 25m 54s	remaining: 12m 56s
6200:	test: 0.9538565	best: 0.9538606 (6133)	total: 26m 46s	remaining: 12m 4s
6400:	test: 0.9538667	best: 0.9538676 (6374)	total: 27m 39s	remaining: 11m 13s
6600:	test: 0.9538728	best: 0.9538742 (6533)	total: 28m 32s	remaining: 10m 22s
6800:	test: 0.9538864	best: 0.9538866 (6782)	total: 29m 25s	remaining: 9m 30s
7000:	test: 0.9538955	best: 0.9538986 (6970)	total: 30m 18s	remaining: 8m 39s
7200:	test: 0.9539004	best: 0.9539021 (7194)	total: 31m 10s	remaining: 7m 47s
7400:	test: 0.9539160	best: 0.9539171 (7368)	total: 32m 3s	remaining: 6m 55s
7600:	test: 0.9539280	best: 0.9539297 (7597)	total: 32m 56s	remaining: 6m 3s
7800:	test: 0.9539439	best: 0.9539439 (7800)	total: 33m 50s	remaining: 5m 12s
8000:	test: 0.9539528	best: 0.9539533 (7996)	total: 34m 43s	remaining: 4m 20s
8200:	test: 0.9539669	best: 0.9539669 (8200)	total: 35m 34s	remaining: 3m 27s
8400:	test: 0.9539698	best: 0.9539701 (8224)	total: 36m 26s	remaining: 2m 35s
8600:	test: 0.9539672	best: 0.9539751 (8439)	total: 37m 20s	remaining: 1m 43s
bestTest = 0.953975141
bestIteration = 8439
Shrink model to first 8440 iterations.
Fold 5 AUC    : 0.953975114
Fold 5 LogLoss: 0.255981556
Fold 5 best_iter: 8439
Fold 5 used_device: GPU

In [12]:
# ============================================================
# CV result
# ============================================================

print_section("CV Result")

cv_auc = roc_auc_score(y_comp, oof)
cv_logloss = log_loss(y_comp, clip_pred(oof))

fold_df = pd.DataFrame(fold_records)

print(f"Overall CV AUC    : {cv_auc:.9f}")
print(f"Overall CV LogLoss: {cv_logloss:.9f}")
print("fold auc mean:", fold_df["auc"].mean())
print("fold auc std :", fold_df["auc"].std())
print("used devices :", sorted(set(used_devices)))

print(fold_df)

==========================================================================================
CV Result
==========================================================================================
Overall CV AUC    : 0.953361477
Overall CV LogLoss: 0.260605062
fold auc mean: 0.9533713576817572
fold auc std : 0.0008231311147775614
used devices : ['GPU']
   fold       auc   logloss  best_iteration used_device  n_train_comp  \
0     1  0.954330  0.259582            8191         GPU        351312
1     2  0.952483  0.262651            7608         GPU        351312
2     3  0.953487  0.262518            7311         GPU        351312
3     4  0.952581  0.262292            7359         GPU        351312
4     5  0.953975  0.255982            8439         GPU        351312

   n_train_orig  n_valid  n_features  n_cat_features
0        101371    87828         337              93
1        101371    87828         337              93
2        101371    87828         337              93
3        101371    87828         337              93
4        101371    87828         337              93

In [13]:
# ============================================================
# Save artifacts
# ============================================================

print_section("Save Artifacts")

np.save(CFG.OUTDIR / f"oof_{CFG.EXP_ID}.npy", oof)
np.save(CFG.OUTDIR / f"pred_{CFG.EXP_ID}.npy", pred)

oof_csv = pd.DataFrame({
    CFG.ID_COL: train_ids,
    CFG.TARGET: y_comp.values,
    "pred": oof,
})
oof_csv.to_csv(CFG.OUTDIR / f"oof_{CFG.EXP_ID}.csv", index=False)

sub = sample_submission.copy()
sub[CFG.TARGET] = clip_pred(pred)

sub_path = CFG.OUTDIR / f"submission_{CFG.EXP_ID}.csv"
sub.to_csv(sub_path, index=False)

fold_df.to_csv(CFG.OUTDIR / "fold_scores.csv", index=False)

fi_all = pd.concat(feature_importance_records, axis=0, ignore_index=True)
fi_summary = (
    fi_all
    .groupby("feature", as_index=False)["importance"]
    .agg(["mean", "std"])
    .reset_index()
    .sort_values("mean", ascending=False)
)
fi_all.to_csv(CFG.OUTDIR / "feature_importance_by_fold.csv", index=False)
fi_summary.to_csv(CFG.OUTDIR / "feature_importance.csv", index=False)

feature_df = pd.DataFrame({
    "feature": common_features,
    "is_cat": [c in cat_cols for c in common_features],
    "is_count": [c.endswith("_count") for c in common_features],
    "is_freq": [c.endswith("_freq") for c in common_features],
    "is_digit": [
        ("_int_digit_" in c) or ("_dec_digit_" in c) or ("_sig_" in c)
        for c in common_features
    ],
    "is_string_precision": [
        c in ["RaceProgress_str", "EstimatedTotalLaps_str", "TyreAgeRatio_str"]
        for c in common_features
    ],
    "is_group_stat": [
        ("_mean_by_" in c) or ("_std_by_" in c) or ("_diff_mean_by_" in c)
        for c in common_features
    ],
    "is_race_year_group_stat": [
        is_race_year_groupstat_feature(c)
        for c in common_features
    ],
    "contains_year": ["Year" in c for c in common_features],
    "contains_race_year": ["Race_Year" in c for c in common_features],
    "is_shared001v2_042": [
        c.endswith("_floor_cat_042")
        or c in [
            "PitStop_cat_",
            "Race_Year_",
            "Race_Compound_",
            "RaceProgress_200_quantile_bin_",
            "LapTime (s)_7_quantile_bin_",
        ]
        or c.startswith("_PitStop_cat_")
        or c.startswith("_Race_Year__")
        or c.startswith("_Race_Compound__")
        or c.startswith("_RaceProgress_200_quantile_bin__")
        or c.startswith("_LapTime_s_7_quantile_bin__")
        for c in common_features
    ],
})
feature_df["is_optuna_refit_046"] = False
feature_df.to_csv(CFG.OUTDIR / "feature_columns.csv", index=False)

pd.DataFrame({
    "dropped_feature": dropped_groupstat_features_015,
    "reason": [
        "Inherited 015/042 policy: remove Race_Year group-stat feature"
        for _ in dropped_groupstat_features_015
    ],
}).to_csv(CFG.OUTDIR / "dropped_features_race_year_groupstats.csv", index=False)

assert "Race_Year" in common_features
assert "IsOriginalData" in common_features
assert "TyreAgeRatio_str" in common_features
assert not any(is_race_year_groupstat_feature(c) for c in common_features)
assert not feature_df["is_race_year_group_stat"].any()

cat_feature_df = pd.DataFrame({
    "cat_feature": cat_cols,
    "index": cat_features,
})
cat_feature_df.to_csv(CFG.OUTDIR / "categorical_features.csv", index=False)

assert "Race_Year" in cat_cols
assert "IsOriginalData" in common_features
assert "TyreAgeRatio_str" in cat_cols

# Effective params after applying 045 Optuna best params.
effective_cat_params = get_catboost_params(
    seed=CFG.SEED,
    iterations=CFG.ITERATIONS,
    task_type=CFG.TASK_TYPE,
)
effective_cat_params_for_json = {
    k: v
    for k, v in effective_cat_params.items()
    if k not in ["verbose"]
}

result = {
    "experiment": {
        "id": CFG.EXP_ID,
        "competition": CFG.COMPETITION,
        "metric": CFG.METRIC,
        "type": "optuna_refit",
        "created_at": "2026-05-20",
    },
    "base": {
        "model_structure": "exp_20260520_042_cat_shared001v2_features_min",
        "params_source": "exp_20260520_045_cat_shared001v2_features_optuna_search_min",
        "best_params_path": CFG.BEST_PARAMS_PATH,
        "baseline_042_cv_auc": 0.953240915414691,
        "baseline_042_public_lb": 0.95283,
        "optuna_045_best_cv_auc": 0.953352253739158,
        "note": [
            "046 keeps the exact 042 feature engineering, folds, original-row policy, and guardrails.",
            "Only CatBoost hyperparameters are replaced by 045 Optuna best params.",
            "039 LOG features are not added.",
            "No new feature engineering is added in 046.",
        ],
    },
    "optuna": {
        "best_params": CFG.BEST_PARAMS,
        "best_params_source_raw": CFG.BEST_PARAMS_SOURCE_RAW,
        "search_experiment": "exp_20260520_045_cat_shared001v2_features_optuna_search_min",
        "search_baseline": "exp_20260520_042_cat_shared001v2_features_min",
    },
    "data": {
        "train_shape": list(train_raw.shape),
        "test_shape": list(test_raw.shape),
        "original_available": original_raw is not None,
        "original_shape_after_drop": list(original_raw.shape) if original_raw is not None else None,
        "target": CFG.TARGET,
        "id_col": CFG.ID_COL,
        "danger_col": CFG.DANGER_COL,
        "danger_col_used": False,
        "use_original_rows": CFG.USE_ORIGINAL,
        "competition_target_mean": float(train_raw[CFG.TARGET].mean()),
        "original_target_mean": float(original_raw[CFG.TARGET].mean()) if original_raw is not None else None,
    },
    "features": {
        "n_features": int(len(common_features)),
        "n_cat_features": int(len(cat_cols)),
        "dropped_race_year_groupstat_features": dropped_groupstat_features_015,
        "dropped_race_year_groupstat_feature_count": int(len(dropped_groupstat_features_015)),
        "race_year_used": "Race_Year" in common_features,
        "isoriginaldata_used": "IsOriginalData" in common_features,
        "tyreageratio_str_used": "TyreAgeRatio_str" in common_features,
        "race_year_groupstats_used": any(
            is_race_year_groupstat_feature(c) for c in common_features
        ),
        "shared001v2_042_feature_count": int(feature_df["is_shared001v2_042"].sum()),
        "feature_blocks": [
            "domain_features",
            "digit_features",
            "float_signature_features",
            "string_precision_features",
            "shared001v2_style_features_042",
            "frequency_features",
            "shared001v2_count_features_042",
            "light_group_stats_without_race_year_groupstats",
        ],
        "normalized_tyrelife_policy": [
            "Normalized_TyreLife is dropped.",
            "Direct use is forbidden.",
            "Intentional proxy reconstruction is not added.",
        ],
    },
    "model": {
        "family": "CatBoost",
        "estimator": "CatBoostClassifier",
        "params_effective": effective_cat_params_for_json,
        "params_from_045": CFG.BEST_PARAMS,
        "fixed_params": {
            "iterations": CFG.ITERATIONS,
            "bootstrap_type": CFG.BOOTSTRAP_TYPE,
            "subsample": CFG.SUBSAMPLE,
            "loss_function": "Logloss",
            "eval_metric": "AUC",
            "auto_class_weights": CFG.AUTO_CLASS_WEIGHTS,
            "early_stopping_rounds": CFG.EARLY_STOPPING_ROUNDS,
            "task_type_requested": CFG.TASK_TYPE,
            "devices_requested": CFG.DEVICES,
            "devices_used": sorted(set(used_devices)),
        },
        "cv": {
            "scheme": "StratifiedKFold",
            "n_splits": CFG.N_SPLITS,
            "shuffle": True,
            "random_state": CFG.SEED,
        },
    },
    "result": {
        "cv_auc": float(cv_auc),
        "cv_logloss": float(cv_logloss),
        "fold_auc_mean": float(fold_df["auc"].mean()),
        "fold_auc_std": float(fold_df["auc"].std()),
        "fold_scores": fold_records,
        "comparison_to_042": {
            "baseline_cv_auc": 0.953240915414691,
            "delta_cv_auc": float(cv_auc - 0.953240915414691),
            "baseline_public_lb": 0.95283,
            "public_lb": None,
        },
        "comparison_to_045_search": {
            "optuna_best_cv_auc": 0.953352253739158,
            "delta_cv_auc": float(cv_auc - 0.953352253739158),
        },
    },
    "artifacts": {
        "outdir": str(CFG.OUTDIR),
        "oof_npy": str(CFG.OUTDIR / f"oof_{CFG.EXP_ID}.npy"),
        "pred_npy": str(CFG.OUTDIR / f"pred_{CFG.EXP_ID}.npy"),
        "oof_csv": str(CFG.OUTDIR / f"oof_{CFG.EXP_ID}.csv"),
        "submission": str(sub_path),
        "fold_scores": str(CFG.OUTDIR / "fold_scores.csv"),
        "feature_columns": str(CFG.OUTDIR / "feature_columns.csv"),
        "categorical_features": str(CFG.OUTDIR / "categorical_features.csv"),
        "feature_importance": str(CFG.OUTDIR / "feature_importance.csv"),
        "cv_result": str(CFG.OUTDIR / "cv_result.json"),
        "dropped_features": str(CFG.OUTDIR / "dropped_features_race_year_groupstats.csv"),
        "memo_draft": str(CFG.OUTDIR / "memo_draft.yml"),
    },
    "success_criteria": {
        "single": {
            "cv_must_exceed_042": 0.953240915414691,
            "public_lb_must_exceed_042": 0.95283,
            "strong_if_cv_at_least": 0.95335,
        },
        "blend": {
            "nm_cv_must_exceed": 0.9550053246176218,
            "nm_public_lb_must_be_at_least": 0.95431,
            "logreg_public_lb_must_exceed": 0.95430,
        },
    },
    "decision_policy": {
        "single_model": [
            "Compare 046 against 042 single CV/LB.",
            "Single CV improvement alone is not enough for final promotion.",
            "Single CV and Public LB both improving means proceed to add046 blend as a serious candidate.",
        ],
        "blend": [
            "Add 046 to the current standard/pruned stack and compare NM/LogReg against add044 and add042.",
            "Promote only if add046 NM or LogReg improves both CV and Public LB, or maintains Public best with structurally better risk.",
        ],
    },
}

with open(CFG.OUTDIR / "cv_result.json", "w", encoding="utf-8") as f:
    json.dump(result, f, ensure_ascii=False, indent=2)

# ------------------------------------------------------------
# memo_draft.yml
# ------------------------------------------------------------
memo_draft = f"""experiment:
  id: {CFG.EXP_ID}
  competition: {CFG.COMPETITION}
  metric: AUC
  created_at: 2026-05-20
  type: optuna_refit
  status: completed

objective:
  summary: >
    045 Optuna searchで得たbest CatBoost paramsを、042 CatBoost shared001v2 features構成へ適用し、
    正式な5fold OOF/pred/submissionを作成する。
    046では特徴量・fold・original rows append・禁止列処理は042から変更しない。
  purpose:
    - 042単体CV/LBをOptuna paramsで更新できるか確認する
    - add046 blendでadd044_nm / add042_logregを置換できるか確認する
  not_purpose:
    - 新規特徴量追加
    - 039 LOG特徴の追加
    - pseudo label
    - stack構成変更

base:
  model_structure: exp_20260520_042_cat_shared001v2_features_min
  params_source: exp_20260520_045_cat_shared001v2_features_optuna_search_min
  baseline_042:
    cv_auc: 0.953240915414691
    public_lb: 0.95283
  optuna_045:
    best_cv_auc: 0.953352253739158
    best_params_path: {CFG.BEST_PARAMS_PATH}

best_params_from_045:
"""
for k, v in CFG.BEST_PARAMS.items():
    memo_draft += f"  {k}: {v}\n"

memo_draft += f"""
fixed_from_042:
  feature_set: same_as_042
  folds: same_as_042
  original_rows: same_as_042
  target: {CFG.TARGET}
  metric: AUC
  forbidden:
    - Normalized_TyreLife
    - Normalized_TyreLife proxy
    - future endpoint proxy
    - pseudo label
    - new feature engineering
  inherited_policy:
    - Race_Year group-stat features are dropped
    - Race_Year itself is kept
    - IsOriginalData is kept
    - TyreAgeRatio_str is kept
    - 039 LOG features are not added

data:
  train_shape: {list(train_raw.shape)}
  test_shape: {list(test_raw.shape)}
  original_available: {original_raw is not None}
  original_shape_after_drop: {list(original_raw.shape) if original_raw is not None else None}
  target: {CFG.TARGET}
  use_original_rows: {CFG.USE_ORIGINAL}

features:
  n_features: {int(len(common_features))}
  n_cat_features: {int(len(cat_cols))}
  shared001v2_042_feature_count: {int(feature_df["is_shared001v2_042"].sum())}
  dropped_race_year_groupstat_feature_count: {int(len(dropped_groupstat_features_015))}
  race_year_used: {"Race_Year" in common_features}
  race_year_groupstats_used: {any(is_race_year_groupstat_feature(c) for c in common_features)}
  isoriginaldata_used: {"IsOriginalData" in common_features}
  tyreageratio_str_used: {"TyreAgeRatio_str" in common_features}

model:
  family: CatBoost
  params_effective:
"""
for k, v in effective_cat_params_for_json.items():
    memo_draft += f"    {k}: {v}\n"

memo_draft += f"""  cv:
    scheme: StratifiedKFold
    n_splits: {CFG.N_SPLITS}
    shuffle: true
    random_state: {CFG.SEED}

result:
  cv_auc: {float(cv_auc)}
  cv_logloss: {float(cv_logloss)}
  fold_auc_mean: {float(fold_df["auc"].mean())}
  fold_auc_std: {float(fold_df["auc"].std())}
  public_lb: null
  comparison_to_042:
    baseline_cv_auc: 0.953240915414691
    delta_cv_auc: {float(cv_auc - 0.953240915414691)}
    baseline_public_lb: 0.95283
  comparison_to_045_search:
    optuna_best_cv_auc: 0.953352253739158
    delta_cv_auc: {float(cv_auc - 0.953352253739158)}

outputs:
  oof_npy: oof_{CFG.EXP_ID}.npy
  pred_npy: pred_{CFG.EXP_ID}.npy
  submission: submission_{CFG.EXP_ID}.csv
  cv_result: cv_result.json
  memo_draft: memo_draft.yml
  feature_columns: feature_columns.csv
  feature_importance: feature_importance.csv
  categorical_features: categorical_features.csv

success_criteria:
  single:
    cv_must_exceed_042: 0.953240915414691
    public_lb_must_exceed_042: 0.95283
    strong_if_cv_at_least: 0.95335
  blend:
    nm_cv_must_exceed: 0.9550053246176218
    nm_public_lb_must_be_at_least: 0.95431
    logreg_public_lb_must_exceed: 0.95430

judgement:
  decision: pending
  notes: >
    まず046単体CVとPublic LBを042と比較する。
    単体CVだけ改善しても採用しない。
    次にadd046 blendでadd044_nmおよびadd042_logregを超えるか確認する。
    CVだけでなくPublic LBとstack内重みを必ず確認する。
"""

with open(CFG.OUTDIR / "memo_draft.yml", "w", encoding="utf-8") as f:
    f.write(memo_draft)

print("Saved to:", CFG.OUTDIR)
print("Submission:", sub_path)
print(json.dumps(result, ensure_ascii=False, indent=2))

print_section("Top Feature Importance")
display(fi_summary.head(80))

print_section("Submission Preview")
display(sub.head())

==========================================================================================
Save Artifacts
==========================================================================================
Saved to: /kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min
Submission: /kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/submission_exp_20260520_046_cat_shared001v2_features_optuna_refit_min.csv
{
  "experiment": {
    "id": "exp_20260520_046_cat_shared001v2_features_optuna_refit_min",
    "competition": "PS S6E5 Predicting F1 Pit Stops",
    "metric": "AUC",
    "type": "optuna_refit",
    "created_at": "2026-05-20"
  },
  "base": {
    "model_structure": "exp_20260520_042_cat_shared001v2_features_min",
    "params_source": "exp_20260520_045_cat_shared001v2_features_optuna_search_min",
    "best_params_path": "/kaggle/input/datasets/mizushimatoshihiko/npy-files/exp_20260520_045_cat_shared001v2_features_optuna_search_min/best_params_045.json",
    "baseline_042_cv_auc": 0.953240915414691,
    "baseline_042_public_lb": 0.95283,
    "optuna_045_best_cv_auc": 0.953352253739158,
    "note": [
      "046 keeps the exact 042 feature engineering, folds, original-row policy, and guardrails.",
      "Only CatBoost hyperparameters are replaced by 045 Optuna best params.",
      "039 LOG features are not added.",
      "No new feature engineering is added in 046."
    ]
  },
  "optuna": {
    "best_params": {
      "learning_rate": 0.015888820918127773,
      "depth": 8,
      "l2_leaf_reg": 2.411289811529197,
      "random_strength": 1.325044568707964,
      "min_data_in_leaf": 13,
      "border_count": 254
    },
    "best_params_source_raw": {
      "learning_rate": 0.015888820918127773,
      "depth": 8,
      "l2_leaf_reg": 2.411289811529197,
      "random_strength": 1.325044568707964,
      "min_data_in_leaf": 13,
      "border_count": 254
    },
    "search_experiment": "exp_20260520_045_cat_shared001v2_features_optuna_search_min",
    "search_baseline": "exp_20260520_042_cat_shared001v2_features_min"
  },
  "data": {
    "train_shape": [
      439140,
      16
    ],
    "test_shape": [
      188165,
      15
    ],
    "original_available": true,
    "original_shape_after_drop": [
      101371,
      15
    ],
    "target": "PitNextLap",
    "id_col": "id",
    "danger_col": "Normalized_TyreLife",
    "danger_col_used": false,
    "use_original_rows": true,
    "competition_target_mean": 0.1989821046590805,
    "original_target_mean": 0.25479673673930414
  },
  "features": {
    "n_features": 337,
    "n_cat_features": 93,
    "dropped_race_year_groupstat_features": [
      "LapTime_Delta_mean_by_Race_Year",
      "LapTime_Delta_std_by_Race_Year",
      "LapTime_Delta_diff_mean_by_Race_Year",
      "Position_Change_mean_by_Race_Year",
      "Position_Change_std_by_Race_Year",
      "Position_Change_diff_mean_by_Race_Year",
      "RaceProgress_mean_by_Race_Year",
      "RaceProgress_std_by_Race_Year",
      "RaceProgress_diff_mean_by_Race_Year",
      "TyreLife_mean_by_Race_Year",
      "TyreLife_std_by_Race_Year",
      "TyreLife_diff_mean_by_Race_Year"
    ],
    "dropped_race_year_groupstat_feature_count": 12,
    "race_year_used": true,
    "isoriginaldata_used": true,
    "tyreageratio_str_used": true,
    "race_year_groupstats_used": false,
    "shared001v2_042_feature_count": 26,
    "feature_blocks": [
      "domain_features",
      "digit_features",
      "float_signature_features",
      "string_precision_features",
      "shared001v2_style_features_042",
      "frequency_features",
      "shared001v2_count_features_042",
      "light_group_stats_without_race_year_groupstats"
    ],
    "normalized_tyrelife_policy": [
      "Normalized_TyreLife is dropped.",
      "Direct use is forbidden.",
      "Intentional proxy reconstruction is not added."
    ]
  },
  "model": {
    "family": "CatBoost",
    "estimator": "CatBoostClassifier",
    "params_effective": {
      "iterations": 9000,
      "learning_rate": 0.015888820918127773,
      "depth": 8,
      "l2_leaf_reg": 2.411289811529197,
      "random_strength": 1.325044568707964,
      "bootstrap_type": "Bernoulli",
      "subsample": 0.8,
      "border_count": 254,
      "loss_function": "Logloss",
      "eval_metric": "AUC",
      "auto_class_weights": "Balanced",
      "task_type": "GPU",
      "random_seed": 42,
      "early_stopping_rounds": 350,
      "allow_writing_files": false,
      "min_data_in_leaf": 13,
      "devices": "0:1"
    },
    "params_from_045": {
      "learning_rate": 0.015888820918127773,
      "depth": 8,
      "l2_leaf_reg": 2.411289811529197,
      "random_strength": 1.325044568707964,
      "min_data_in_leaf": 13,
      "border_count": 254
    },
    "fixed_params": {
      "iterations": 9000,
      "bootstrap_type": "Bernoulli",
      "subsample": 0.8,
      "loss_function": "Logloss",
      "eval_metric": "AUC",
      "auto_class_weights": "Balanced",
      "early_stopping_rounds": 350,
      "task_type_requested": "GPU",
      "devices_requested": "0:1",
      "devices_used": [
        "GPU"
      ]
    },
    "cv": {
      "scheme": "StratifiedKFold",
      "n_splits": 5,
      "shuffle": true,
      "random_state": 42
    }
  },
  "result": {
    "cv_auc": 0.9533614771835248,
    "cv_logloss": 0.26060506238336834,
    "fold_auc_mean": 0.9533713576817572,
    "fold_auc_std": 0.0008231311147775614,
    "fold_scores": [
      {
        "fold": 1,
        "auc": 0.9543298971806439,
        "logloss": 0.25958244194627655,
        "best_iteration": 8191,
        "used_device": "GPU",
        "n_train_comp": 351312,
        "n_train_orig": 101371,
        "n_valid": 87828,
        "n_features": 337,
        "n_cat_features": 93
      },
      {
        "fold": 2,
        "auc": 0.9524829619644588,
        "logloss": 0.262651083270529,
        "best_iteration": 7608,
        "used_device": "GPU",
        "n_train_comp": 351312,
        "n_train_orig": 101371,
        "n_valid": 87828,
        "n_features": 337,
        "n_cat_features": 93
      },
      {
        "fold": 3,
        "auc": 0.9534874760567049,
        "logloss": 0.26251821200150105,
        "best_iteration": 7311,
        "used_device": "GPU",
        "n_train_comp": 351312,
        "n_train_orig": 101371,
        "n_valid": 87828,
        "n_features": 337,
        "n_cat_features": 93
      },
      {
        "fold": 4,
        "auc": 0.9525813391898635,
        "logloss": 0.26229201874468266,
        "best_iteration": 7359,
        "used_device": "GPU",
        "n_train_comp": 351312,
        "n_train_orig": 101371,
        "n_valid": 87828,
        "n_features": 337,
        "n_cat_features": 93
      },
      {
        "fold": 5,
        "auc": 0.9539751140171155,
        "logloss": 0.25598155595385214,
        "best_iteration": 8439,
        "used_device": "GPU",
        "n_train_comp": 351312,
        "n_train_orig": 101371,
        "n_valid": 87828,
        "n_features": 337,
        "n_cat_features": 93
      }
    ],
    "comparison_to_042": {
      "baseline_cv_auc": 0.953240915414691,
      "delta_cv_auc": 0.00012056176883379344,
      "baseline_public_lb": 0.95283,
      "public_lb": null
    },
    "comparison_to_045_search": {
      "optuna_best_cv_auc": 0.953352253739158,
      "delta_cv_auc": 9.223444366823763e-06
    }
  },
  "artifacts": {
    "outdir": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min",
    "oof_npy": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/oof_exp_20260520_046_cat_shared001v2_features_optuna_refit_min.npy",
    "pred_npy": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/pred_exp_20260520_046_cat_shared001v2_features_optuna_refit_min.npy",
    "oof_csv": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/oof_exp_20260520_046_cat_shared001v2_features_optuna_refit_min.csv",
    "submission": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/submission_exp_20260520_046_cat_shared001v2_features_optuna_refit_min.csv",
    "fold_scores": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/fold_scores.csv",
    "feature_columns": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/feature_columns.csv",
    "categorical_features": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/categorical_features.csv",
    "feature_importance": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/feature_importance.csv",
    "cv_result": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/cv_result.json",
    "dropped_features": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/dropped_features_race_year_groupstats.csv",
    "memo_draft": "/kaggle/working/exp_20260520_046_cat_shared001v2_features_optuna_refit_min/memo_draft.yml"
  },
  "success_criteria": {
    "single": {
      "cv_must_exceed_042": 0.953240915414691,
      "public_lb_must_exceed_042": 0.95283,
      "strong_if_cv_at_least": 0.95335
    },
    "blend": {
      "nm_cv_must_exceed": 0.9550053246176218,
      "nm_public_lb_must_be_at_least": 0.95431,
      "logreg_public_lb_must_exceed": 0.9543
    }
  },
  "decision_policy": {
    "single_model": [
      "Compare 046 against 042 single CV/LB.",
      "Single CV improvement alone is not enough for final promotion.",
      "Single CV and Public LB both improving means proceed to add046 blend as a serious candidate."
    ],
    "blend": [
      "Add 046 to the current standard/pruned stack and compare NM/LogReg against add044 and add042.",
      "Promote only if add046 NM or LogReg improves both CV and Public LB, or maintains Public best with structurally better risk."
    ]
  }
}

==========================================================================================
Top Feature Importance
==========================================================================================

     index                              feature      mean       std
95      95                       IsOriginalData  4.493267  0.158134
242    242                  Race_Compound_Stint  3.654062  0.207650
301    301                   Year_floor_cat_042  3.474766  0.428037
275    275                     TyreAgeRatio_str  2.948082  0.167633
247    247                            Race_Year  2.599687  0.180137
..     ...                                  ...       ...       ...
117    117          LapTime (s)_7_quantile_bin_  0.425134  0.125682
68      68                DeltaPerTyreLap_sig_2  0.422290  0.045659
74      74                Driver_Compound_count  0.418985  0.021913
240    240                        Race_Compound  0.416695  0.036531
204    204  Position_Change_mean_by_Driver_Race  0.411411  0.030532

[80 rows x 4 columns]

==========================================================================================
Submission Preview
==========================================================================================

       id  PitNextLap
0  439140    0.022361
1  439141    0.018778
2  439142    0.015711
3  439143    0.477897
4  439144    0.946221