# 050 Blend Add047 + 048 + 049 Check

Blend/correlation check after adding 047, 048, and 049 to the 046 candidate pool.

Purpose:
- Test whether 049, which improved Public LB over 045/046, can improve direct probability blends with 040/038/033/045.
- Include 048 as a stronger OVR XGB variant material.
- Include 047 only as a low-priority diagnostic; if 047 receives non-trivial safe-blend weight, consider a later GPU LogReg stacker add047 check.

In [1]:
# ============================================================
# 0. Imports / Config
# ============================================================

import json
import warnings
from pathlib import Path
from itertools import combinations

import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.stats import spearmanr

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import balanced_accuracy_score
from sklearn.linear_model import LogisticRegression, RidgeClassifier, Ridge, ElasticNet

warnings.filterwarnings("ignore")

try:
    import yaml
except Exception:
    yaml = None

COMPETITION = "PS S6E6 Predicting Stellar Class"
EXP_ID = "exp_20260614_050_blend_add047_048_049_check"
SEED = 42

TRAIN_PATH = Path("/kaggle/input/competitions/playground-series-s6e6/train.csv")
TEST_PATH = Path("/kaggle/input/competitions/playground-series-s6e6/test.csv")
SAMPLE_SUB_PATH = Path("/kaggle/input/competitions/playground-series-s6e6/sample_submission.csv")

# Primary location. The loader below also scans /kaggle/input if a file is not found here.
NPY_DIR = Path("/kaggle/input/datasets/mizushimatoshihiko/npy-files")
INPUT_ROOT = Path("/kaggle/input")

OUTDIR = Path("/kaggle/working") / EXP_ID
OUTDIR.mkdir(parents=True, exist_ok=True)

ID_COL = "id"
TARGET_COL = "class"

MODEL_SPECS = [
    {"key": "015_realmlp_seed42", "exp_id": "exp_20260605_015_shared001_realmlp_as_is", "family": "RealMLP", "role": "stable_single_realmlp_backup", "oof": "oof_exp_20260605_015_shared001_realmlp_as_is_proba.npy", "pred": "pred_exp_20260605_015_shared001_realmlp_as_is_proba.npy", "cv": 0.9681693449222352, "public_lb": 0.96977},
    {"key": "017_realmlp_bias", "exp_id": "exp_20260606_017_bias_search_on_015_realmlp", "family": "RealMLP", "role": "previous_best_realmlp_bias_backup", "oof": "oof_exp_20260606_017_bias_search_on_015_realmlp_proba.npy", "pred": "pred_exp_20260606_017_bias_search_on_015_realmlp_proba.npy", "cv": 0.9683022653955233, "public_lb": 0.96985},
    {"key": "018_xgb_shared003", "exp_id": "exp_20260606_018_shared003_xgb_as_is", "family": "XGBoost", "role": "effective_blend_material", "oof": "oof_exp_20260606_018_shared003_xgb_as_is_proba.npy", "pred": "pred_exp_20260606_018_shared003_xgb_as_is_proba.npy", "cv": 0.965207986418628, "public_lb": 0.96578},
    {"key": "019_blend_best", "exp_id": "exp_20260607_019_blend_add018_xgb_check", "family": "Blend", "role": "previous_public_confirmed_best", "oof": "oof_exp_20260607_019_blend_add018_xgb_check_best_blend_proba.npy", "pred": "pred_exp_20260607_019_blend_add018_xgb_check_best_blend_proba.npy", "cv": 0.968872315017554, "public_lb": 0.97000},
    {"key": "020_blend_bias", "exp_id": "exp_20260607_020_bias_search_on_019_best_blend", "family": "Blend", "role": "cv_trusted_attack_reference", "oof": "oof_exp_20260607_020_bias_search_on_019_best_blend_proba.npy", "pred": "pred_exp_20260607_020_bias_search_on_019_best_blend_proba.npy", "cv": 0.9692240443617589, "public_lb": 0.96969},
    {"key": "024_seed_ensemble_blend", "exp_id": "exp_20260608_024_seed_ensemble_and_blend_check", "family": "Blend", "role": "seed_ensemble_blend_reference", "oof": "oof_exp_20260608_024_seed_ensemble_and_blend_check_best_blend_proba.npy", "pred": "pred_exp_20260608_024_seed_ensemble_and_blend_check_best_blend_proba.npy", "cv": 0.9694803109983217, "public_lb": 0.96958},
    {"key": "026_realmlp_v5", "exp_id": "exp_20260608_026_realmlp_v5_as_is", "family": "RealMLP", "role": "realmlp_v5_single_model_candidate", "oof": "oof_exp_20260608_026_realmlp_v5_as_is_proba.npy", "pred": "pred_exp_20260608_026_realmlp_v5_as_is_proba.npy", "cv": 0.9690389777981231, "public_lb": 0.96979},
    {"key": "027_blend_add026", "exp_id": "exp_20260608_027_blend_add026_realmlp_v5_check", "family": "Blend", "role": "previous_cv_trusted_slot", "oof": "oof_exp_20260608_027_blend_add026_realmlp_v5_check_best_blend_proba.npy", "pred": "pred_exp_20260608_027_blend_add026_realmlp_v5_check_best_blend_proba.npy", "cv": 0.9695425457477898, "public_lb": 0.96975},
    {"key": "028_cat_v3", "exp_id": "exp_20260608_028_cat_v3_as_is", "family": "CatBoost", "role": "catboost_v3_family_aux_material", "oof": "oof_exp_20260608_028_cat_v3_as_is_proba.npy", "pred": "pred_exp_20260608_028_cat_v3_as_is_proba.npy", "cv": 0.9688146470512534, "public_lb": 0.96969},
    {"key": "029_blend_add028", "exp_id": "exp_20260608_029_blend_add028_cat_v3_check", "family": "Blend", "role": "previous_best_backup", "oof": "oof_exp_20260608_029_blend_add028_cat_v3_check_best_blend_proba.npy", "pred": "pred_exp_20260608_029_blend_add028_cat_v3_check_best_blend_proba.npy", "cv": 0.9700023026377228, "public_lb": 0.970036},
    {"key": "030_ovr_xgb", "exp_id": "exp_20260608_030_ovr_xgb_as_is", "family": "XGBoost", "role": "low_weight_auxiliary_xgb_ovr_material", "oof": "oof_exp_20260608_030_ovr_xgb_as_is_proba.npy", "pred": "pred_exp_20260608_030_ovr_xgb_as_is_proba.npy", "cv": 0.9609971296999271, "public_lb": 0.96118},
    {"key": "031_blend_add030", "exp_id": "exp_20260608_031_blend_add030_ovr_xgb_check", "family": "Blend", "role": "public_confirmed_current_best_before_033", "oof": "oof_exp_20260608_031_blend_add030_ovr_xgb_check_best_blend_proba.npy", "pred": "pred_exp_20260608_031_blend_add030_ovr_xgb_check_best_blend_proba.npy", "cv": 0.9700333620193362, "public_lb": 0.97043},
    {"key": "032_ovr_tabm", "exp_id": "exp_20260609_032_ovr_tabm_as_is", "family": "TabM", "role": "tabm_ovr_family_aux_material", "oof": "oof_exp_20260609_032_ovr_tabm_as_is_proba.npy", "pred": "pred_exp_20260609_032_ovr_tabm_as_is_proba.npy", "cv": 0.9610105651284856, "public_lb": 0.96106, "tuned_cv": 0.9686168281485955, "public_lb_biased": 0.96895},
    {"key": "033_blend_add032", "exp_id": "exp_20260609_033_blend_add032_tabm_check", "family": "Blend", "role": "previous_public_confirmed_best_backup", "oof": "oof_exp_20260609_033_blend_add032_tabm_check_best_blend_proba.npy", "pred": "pred_exp_20260609_033_blend_add032_tabm_check_best_blend_proba.npy", "cv": 0.9700400336552478, "public_lb": 0.97043},
    {"key": "034_gpu_logreg_default", "exp_id": "exp_20260609_034_gpu_logreg_stacker_own", "family": "GPU_LogisticRegression_Stacker", "role": "stacker_backup_default", "oof": "oof_exp_20260609_034_gpu_logreg_stacker_own_proba.npy", "pred": "pred_exp_20260609_034_gpu_logreg_stacker_own_proba.npy", "cv": 0.9700373069292101, "public_lb": 0.97022, "raw_cv": 0.9699389938897909, "public_lb_raw": 0.97027},
    {"key": "035_shared001_updated", "exp_id": "exp_20260610_035_shared001_updated_realmlp_pytorch_as_is", "family": "RealMLP", "role": "updated_shared001_realmlp_aux_material", "oof": "oof_exp_20260610_035_shared001_updated_realmlp_pytorch_as_is_proba.npy", "pred": "pred_exp_20260610_035_shared001_updated_realmlp_pytorch_as_is_proba.npy", "cv": 0.9687410900866934, "public_lb": 0.97012},
    {"key": "036_gpu_logreg_add035", "exp_id": "exp_20260610_036_gpu_logreg_stacker_add035_own", "family": "GPU_LogisticRegression_Stacker", "role": "improved_stacker_backup_add035", "oof": "oof_exp_20260610_036_gpu_logreg_stacker_add035_own_proba.npy", "pred": "pred_exp_20260610_036_gpu_logreg_stacker_add035_own_proba.npy", "cv": 0.9700674063284508, "public_lb": 0.97037},
    {"key": "036_blend_add035", "exp_id": "exp_20260610_036_blend_add035_shared001_check", "family": "Blend", "role": "cv_best_but_public_weak_add035_blend", "oof": "oof_exp_20260610_036_blend_add035_shared001_check_best_blend_proba.npy", "pred": "pred_exp_20260610_036_blend_add035_shared001_check_best_blend_proba.npy", "cv": 0.9700727843277738, "public_lb": 0.97023},
    {"key": "037_tabicl_v2", "exp_id": "exp_20260610_037_tabicl_v2_as_is", "family": "TabICL", "role": "weak_tabicl_family_material_optional_corr", "oof": "oof_exp_20260610_037_tabicl_v2_as_is_proba.npy", "pred": "pred_exp_20260610_037_tabicl_v2_as_is_proba.npy", "cv": 0.9580770153777599, "public_lb": 0.95920},
    {"key": "038_gpu_logreg_add037", "exp_id": "exp_20260610_038_gpu_logreg_stacker_add037_own", "family": "GPU_LogisticRegression_Stacker", "role": "previous_stacker_best_before_040", "oof": "oof_exp_20260610_038_gpu_logreg_stacker_add037_own_proba.npy", "pred": "pred_exp_20260610_038_gpu_logreg_stacker_add037_own_proba.npy", "cv": 0.9701353365798572, "public_lb": 0.97060},
    {"key": "039_cat_v3_seed2026_qbin_variant", "exp_id": "exp_20260611_039_cat_v3_seed2026_qbin_variant", "family": "CatBoost", "role": "catboost_v3_lower_correlation_variant_material", "oof": "oof_exp_20260611_039_cat_v3_seed2026_qbin_variant_proba.npy", "pred": "pred_exp_20260611_039_cat_v3_seed2026_qbin_variant_proba.npy", "cv": 0.9687053023092482, "public_lb": 0.96984},
    {"key": "040_gpu_logreg_add039", "exp_id": "exp_20260611_040_gpu_logreg_stacker_add039_own", "family": "GPU_LogisticRegression_Stacker", "role": "current_best_after_add039", "oof": "oof_exp_20260611_040_gpu_logreg_stacker_add039_own_proba.npy", "pred": "pred_exp_20260611_040_gpu_logreg_stacker_add039_own_proba.npy", "cv": 0.9702017877238539, "public_lb": 0.97069},
    {"key": "042_realmlp_v5_seed2026_foldvariant", "exp_id": "exp_20260611_042_realmlp_v5_seed2026_foldvariant", "family": "RealMLP", "role": "realmlp_v5_seed_fold_variant_material", "oof": "oof_exp_20260611_042_realmlp_v5_seed2026_foldvariant_proba.npy", "pred": "pred_exp_20260611_042_realmlp_v5_seed2026_foldvariant_proba.npy", "cv": 0.9689482884928097, "public_lb": 0.96943},
    {"key": "044_shared001_updated_seed2027_foldvariant", "exp_id": "exp_20260612_044_shared001_updated_seed2027_foldvariant", "family": "RealMLP", "role": "shared001_updated_seed_fold_variant_material", "oof": "oof_exp_20260612_044_shared001_updated_seed2027_foldvariant_proba.npy", "pred": "pred_exp_20260612_044_shared001_updated_seed2027_foldvariant_proba.npy", "cv": 0.9686035095582338, "public_lb": 0.97000},
    {"key": "045_gpu_logreg_add044", "exp_id": "exp_20260612_045_gpu_logreg_stacker_add044_own", "family": "GPU_LogisticRegression_Stacker", "role": "cv_best_but_public_weak_stacker_add044", "oof": "oof_exp_20260612_045_gpu_logreg_stacker_add044_own_proba.npy", "pred": "pred_exp_20260612_045_gpu_logreg_stacker_add044_own_proba.npy", "cv": 0.9702445493383917, "public_lb": 0.97040, "raw_cv": 0.9701651297689362, "tuned_cv": 0.9702445493383917},
    {"key": "047_xgb_multiclass_fe_objective_foldvariant", "exp_id": "exp_20260614_047_xgb_multiclass_fe_objective_foldvariant", "family": "XGBoost", "role": "failed_multiclass_xgb_variant_low_priority_diagnostic", "oof": "oof_exp_20260614_047_xgb_multiclass_fe_objective_foldvariant_proba.npy", "pred": "pred_exp_20260614_047_xgb_multiclass_fe_objective_foldvariant_proba.npy", "cv": 0.9596874103404002, "public_lb": 0.96027},
    {"key": "048_ovr_xgb_seed2027_fe_foldvariant", "exp_id": "exp_20260614_048_ovr_xgb_seed2027_fe_foldvariant", "family": "XGBoost", "role": "improved_xgb_ovr_variant_material", "oof": "oof_exp_20260614_048_ovr_xgb_seed2027_fe_foldvariant_proba.npy", "pred": "pred_exp_20260614_048_ovr_xgb_seed2027_fe_foldvariant_proba.npy", "cv": 0.9636973807714805, "public_lb": 0.96444},
    {"key": "049_gpu_logreg_add048", "exp_id": "exp_20260614_049_gpu_logreg_stacker_add048_own", "family": "GPU_LogisticRegression_Stacker", "role": "add048_stacker_public_improved_diagnostic", "oof": "oof_exp_20260614_049_gpu_logreg_stacker_add048_own_proba.npy", "pred": "pred_exp_20260614_049_gpu_logreg_stacker_add048_own_proba.npy", "cv": 0.9701958734042008, "public_lb": 0.97046, "raw_cv": 0.97011955078962, "tuned_cv": 0.9701958734042008},
]

TRACK_KEYS = {
    "049": "049_gpu_logreg_add048",
    "048": "048_ovr_xgb_seed2027_fe_foldvariant",
    "047": "047_xgb_multiclass_fe_objective_foldvariant",
    "045": "045_gpu_logreg_add044",
    "044": "044_shared001_updated_seed2027_foldvariant",
    "042": "042_realmlp_v5_seed2026_foldvariant",
    "040": "040_gpu_logreg_add039",
    "039": "039_cat_v3_seed2026_qbin_variant",
    "038": "038_gpu_logreg_add037",
    "037": "037_tabicl_v2",
    "036_gpu": "036_gpu_logreg_add035",
    "036_blend": "036_blend_add035",
    "035": "035_shared001_updated",
    "034": "034_gpu_logreg_default",
    "033": "033_blend_add032",
    "032": "032_ovr_tabm",
    "031": "031_blend_add030",
    "030": "030_ovr_xgb",
    "029": "029_blend_add028",
    "028": "028_cat_v3",
}

FOCUS_MODEL_KEYS = {
    "049": "049_gpu_logreg_add048",
    "048": "048_ovr_xgb_seed2027_fe_foldvariant",
    "047": "047_xgb_multiclass_fe_objective_foldvariant",
    "045": "045_gpu_logreg_add044",
    "040": "040_gpu_logreg_add039",
    "038": "038_gpu_logreg_add037",
    "033": "033_blend_add032",
    "031": "031_blend_add030",
    "030": "030_ovr_xgb",
    "044": "044_shared001_updated_seed2027_foldvariant",
    "042": "042_realmlp_v5_seed2026_foldvariant",
}

# 050 should answer:
# - Does 049 improve direct probability blending with 040/038/033/045?
# - Does 048 have direct probability-blend value beyond its use inside 049?
# - Does the weak 047 receive non-trivial safe-blend weight? If yes, consider a later GPU LogReg stacker add047 diagnostic.
# - Keep interpretation conservative: 047/048 are weak standalone models; useful only if safe-blend weights and Public LB confirm.
BLEND_SETS = {
    # Singles / current references
    "A_049_only": ["049_gpu_logreg_add048"],
    "B_045_only": ["045_gpu_logreg_add044"],
    "C_040_only": ["040_gpu_logreg_add039"],
    "D_038_only": ["038_gpu_logreg_add037"],
    "E_033_only": ["033_blend_add032"],
    "F_048_only": ["048_ovr_xgb_seed2027_fe_foldvariant"],
    "G_047_only": ["047_xgb_multiclass_fe_objective_foldvariant"],
    "H_044_only": ["044_shared001_updated_seed2027_foldvariant"],
    "I_042_only": ["042_realmlp_v5_seed2026_foldvariant"],
    "J_039_only": ["039_cat_v3_seed2026_qbin_variant"],
    "K_036_gpu_only": ["036_gpu_logreg_add035"],
    "L_036_blend_only": ["036_blend_add035"],
    "M_031_only": ["031_blend_add030"],

    # Main 049 checks.
    "N_049_040": ["049_gpu_logreg_add048", "040_gpu_logreg_add039"],
    "O_049_038": ["049_gpu_logreg_add048", "038_gpu_logreg_add037"],
    "P_049_033": ["049_gpu_logreg_add048", "033_blend_add032"],
    "Q_049_045": ["049_gpu_logreg_add048", "045_gpu_logreg_add044"],
    "R_049_040_038": ["049_gpu_logreg_add048", "040_gpu_logreg_add039", "038_gpu_logreg_add037"],
    "S_049_040_033": ["049_gpu_logreg_add048", "040_gpu_logreg_add039", "033_blend_add032"],
    "T_049_038_033": ["049_gpu_logreg_add048", "038_gpu_logreg_add037", "033_blend_add032"],
    "U_049_045_040": ["049_gpu_logreg_add048", "045_gpu_logreg_add044", "040_gpu_logreg_add039"],
    "V_049_045_038": ["049_gpu_logreg_add048", "045_gpu_logreg_add044", "038_gpu_logreg_add037"],
    "W_049_045_040_038": ["049_gpu_logreg_add048", "045_gpu_logreg_add044", "040_gpu_logreg_add039", "038_gpu_logreg_add037"],
    "X_049_045_040_038_033": ["049_gpu_logreg_add048", "045_gpu_logreg_add044", "040_gpu_logreg_add039", "038_gpu_logreg_add037", "033_blend_add032"],

    # 048 direct checks. 048 is better than 030/047 but still weak; expect low direct weight unless it provides useful diversity.
    "Y_048_040": ["048_ovr_xgb_seed2027_fe_foldvariant", "040_gpu_logreg_add039"],
    "Z01_048_038": ["048_ovr_xgb_seed2027_fe_foldvariant", "038_gpu_logreg_add037"],
    "Z02_048_033": ["048_ovr_xgb_seed2027_fe_foldvariant", "033_blend_add032"],
    "Z03_048_045": ["048_ovr_xgb_seed2027_fe_foldvariant", "045_gpu_logreg_add044"],
    "Z04_048_049": ["048_ovr_xgb_seed2027_fe_foldvariant", "049_gpu_logreg_add048"],
    "Z05_048_049_040_038": ["048_ovr_xgb_seed2027_fe_foldvariant", "049_gpu_logreg_add048", "040_gpu_logreg_add039", "038_gpu_logreg_add037"],
    "Z06_048_049_045_040_038_033": ["048_ovr_xgb_seed2027_fe_foldvariant", "049_gpu_logreg_add048", "045_gpu_logreg_add044", "040_gpu_logreg_add039", "038_gpu_logreg_add037", "033_blend_add032"],

    # 047 diagnostic checks. If 047 receives meaningful safe-blend weight, consider GPU LogReg stacker add047 next.
    "Z07_047_040": ["047_xgb_multiclass_fe_objective_foldvariant", "040_gpu_logreg_add039"],
    "Z08_047_038": ["047_xgb_multiclass_fe_objective_foldvariant", "038_gpu_logreg_add037"],
    "Z09_047_033": ["047_xgb_multiclass_fe_objective_foldvariant", "033_blend_add032"],
    "Z10_047_045": ["047_xgb_multiclass_fe_objective_foldvariant", "045_gpu_logreg_add044"],
    "Z11_047_049": ["047_xgb_multiclass_fe_objective_foldvariant", "049_gpu_logreg_add048"],
    "Z12_047_048_049": ["047_xgb_multiclass_fe_objective_foldvariant", "048_ovr_xgb_seed2027_fe_foldvariant", "049_gpu_logreg_add048"],
    "Z13_047_048_049_040_038": ["047_xgb_multiclass_fe_objective_foldvariant", "048_ovr_xgb_seed2027_fe_foldvariant", "049_gpu_logreg_add048", "040_gpu_logreg_add039", "038_gpu_logreg_add037"],
    "Z14_047_048_049_045_040_038_033": ["047_xgb_multiclass_fe_objective_foldvariant", "048_ovr_xgb_seed2027_fe_foldvariant", "049_gpu_logreg_add048", "045_gpu_logreg_add044", "040_gpu_logreg_add039", "038_gpu_logreg_add037", "033_blend_add032"],

    # Existing 046-style core sets for backward comparison.
    "Z15_045_040_038": ["045_gpu_logreg_add044", "040_gpu_logreg_add039", "038_gpu_logreg_add037"],
    "Z16_045_040_033_038": ["045_gpu_logreg_add044", "040_gpu_logreg_add039", "033_blend_add032", "038_gpu_logreg_add037"],
    "Z17_045_040_033_038_044_042": ["045_gpu_logreg_add044", "040_gpu_logreg_add039", "033_blend_add032", "038_gpu_logreg_add037", "044_shared001_updated_seed2027_foldvariant", "042_realmlp_v5_seed2026_foldvariant"],
    "Z18_041_old_best_like_plus_new049": ["040_gpu_logreg_add039", "033_blend_add032", "038_gpu_logreg_add037", "036_gpu_logreg_add035", "036_blend_add035", "039_cat_v3_seed2026_qbin_variant", "037_tabicl_v2", "044_shared001_updated_seed2027_foldvariant", "042_realmlp_v5_seed2026_foldvariant", "045_gpu_logreg_add044", "049_gpu_logreg_add048"],
    "Z19_040_033_038_036gpu_036blend_039_044_042_048_049": ["040_gpu_logreg_add039", "033_blend_add032", "038_gpu_logreg_add037", "036_gpu_logreg_add035", "036_blend_add035", "039_cat_v3_seed2026_qbin_variant", "044_shared001_updated_seed2027_foldvariant", "042_realmlp_v5_seed2026_foldvariant", "048_ovr_xgb_seed2027_fe_foldvariant", "049_gpu_logreg_add048"],

    # Component diagnostics. Interpret weights carefully because composite blends and components coexist.
    "Z20_component_diagnostics_xgb_and_core": ["027_blend_add026", "026_realmlp_v5", "028_cat_v3", "039_cat_v3_seed2026_qbin_variant", "030_ovr_xgb", "032_ovr_tabm", "035_shared001_updated", "037_tabicl_v2", "047_xgb_multiclass_fe_objective_foldvariant", "048_ovr_xgb_seed2027_fe_foldvariant", "049_gpu_logreg_add048"],
    "Z21_full_all_loaded": [
        "015_realmlp_seed42", "017_realmlp_bias", "018_xgb_shared003",
        "019_blend_best", "020_blend_bias", "024_seed_ensemble_blend",
        "026_realmlp_v5", "027_blend_add026", "028_cat_v3",
        "029_blend_add028", "030_ovr_xgb", "031_blend_add030",
        "032_ovr_tabm", "033_blend_add032", "034_gpu_logreg_default",
        "035_shared001_updated", "036_gpu_logreg_add035", "036_blend_add035",
        "037_tabicl_v2", "038_gpu_logreg_add037", "039_cat_v3_seed2026_qbin_variant",
        "040_gpu_logreg_add039", "042_realmlp_v5_seed2026_foldvariant",
        "044_shared001_updated_seed2027_foldvariant", "045_gpu_logreg_add044",
        "047_xgb_multiclass_fe_objective_foldvariant", "048_ovr_xgb_seed2027_fe_foldvariant", "049_gpu_logreg_add048",
    ],
}

print("EXP_ID:", EXP_ID)
print("OUTDIR:", OUTDIR)
print("NPY_DIR:", NPY_DIR)
print("n_models:", len(MODEL_SPECS))
print("n_blend_sets:", len(BLEND_SETS))

EXP_ID: exp_20260614_050_blend_add047_048_049_check
OUTDIR: /kaggle/working/exp_20260614_050_blend_add047_048_049_check
NPY_DIR: /kaggle/input/datasets/mizushimatoshihiko/npy-files
n_models: 28
n_blend_sets: 46

In [2]:
# ============================================================
# 1. Utilities
# ============================================================

def save_json(obj, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False, default=str)

def resolve_npy(filename):
    """Resolve an npy path. Prefer NPY_DIR, then scan /kaggle/input.

    This is intentionally more robust than 027 because 028 may be uploaded as a
    separate dataset from older npy files.
    """
    p = NPY_DIR / filename
    if p.exists():
        return p
    matches = list(INPUT_ROOT.rglob(filename)) if INPUT_ROOT.exists() else []
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        print(f"[WARN] multiple matches for {filename}. Using first:")
        for m in matches[:10]:
            print("  ", m)
        return matches[0]
    raise FileNotFoundError(f"Missing npy file: {filename}. Checked {NPY_DIR} and scanned {INPUT_ROOT}.")

def validate_proba(name, arr, n_rows, n_classes):
    assert arr.shape == (n_rows, n_classes), (name, arr.shape)
    assert np.isfinite(arr).all(), name
    assert np.allclose(arr.sum(axis=1), 1.0, atol=1e-4), name
    assert arr.min() >= -1e-7, (name, arr.min())
    assert arr.max() <= 1.0 + 1e-7, (name, arr.max())

def normalize_rows(p, eps=1e-12):
    p = np.asarray(p, dtype=np.float64)
    p = np.clip(p, eps, None)
    return p / p.sum(axis=1, keepdims=True)

def softmax_np(x, axis=1):
    x = np.asarray(x, dtype=np.float64)
    x = x - np.max(x, axis=axis, keepdims=True)
    ex = np.exp(x)
    return ex / np.sum(ex, axis=axis, keepdims=True)

def proba_to_pred(p):
    return np.argmax(p, axis=1)

def flatten_proba(p):
    return np.asarray(p, dtype=float).reshape(-1)

def corr_pearson(a, b):
    a, b = flatten_proba(a), flatten_proba(b)
    if np.std(a) == 0 or np.std(b) == 0:
        return float("nan")
    return float(np.corrcoef(a, b)[0, 1])

def corr_spearman(a, b):
    a, b = flatten_proba(a), flatten_proba(b)
    if np.std(a) == 0 or np.std(b) == 0:
        return float("nan")
    return float(spearmanr(a, b).correlation)

def class_recalls(y_true, y_pred, class_names):
    out = {}
    for i, cls in enumerate(class_names):
        m = y_true == i
        out[f"recall_{cls}"] = float((y_pred[m] == i).mean()) if m.any() else float("nan")
    return out

def evaluate_proba(y_true, p, class_names):
    pred = proba_to_pred(p)
    res = {"balanced_accuracy": float(balanced_accuracy_score(y_true, pred))}
    res.update(class_recalls(y_true, pred, class_names))
    return res

def rank_normalize_matrix(p):
    out = np.zeros_like(p, dtype=np.float64)
    n = p.shape[0]
    for j in range(p.shape[1]):
        r = pd.Series(p[:, j]).rank(method="average").to_numpy()
        out[:, j] = (r - 1) / max(n - 1, 1)
    return normalize_rows(out)

def logit_transform(p, eps=1e-15):
    p = np.clip(p, eps, 1.0 - eps)
    return np.log(p / (1.0 - p))

def build_meta_features(keys, proba_dict, mode):
    mats = []
    for k in keys:
        p = proba_dict[k]
        if mode == "raw":
            mats.append(p)
        elif mode == "rank":
            mats.append(rank_normalize_matrix(p))
        elif mode == "logit":
            mats.append(logit_transform(p))
        elif mode == "raw_logit":
            mats += [p, logit_transform(p)]
        elif mode == "raw_rank_logit":
            mats += [p, rank_normalize_matrix(p), logit_transform(p)]
        else:
            raise ValueError(mode)
    return np.concatenate(mats, axis=1)

def average_proba(keys, oof_dict, pred_dict=None):
    oof_avg = normalize_rows(np.mean([oof_dict[k] for k in keys], axis=0))
    pred_avg = None
    if pred_dict is not None:
        pred_avg = normalize_rows(np.mean([pred_dict[k] for k in keys], axis=0))
    return oof_avg, pred_avg

def onehot_y(y, n_classes):
    out = np.zeros((len(y), n_classes), dtype=np.float64)
    out[np.arange(len(y)), y] = 1.0
    return out

def hill_climb_weights(y_true, probas, steps=(0.1, 0.05, 0.02, 0.01, 0.005, 0.002), max_iter=300):
    n = len(probas)
    w = np.ones(n, dtype=float) / n
    cur_score = balanced_accuracy_score(y_true, normalize_rows(sum(w[i] * probas[i] for i in range(n))).argmax(axis=1))
    hist = [{"iter": 0, "score": float(cur_score), "weights": w.copy().tolist()}]
    for step in steps:
        improved = True
        it = 0
        while improved and it < max_iter:
            improved = False
            it += 1
            best_score, best_w = cur_score, w.copy()
            for i in range(n):
                for direction in [-1, 1]:
                    cand_w = w.copy()
                    cand_w[i] += direction * step
                    cand_w = np.clip(cand_w, 0.0, None)
                    if cand_w.sum() <= 0:
                        continue
                    cand_w /= cand_w.sum()
                    cand = normalize_rows(sum(cand_w[j] * probas[j] for j in range(n)))
                    score = balanced_accuracy_score(y_true, cand.argmax(axis=1))
                    if score > best_score + 1e-15:
                        best_score, best_w = score, cand_w.copy()
            if best_score > cur_score + 1e-15:
                cur_score, w = best_score, best_w
                improved = True
                hist.append({"iter": len(hist), "step": step, "score": float(cur_score), "weights": w.copy().tolist()})
    return w, float(cur_score), hist

def nm_softmax_weights(y_true, probas, n_restarts=5, maxiter=2500):
    probas = [np.asarray(p, dtype=np.float64) for p in probas]
    n = len(probas)

    def eval_from_theta(theta):
        w = np.exp(theta - np.max(theta))
        w = w / w.sum()
        p = normalize_rows(sum(w[i] * probas[i] for i in range(n)))
        return balanced_accuracy_score(y_true, p.argmax(axis=1)), w

    def objective(theta):
        score, _ = eval_from_theta(theta)
        return -score

    inits = [np.zeros(n)]
    rng = np.random.default_rng(SEED)
    for _ in range(n_restarts - 1):
        inits.append(rng.normal(0, 0.25, size=n))

    best_score, best_w, best_res = -1, None, None
    for init in inits:
        res = minimize(objective, init, method="Nelder-Mead", options={"maxiter": maxiter, "xatol": 1e-8, "fatol": 1e-12})
        score, w = eval_from_theta(res.x)
        if score > best_score:
            best_score, best_w, best_res = score, w, res
    return best_w, float(best_score), best_res

def disagreement_and_error_overlap(y_true, p1, p2):
    pred1 = p1.argmax(axis=1)
    pred2 = p2.argmax(axis=1)
    wrong1 = pred1 != y_true
    wrong2 = pred2 != y_true
    both_wrong = wrong1 & wrong2
    either_wrong = wrong1 | wrong2
    return {
        "disagreement_rate": float((pred1 != pred2).mean()),
        "wrong_rate_left": float(wrong1.mean()),
        "wrong_rate_right": float(wrong2.mean()),
        "both_wrong_rate": float(both_wrong.mean()),
        "error_overlap_jaccard": float(both_wrong.sum() / max(either_wrong.sum(), 1)),
        "left_wrong_right_correct_rate": float((wrong1 & ~wrong2).mean()),
        "right_wrong_left_correct_rate": float((wrong2 & ~wrong1).mean()),
    }

In [3]:
# ============================================================
# 2. Load data and OOF/pred
# ============================================================

for p in [TRAIN_PATH, TEST_PATH, SAMPLE_SUB_PATH]:
    if not p.exists():
        raise FileNotFoundError(p)

train = pd.read_csv(TRAIN_PATH)
test = pd.read_csv(TEST_PATH)
sample = pd.read_csv(SAMPLE_SUB_PATH)

le = LabelEncoder()
y = le.fit_transform(train[TARGET_COL].astype(str))
class_names = le.classes_.tolist()
n_classes = len(class_names)
assert class_names == ["GALAXY", "QSO", "STAR"], class_names

oof, pred, resolved_specs = {}, {}, []
for spec in MODEL_SPECS:
    key = spec["key"]
    oof_path = resolve_npy(spec["oof"])
    pred_path = resolve_npy(spec["pred"])
    oof_arr = np.load(oof_path)
    pred_arr = np.load(pred_path)
    validate_proba(f"oof:{key}", oof_arr, len(train), n_classes)
    validate_proba(f"pred:{key}", pred_arr, len(test), n_classes)
    oof[key] = oof_arr.astype(np.float64)
    pred[key] = pred_arr.astype(np.float64)
    s = spec.copy()
    s["resolved_oof_path"] = str(oof_path)
    s["resolved_pred_path"] = str(pred_path)
    resolved_specs.append(s)
    print(f"loaded {key}: {oof_arr.shape} / {pred_arr.shape}")

model_keys = [s["key"] for s in resolved_specs]
print("class_names:", class_names)
print("loaded keys:", model_keys)

loaded 015_realmlp_seed42: (577347, 3) / (247435, 3)
loaded 017_realmlp_bias: (577347, 3) / (247435, 3)
loaded 018_xgb_shared003: (577347, 3) / (247435, 3)
loaded 019_blend_best: (577347, 3) / (247435, 3)
loaded 020_blend_bias: (577347, 3) / (247435, 3)
loaded 024_seed_ensemble_blend: (577347, 3) / (247435, 3)
loaded 026_realmlp_v5: (577347, 3) / (247435, 3)
loaded 027_blend_add026: (577347, 3) / (247435, 3)
loaded 028_cat_v3: (577347, 3) / (247435, 3)
loaded 029_blend_add028: (577347, 3) / (247435, 3)
loaded 030_ovr_xgb: (577347, 3) / (247435, 3)
loaded 031_blend_add030: (577347, 3) / (247435, 3)
loaded 032_ovr_tabm: (577347, 3) / (247435, 3)
loaded 033_blend_add032: (577347, 3) / (247435, 3)
loaded 034_gpu_logreg_default: (577347, 3) / (247435, 3)
loaded 035_shared001_updated: (577347, 3) / (247435, 3)
loaded 036_gpu_logreg_add035: (577347, 3) / (247435, 3)
loaded 036_blend_add035: (577347, 3) / (247435, 3)
loaded 037_tabicl_v2: (577347, 3) / (247435, 3)
loaded 038_gpu_logreg_add037: (577347, 3) / (247435, 3)
loaded 039_cat_v3_seed2026_qbin_variant: (577347, 3) / (247435, 3)
loaded 040_gpu_logreg_add039: (577347, 3) / (247435, 3)
loaded 042_realmlp_v5_seed2026_foldvariant: (577347, 3) / (247435, 3)
loaded 044_shared001_updated_seed2027_foldvariant: (577347, 3) / (247435, 3)
loaded 045_gpu_logreg_add044: (577347, 3) / (247435, 3)
loaded 047_xgb_multiclass_fe_objective_foldvariant: (577347, 3) / (247435, 3)
loaded 048_ovr_xgb_seed2027_fe_foldvariant: (577347, 3) / (247435, 3)
loaded 049_gpu_logreg_add048: (577347, 3) / (247435, 3)
class_names: ['GALAXY', 'QSO', 'STAR']
loaded keys: ['015_realmlp_seed42', '017_realmlp_bias', '018_xgb_shared003', '019_blend_best', '020_blend_bias', '024_seed_ensemble_blend', '026_realmlp_v5', '027_blend_add026', '028_cat_v3', '029_blend_add028', '030_ovr_xgb', '031_blend_add030', '032_ovr_tabm', '033_blend_add032', '034_gpu_logreg_default', '035_shared001_updated', '036_gpu_logreg_add035', '036_blend_add035', '037_tabicl_v2', '038_gpu_logreg_add037', '039_cat_v3_seed2026_qbin_variant', '040_gpu_logreg_add039', '042_realmlp_v5_seed2026_foldvariant', '044_shared001_updated_seed2027_foldvariant', '045_gpu_logreg_add044', '047_xgb_multiclass_fe_objective_foldvariant', '048_ovr_xgb_seed2027_fe_foldvariant', '049_gpu_logreg_add048']

In [4]:
# ============================================================
# 3. Individual scores and pairwise diagnostics
# ============================================================

rows = []
for spec in resolved_specs:
    key = spec["key"]
    p = oof[key]
    y_pred = proba_to_pred(p)
    score = balanced_accuracy_score(y, y_pred)
    row = {
        "key": key,
        "exp_id": spec["exp_id"],
        "family": spec["family"],
        "role": spec["role"],
        "cv_from_memo": spec.get("cv", np.nan),
        "public_lb": spec.get("public_lb", np.nan),
        "public_lb_biased": spec.get("public_lb_biased", np.nan),
        "tuned_cv": spec.get("tuned_cv", np.nan),
        "recomputed_oof_cv": float(score),
        "delta_recomputed_minus_memo": float(score - spec.get("cv", score)),
    }
    row.update(class_recalls(y, y_pred, class_names))
    rows.append(row)

individual_df = pd.DataFrame(rows).sort_values("recomputed_oof_cv", ascending=False).reset_index(drop=True)
display(individual_df)
individual_df.to_csv(OUTDIR / "individual_scores.csv", index=False)

pair_rows = []
for a, b in combinations(model_keys, 2):
    diag = disagreement_and_error_overlap(y, oof[a], oof[b])
    pair_rows.append({
        "left": a,
        "right": b,
        "pearson_flat_proba": corr_pearson(oof[a], oof[b]),
        "spearman_flat_proba": corr_spearman(oof[a], oof[b]),
        **diag,
    })

pairwise_df = pd.DataFrame(pair_rows)
pairwise_df = pairwise_df.sort_values(["pearson_flat_proba", "error_overlap_jaccard"], ascending=[True, True]).reset_index(drop=True)
display(pairwise_df)
pairwise_df.to_csv(OUTDIR / "pairwise_oof_correlation.csv", index=False)

# Focus tables for newly added / current reference models.
def focus_pairwise(key, filename):
    df = pairwise_df[(pairwise_df["left"] == key) | (pairwise_df["right"] == key)].copy()
    df = df.sort_values("pearson_flat_proba").reset_index(drop=True)
    display(df)
    df.to_csv(OUTDIR / filename, index=False)
    return df

focus_pairwise_tables = {}
for short_name, key in FOCUS_MODEL_KEYS.items():
    if key in model_keys:
        focus_pairwise_tables[short_name] = focus_pairwise(key, f"pairwise_oof_correlation_focus_{short_name}.csv")

# Backward-compatible variables for easy notebook inspection.
focus_040_df = focus_pairwise_tables.get("040", pd.DataFrame())
focus_039_df = focus_pairwise_tables.get("039", pd.DataFrame())
focus_038_df = focus_pairwise_tables.get("038", pd.DataFrame())
focus_037_df = focus_pairwise_tables.get("037", pd.DataFrame())
focus_033_df = focus_pairwise_tables.get("033", pd.DataFrame())

,key,exp_id,family,role,cv_from_memo,public_lb,public_lb_biased,tuned_cv,recomputed_oof_cv,delta_recomputed_minus_memo,recall_GALAXY,recall_QSO,recall_STAR
0,045_gpu_logreg_add044,exp_20260612_045_gpu_logreg_stacker_add044_own,GPU_LogisticRegression_Stacker,cv_best_but_public_weak_stacker_add044,0.970245,0.970400,NaN,0.970245,0.970245,0.0,0.960096,0.977148,0.973490
1,040_gpu_logreg_add039,exp_20260611_040_gpu_logreg_stacker_add039_own,GPU_LogisticRegression_Stacker,current_best_after_add039,0.970202,0.970690,NaN,NaN,0.970202,0.0,0.959500,0.976866,0.974240
2,049_gpu_logreg_add048,exp_20260614_049_gpu_logreg_stacker_add048_own,GPU_LogisticRegression_Stacker,add048_stacker_public_improved_diagnostic,0.970196,0.970460,NaN,0.970196,0.970196,0.0,0.960273,0.977199,0.973115
3,038_gpu_logreg_add037,exp_20260610_038_gpu_logreg_stacker_add037_own,GPU_LogisticRegression_Stacker,previous_stacker_best_before_040,0.970135,0.970600,NaN,NaN,0.970135,0.0,0.958120,0.977950,0.974336
4,036_blend_add035,exp_20260610_036_blend_add035_shared001_check,Blend,cv_best_but_public_weak_add035_blend,0.970073,0.970230,NaN,NaN,0.970073,0.0,0.960777,0.976943,0.972499
5,036_gpu_logreg_add035,exp_20260610_036_gpu_logreg_stacker_add035_own,GPU_LogisticRegression_Stacker,improved_stacker_backup_add035,0.970067,0.970370,NaN,NaN,0.970067,0.0,0.958313,0.978701,0.973188
6,033_blend_add032,exp_20260609_033_blend_add032_tabm_check,Blend,previous_public_confirmed_best_backup,0.970040,0.970430,NaN,NaN,0.970040,0.0,0.961775,0.975773,0.972571
7,034_gpu_logreg_default,exp_20260609_034_gpu_logreg_stacker_own,GPU_LogisticRegression_Stacker,stacker_backup_default,0.970037,0.970220,NaN,NaN,0.970037,0.0,0.959794,0.977771,0.972547
8,031_blend_add030,exp_20260608_031_blend_add030_ovr_xgb_check,Blend,public_confirmed_current_best_before_033,0.970033,0.970430,NaN,NaN,0.970033,0.0,0.961738,0.975790,0.972571
9,029_blend_add028,exp_20260608_029_blend_add028_cat_v3_check,Blend,previous_best_backup,0.970002,0.970036,NaN,NaN,0.970002,0.0,0.961315,0.975867,0.972825
10,027_blend_add026,exp_20260608_027_blend_add026_realmlp_v5_check,Blend,previous_cv_trusted_slot,0.969543,0.969750,NaN,NaN,0.969543,0.0,0.961479,0.976439,0.970710
11,024_seed_ensemble_blend,exp_20260608_024_seed_ensemble_and_blend_check,Blend,seed_ensemble_blend_reference,0.969480,0.969580,NaN,NaN,0.969480,0.0,0.961956,0.976174,0.970311
12,020_blend_bias,exp_20260607_020_bias_search_on_019_best_blend,Blend,cv_trusted_attack_reference,0.969224,0.969690,NaN,NaN,0.969224,0.0,0.961137,0.976200,0.970335
13,026_realmlp_v5,exp_20260608_026_realmlp_v5_as_is,RealMLP,realmlp_v5_single_model_candidate,0.969039,0.969790,NaN,NaN,0.969039,0.0,0.959505,0.976431,0.971181
14,042_realmlp_v5_seed2026_foldvariant,exp_20260611_042_realmlp_v5_seed2026_foldvariant,RealMLP,realmlp_v5_seed_fold_variant_material,0.968948,0.969430,NaN,NaN,0.968948,0.0,0.958469,0.976541,0.971834
15,019_blend_best,exp_20260607_019_blend_add018_xgb_check,Blend,previous_public_confirmed_best,0.968872,0.970000,NaN,NaN,0.968872,0.0,0.965479,0.974441,0.966696
16,028_cat_v3,exp_20260608_028_cat_v3_as_is,CatBoost,catboost_v3_family_aux_material,0.968815,0.969690,NaN,NaN,0.968815,0.0,0.960099,0.974826,0.971520
17,035_shared001_updated,exp_20260610_035_shared001_updated_realmlp_pyt...,RealMLP,updated_shared001_realmlp_aux_material,0.968741,0.970120,NaN,NaN,0.968741,0.0,0.960591,0.976046,0.969586
18,039_cat_v3_seed2026_qbin_variant,exp_20260611_039_cat_v3_seed2026_qbin_variant,CatBoost,catboost_v3_lower_correlation_variant_material,0.968705,0.969840,NaN,NaN,0.968705,0.0,0.959571,0.974928,0.971616
19,044_shared001_updated_seed2027_foldvariant,exp_20260612_044_shared001_updated_seed2027_fo...,RealMLP,shared001_updated_seed_fold_variant_material,0.968604,0.970000,NaN,NaN,0.968604,0.0,0.959079,0.975756,0.970976
20,017_realmlp_bias,exp_20260606_017_bias_search_on_015_realmlp,RealMLP,previous_best_realmlp_bias_backup,0.968302,0.969850,NaN,NaN,0.968302,0.0,0.959889,0.975867,0.969150
21,015_realmlp_seed42,exp_20260605_015_shared001_realmlp_as_is,RealMLP,stable_single_realmlp_backup,0.968169,0.969770,NaN,NaN,0.968169,0.0,0.962234,0.976098,0.966177
22,018_xgb_shared003,exp_20260606_018_shared003_xgb_as_is,XGBoost,effective_blend_material,0.965208,0.965780,NaN,NaN,0.965208,0.0,0.966870,0.972043,0.956711
23,048_ovr_xgb_seed2027_fe_foldvariant,exp_20260614_048_ovr_xgb_seed2027_fe_foldvariant,XGBoost,improved_xgb_ovr_variant_material,0.963697,0.964440,NaN,NaN,0.963697,0.0,0.976915,0.968176,0.946001
24,032_ovr_tabm,exp_20260609_032_ovr_tabm_as_is,TabM,tabm_ovr_family_aux_material,0.961011,0.961060,0.96895,0.968617,0.961011,0.0,0.979880,0.965939,0.937213
25,030_ovr_xgb,exp_20260608_030_ovr_xgb_as_is,XGBoost,low_weight_auxiliary_xgb_ovr_material,0.960997,0.961180,NaN,NaN,0.960997,0.0,0.980163,0.965410,0.937418
26,047_xgb_multiclass_fe_objective_foldvariant,exp_20260614_047_xgb_multiclass_fe_objective_f...,XGBoost,failed_multiclass_xgb_variant_low_priority_dia...,0.959687,0.960270,NaN,NaN,0.959687,0.0,0.979798,0.964590,0.934674
27,037_tabicl_v2,exp_20260610_037_tabicl_v2_as_is,TabICL,weak_tabicl_family_material_optional_corr,0.958077,0.959200,NaN,NaN,0.958077,0.0,0.941422,0.970839,0.961970

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,037_tabicl_v2,047_xgb_multiclass_fe_objective_foldvariant,0.972636,0.953048,0.038251,0.049665,0.029753,0.020788,0.354564,0.028877,0.008965
1,030_ovr_xgb,037_tabicl_v2,0.974477,0.953569,0.037044,0.028955,0.049665,0.020975,0.363871,0.007980,0.028690
2,032_ovr_tabm,037_tabicl_v2,0.974850,0.953750,0.037186,0.029062,0.049665,0.020963,0.362909,0.008099,0.028702
3,037_tabicl_v2,048_ovr_xgb_seed2027_fe_foldvariant,0.978206,0.956579,0.033862,0.049665,0.029287,0.022716,0.403936,0.026949,0.006571
4,015_realmlp_seed42,037_tabicl_v2,0.979561,0.910951,0.031806,0.034388,0.049665,0.026350,0.456641,0.008038,0.023315
...,...,...,...,...,...,...,...,...,...,...,...
373,045_gpu_logreg_add044,049_gpu_logreg_add048,0.999960,0.998869,0.001136,0.034525,0.034452,0.033936,0.968464,0.000589,0.000516
374,040_gpu_logreg_add039,045_gpu_logreg_add044,0.999966,0.999174,0.001102,0.034865,0.034525,0.034158,0.969520,0.000707,0.000367
375,029_blend_add028,033_blend_add032,0.999993,0.999794,0.000438,0.034083,0.033838,0.033749,0.987632,0.000334,0.000088
376,029_blend_add028,031_blend_add030,0.999993,0.999801,0.000421,0.034083,0.033858,0.033768,0.988140,0.000315,0.000090
377,031_blend_add030,033_blend_add032,1.000000,0.999999,0.000031,0.033858,0.033838,0.033832,0.999079,0.000026,0.000005

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,037_tabicl_v2,049_gpu_logreg_add048,0.984050,0.957335,0.027732,0.049665,0.034452,0.028345,0.508230,0.021320,0.006107
1,047_xgb_multiclass_fe_objective_foldvariant,049_gpu_logreg_add048,0.989001,0.949482,0.022016,0.029753,0.034452,0.021230,0.493995,0.008523,0.013223
2,030_ovr_xgb,049_gpu_logreg_add048,0.990255,0.947497,0.021169,0.028955,0.034452,0.021225,0.503162,0.007730,0.013228
3,032_ovr_tabm,049_gpu_logreg_add048,0.990478,0.955091,0.021084,0.029062,0.034452,0.021320,0.505275,0.007742,0.013132
4,048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_logreg_add048,0.993048,0.951880,0.017257,0.029287,0.034452,0.023334,0.577503,0.005953,0.011118
5,018_xgb_shared003,049_gpu_logreg_add048,0.994308,0.968039,0.014147,0.033536,0.034452,0.026998,0.658624,0.006539,0.007455
6,015_realmlp_seed42,049_gpu_logreg_add048,0.996940,0.927431,0.010295,0.034388,0.034452,0.029391,0.745039,0.004997,0.005061
7,017_realmlp_bias,049_gpu_logreg_add048,0.997026,0.923623,0.010340,0.035542,0.034452,0.029940,0.747503,0.005601,0.004512
8,042_realmlp_v5_seed2026_foldvariant,049_gpu_logreg_add048,0.997536,0.853026,0.008517,0.035949,0.034452,0.031042,0.788682,0.004907,0.003410
9,044_shared001_updated_seed2027_foldvariant,049_gpu_logreg_add048,0.997714,0.893090,0.008679,0.035833,0.034452,0.030896,0.784398,0.004936,0.003556
10,026_realmlp_v5,049_gpu_logreg_add048,0.997809,0.854673,0.008272,0.035388,0.034452,0.030883,0.792726,0.004505,0.003570
11,035_shared001_updated,049_gpu_logreg_add048,0.997836,0.903812,0.008439,0.034984,0.034452,0.030595,0.787692,0.004389,0.003857
12,039_cat_v3_seed2026_qbin_variant,049_gpu_logreg_add048,0.998055,0.971637,0.008279,0.035587,0.034452,0.030968,0.792579,0.004619,0.003485
13,028_cat_v3,049_gpu_logreg_add048,0.998184,0.973372,0.008089,0.035277,0.034452,0.030907,0.796110,0.004370,0.003546
14,019_blend_best,049_gpu_logreg_add048,0.998254,0.940980,0.007850,0.032528,0.034452,0.029642,0.793895,0.002886,0.004810
15,020_blend_bias,049_gpu_logreg_add048,0.998611,0.946304,0.007058,0.034489,0.034452,0.031011,0.817572,0.003478,0.003442
16,024_seed_ensemble_blend,049_gpu_logreg_add048,0.998710,0.953747,0.006786,0.033962,0.034452,0.030888,0.823087,0.003074,0.003565
17,027_blend_add026,049_gpu_logreg_add048,0.998850,0.915036,0.006391,0.034163,0.034452,0.031189,0.833349,0.002974,0.003263
18,031_blend_add030,049_gpu_logreg_add048,0.999469,0.910104,0.003804,0.033858,0.034452,0.032312,0.897565,0.001547,0.002141
19,033_blend_add032,049_gpu_logreg_add048,0.999469,0.910155,0.003811,0.033838,0.034452,0.032298,0.897353,0.001540,0.002155
20,029_blend_add028,049_gpu_logreg_add048,0.999489,0.911543,0.003746,0.034083,0.034452,0.032452,0.899342,0.001632,0.002001
21,036_blend_add035,049_gpu_logreg_add048,0.999784,0.956014,0.002536,0.034264,0.034452,0.033122,0.930560,0.001141,0.001330
22,036_gpu_logreg_add035,049_gpu_logreg_add048,0.999786,0.997311,0.002938,0.035419,0.034452,0.033488,0.920404,0.001931,0.000965
23,034_gpu_logreg_default,049_gpu_logreg_add048,0.999854,0.997851,0.002343,0.034731,0.034452,0.033441,0.935598,0.001290,0.001012
24,038_gpu_logreg_add037,049_gpu_logreg_add048,0.999855,0.997559,0.002369,0.035533,0.034452,0.033829,0.935617,0.001704,0.000624
25,040_gpu_logreg_add039,049_gpu_logreg_add048,0.999947,0.998655,0.001389,0.034865,0.034452,0.033986,0.961957,0.000878,0.000466
26,045_gpu_logreg_add044,049_gpu_logreg_add048,0.999960,0.998869,0.001136,0.034525,0.034452,0.033936,0.968464,0.000589,0.000516

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,037_tabicl_v2,048_ovr_xgb_seed2027_fe_foldvariant,0.978206,0.956579,0.033862,0.049665,0.029287,0.022716,0.403936,0.026949,0.006571
1,042_realmlp_v5_seed2026_foldvariant,048_ovr_xgb_seed2027_fe_foldvariant,0.990047,0.755354,0.019548,0.035949,0.029287,0.022971,0.543480,0.012978,0.006317
2,017_realmlp_bias,048_ovr_xgb_seed2027_fe_foldvariant,0.990246,0.892845,0.019574,0.035542,0.029287,0.022763,0.541113,0.012779,0.006525
3,026_realmlp_v5,048_ovr_xgb_seed2027_fe_foldvariant,0.990399,0.757243,0.019016,0.035388,0.029287,0.022948,0.549956,0.012440,0.006339
4,015_realmlp_seed42,048_ovr_xgb_seed2027_fe_foldvariant,0.991328,0.907443,0.018050,0.034388,0.029287,0.022953,0.563651,0.011435,0.006334
5,044_shared001_updated_seed2027_foldvariant,048_ovr_xgb_seed2027_fe_foldvariant,0.991437,0.882209,0.018930,0.035833,0.029287,0.023223,0.554302,0.012609,0.006064
6,035_shared001_updated,048_ovr_xgb_seed2027_fe_foldvariant,0.991656,0.889307,0.018188,0.034984,0.029287,0.023159,0.563322,0.011825,0.006128
7,039_cat_v3_seed2026_qbin_variant,048_ovr_xgb_seed2027_fe_foldvariant,0.991735,0.967212,0.018441,0.035587,0.029287,0.023350,0.562318,0.012237,0.005938
8,028_cat_v3,048_ovr_xgb_seed2027_fe_foldvariant,0.991857,0.968028,0.018032,0.035277,0.029287,0.023390,0.568063,0.011887,0.005898
9,038_gpu_logreg_add037,048_ovr_xgb_seed2027_fe_foldvariant,0.991878,0.939663,0.019054,0.035533,0.029287,0.022981,0.549263,0.012552,0.006306
10,036_gpu_logreg_add035,048_ovr_xgb_seed2027_fe_foldvariant,0.992085,0.940781,0.018831,0.035419,0.029287,0.023038,0.552895,0.012381,0.006249
11,040_gpu_logreg_add039,048_ovr_xgb_seed2027_fe_foldvariant,0.992544,0.943643,0.017956,0.034865,0.029287,0.023194,0.566287,0.011671,0.006093
12,027_blend_add026,048_ovr_xgb_seed2027_fe_foldvariant,0.992661,0.833610,0.017334,0.034163,0.029287,0.023161,0.574868,0.011002,0.006126
13,020_blend_bias,048_ovr_xgb_seed2027_fe_foldvariant,0.992696,0.913729,0.017449,0.034489,0.029287,0.023270,0.574489,0.011219,0.006017
14,045_gpu_logreg_add044,048_ovr_xgb_seed2027_fe_foldvariant,0.992831,0.945691,0.017494,0.034525,0.029287,0.023253,0.573301,0.011272,0.006034
15,034_gpu_logreg_default,048_ovr_xgb_seed2027_fe_foldvariant,0.992863,0.942336,0.017650,0.034731,0.029287,0.023286,0.571672,0.011445,0.006002
16,029_blend_add028,048_ovr_xgb_seed2027_fe_foldvariant,0.992908,0.828030,0.016888,0.034083,0.029287,0.023353,0.583579,0.010730,0.005934
17,024_seed_ensemble_blend,048_ovr_xgb_seed2027_fe_foldvariant,0.992957,0.924699,0.016985,0.033962,0.029287,0.023236,0.580686,0.010727,0.006052
18,048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_logreg_add048,0.993048,0.951880,0.017257,0.029287,0.034452,0.023334,0.577503,0.005953,0.011118
19,036_blend_add035,048_ovr_xgb_seed2027_fe_foldvariant,0.993146,0.874180,0.016993,0.034264,0.029287,0.023372,0.581713,0.010891,0.005915
20,018_xgb_shared003,048_ovr_xgb_seed2027_fe_foldvariant,0.993179,0.971934,0.015272,0.033536,0.029287,0.023875,0.612976,0.009661,0.005413
21,031_blend_add030,048_ovr_xgb_seed2027_fe_foldvariant,0.993196,0.827006,0.016562,0.033858,0.029287,0.023402,0.588817,0.010456,0.005886
22,033_blend_add032,048_ovr_xgb_seed2027_fe_foldvariant,0.993213,0.827104,0.016534,0.033838,0.029287,0.023405,0.589264,0.010432,0.005882
23,019_blend_best,048_ovr_xgb_seed2027_fe_foldvariant,0.994441,0.923319,0.014456,0.032528,0.029287,0.023773,0.624886,0.008756,0.005515
24,047_xgb_multiclass_fe_objective_foldvariant,048_ovr_xgb_seed2027_fe_foldvariant,0.997475,0.980912,0.008775,0.029753,0.029287,0.025231,0.746260,0.004522,0.004056
25,032_ovr_tabm,048_ovr_xgb_seed2027_fe_foldvariant,0.997892,0.982367,0.008052,0.029062,0.029287,0.025222,0.761372,0.003840,0.004065
26,030_ovr_xgb,048_ovr_xgb_seed2027_fe_foldvariant,0.998682,0.993460,0.006606,0.028955,0.029287,0.025889,0.800203,0.003066,0.003398

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,037_tabicl_v2,047_xgb_multiclass_fe_objective_foldvariant,0.972636,0.953048,0.038251,0.049665,0.029753,0.020788,0.354564,0.028877,0.008965
1,042_realmlp_v5_seed2026_foldvariant,047_xgb_multiclass_fe_objective_foldvariant,0.986131,0.752138,0.023714,0.035949,0.029753,0.021140,0.474386,0.014809,0.008614
2,026_realmlp_v5,047_xgb_multiclass_fe_objective_foldvariant,0.986641,0.754358,0.023149,0.035388,0.029753,0.021148,0.480728,0.014239,0.008605
3,017_realmlp_bias,047_xgb_multiclass_fe_objective_foldvariant,0.986868,0.891112,0.023364,0.035542,0.029753,0.021129,0.478411,0.014412,0.008624
4,038_gpu_logreg_add037,047_xgb_multiclass_fe_objective_foldvariant,0.987637,0.937710,0.023721,0.035533,0.029753,0.020922,0.471578,0.014612,0.008832
5,044_shared001_updated_seed2027_foldvariant,047_xgb_multiclass_fe_objective_foldvariant,0.987750,0.880705,0.023059,0.035833,0.029753,0.021417,0.484883,0.014416,0.008336
6,039_cat_v3_seed2026_qbin_variant,047_xgb_multiclass_fe_objective_foldvariant,0.987780,0.965998,0.022865,0.035587,0.029753,0.021400,0.487012,0.014187,0.008354
7,036_gpu_logreg_add035,047_xgb_multiclass_fe_objective_foldvariant,0.987823,0.938261,0.023539,0.035419,0.029753,0.020954,0.473892,0.014464,0.008799
8,028_cat_v3,047_xgb_multiclass_fe_objective_foldvariant,0.987942,0.966078,0.022451,0.035277,0.029753,0.021433,0.491597,0.013844,0.008321
9,035_shared001_updated,047_xgb_multiclass_fe_objective_foldvariant,0.988141,0.887807,0.022281,0.034984,0.029753,0.021379,0.493069,0.013605,0.008375
10,015_realmlp_seed42,047_xgb_multiclass_fe_objective_foldvariant,0.988230,0.905711,0.021666,0.034388,0.029753,0.021398,0.500608,0.012990,0.008355
11,040_gpu_logreg_add039,047_xgb_multiclass_fe_objective_foldvariant,0.988492,0.943339,0.022619,0.034865,0.029753,0.021138,0.486157,0.013727,0.008615
12,034_gpu_logreg_default,047_xgb_multiclass_fe_objective_foldvariant,0.988778,0.940954,0.022318,0.034731,0.029753,0.021223,0.490571,0.013508,0.008530
13,045_gpu_logreg_add044,047_xgb_multiclass_fe_objective_foldvariant,0.988839,0.944789,0.022189,0.034525,0.029753,0.021183,0.491540,0.013342,0.008570
14,047_xgb_multiclass_fe_objective_foldvariant,049_gpu_logreg_add048,0.989001,0.949482,0.022016,0.029753,0.034452,0.021230,0.493995,0.008523,0.013223
15,020_blend_bias,047_xgb_multiclass_fe_objective_foldvariant,0.989103,0.910509,0.021704,0.034489,0.029753,0.021415,0.500040,0.013074,0.008338
16,027_blend_add026,047_xgb_multiclass_fe_objective_foldvariant,0.989123,0.831452,0.021543,0.034163,0.029753,0.021325,0.500691,0.012838,0.008428
17,029_blend_add028,047_xgb_multiclass_fe_objective_foldvariant,0.989137,0.825562,0.021420,0.034083,0.029753,0.021353,0.502609,0.012731,0.008400
18,036_blend_add035,047_xgb_multiclass_fe_objective_foldvariant,0.989248,0.871979,0.021616,0.034264,0.029753,0.021336,0.499878,0.012928,0.008418
19,031_blend_add030,047_xgb_multiclass_fe_objective_foldvariant,0.989468,0.824466,0.021090,0.033858,0.029753,0.021405,0.507141,0.012454,0.008349
20,033_blend_add032,047_xgb_multiclass_fe_objective_foldvariant,0.989490,0.824570,0.021062,0.033838,0.029753,0.021408,0.507514,0.012429,0.008345
21,024_seed_ensemble_blend,047_xgb_multiclass_fe_objective_foldvariant,0.989506,0.922171,0.021183,0.033962,0.029753,0.021403,0.505833,0.012559,0.008350
22,018_xgb_shared003,047_xgb_multiclass_fe_objective_foldvariant,0.990144,0.968763,0.019021,0.033536,0.029753,0.022271,0.542944,0.011265,0.007483
23,019_blend_best,047_xgb_multiclass_fe_objective_foldvariant,0.991376,0.921757,0.018543,0.032528,0.029753,0.022002,0.546248,0.010526,0.007751
24,032_ovr_tabm,047_xgb_multiclass_fe_objective_foldvariant,0.997080,0.974466,0.009540,0.029062,0.029753,0.024727,0.725370,0.004335,0.005026
25,030_ovr_xgb,047_xgb_multiclass_fe_objective_foldvariant,0.997424,0.979295,0.008910,0.028955,0.029753,0.024994,0.741331,0.003961,0.004760
26,047_xgb_multiclass_fe_objective_foldvariant,048_ovr_xgb_seed2027_fe_foldvariant,0.997475,0.980912,0.008775,0.029753,0.029287,0.025231,0.746260,0.004522,0.004056

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,037_tabicl_v2,045_gpu_logreg_add044,0.984186,0.955351,0.027613,0.049665,0.034525,0.028435,0.510003,0.021230,0.006090
1,045_gpu_logreg_add044,047_xgb_multiclass_fe_objective_foldvariant,0.988839,0.944789,0.022189,0.034525,0.029753,0.021183,0.491540,0.013342,0.008570
2,030_ovr_xgb,045_gpu_logreg_add044,0.990156,0.942695,0.021306,0.028955,0.034525,0.021187,0.500942,0.007768,0.013339
3,032_ovr_tabm,045_gpu_logreg_add044,0.990390,0.951425,0.021247,0.029062,0.034525,0.021271,0.502681,0.007791,0.013254
4,045_gpu_logreg_add044,048_ovr_xgb_seed2027_fe_foldvariant,0.992831,0.945691,0.017494,0.034525,0.029287,0.023253,0.573301,0.011272,0.006034
5,018_xgb_shared003,045_gpu_logreg_add044,0.994284,0.965120,0.014118,0.033536,0.034525,0.027039,0.659137,0.006497,0.007486
6,015_realmlp_seed42,045_gpu_logreg_add044,0.996933,0.926308,0.010306,0.034388,0.034525,0.029423,0.745044,0.004966,0.005103
7,017_realmlp_bias,045_gpu_logreg_add044,0.997038,0.923205,0.010356,0.035542,0.034525,0.029968,0.747354,0.005574,0.004557
8,042_realmlp_v5_seed2026_foldvariant,045_gpu_logreg_add044,0.997539,0.857610,0.008610,0.035949,0.034525,0.031032,0.786756,0.004917,0.003494
9,044_shared001_updated_seed2027_foldvariant,045_gpu_logreg_add044,0.997719,0.892361,0.008721,0.035833,0.034525,0.030914,0.783735,0.004919,0.003611
10,026_realmlp_v5,045_gpu_logreg_add044,0.997793,0.860130,0.008349,0.035388,0.034525,0.030884,0.791328,0.004503,0.003641
11,035_shared001_updated,045_gpu_logreg_add044,0.997819,0.901692,0.008534,0.034984,0.034525,0.030585,0.785743,0.004399,0.003940
12,039_cat_v3_seed2026_qbin_variant,045_gpu_logreg_add044,0.998123,0.969399,0.008170,0.035587,0.034525,0.031054,0.795078,0.004533,0.003471
13,028_cat_v3,045_gpu_logreg_add044,0.998216,0.970972,0.008068,0.035277,0.034525,0.030952,0.796701,0.004325,0.003573
14,019_blend_best,045_gpu_logreg_add044,0.998256,0.939575,0.007876,0.032528,0.034525,0.029662,0.793265,0.002867,0.004864
15,020_blend_bias,045_gpu_logreg_add044,0.998630,0.945740,0.006992,0.034489,0.034525,0.031077,0.819157,0.003412,0.003449
16,024_seed_ensemble_blend,045_gpu_logreg_add044,0.998733,0.953208,0.006720,0.033962,0.034525,0.030955,0.824773,0.003007,0.003570
17,027_blend_add026,045_gpu_logreg_add044,0.998862,0.918929,0.006377,0.034163,0.034525,0.031231,0.833765,0.002932,0.003294
18,031_blend_add030,045_gpu_logreg_add044,0.999479,0.914232,0.003925,0.033858,0.034525,0.032286,0.894391,0.001573,0.002240
19,033_blend_add032,045_gpu_logreg_add044,0.999479,0.914281,0.003928,0.033838,0.034525,0.032273,0.894270,0.001564,0.002252
20,029_blend_add028,045_gpu_logreg_add044,0.999503,0.915659,0.003804,0.034083,0.034525,0.032457,0.897806,0.001626,0.002068
21,036_blend_add035,045_gpu_logreg_add044,0.999789,0.959305,0.002583,0.034264,0.034525,0.033134,0.929317,0.001129,0.001391
22,036_gpu_logreg_add035,045_gpu_logreg_add044,0.999791,0.997941,0.002873,0.035419,0.034525,0.033557,0.922220,0.001862,0.000968
23,034_gpu_logreg_default,045_gpu_logreg_add044,0.999859,0.998380,0.002298,0.034731,0.034525,0.033498,0.936789,0.001233,0.001027
24,038_gpu_logreg_add037,045_gpu_logreg_add044,0.999870,0.998229,0.002234,0.035533,0.034525,0.033926,0.938929,0.001607,0.000599
25,045_gpu_logreg_add044,049_gpu_logreg_add048,0.999960,0.998869,0.001136,0.034525,0.034452,0.033936,0.968464,0.000589,0.000516
26,040_gpu_logreg_add039,045_gpu_logreg_add044,0.999966,0.999174,0.001102,0.034865,0.034525,0.034158,0.969520,0.000707,0.000367

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,037_tabicl_v2,040_gpu_logreg_add039,0.984338,0.953540,0.027484,0.049665,0.034865,0.028666,0.513131,0.021000,0.006199
1,040_gpu_logreg_add039,047_xgb_multiclass_fe_objective_foldvariant,0.988492,0.943339,0.022619,0.034865,0.029753,0.021138,0.486157,0.013727,0.008615
2,030_ovr_xgb,040_gpu_logreg_add039,0.989809,0.940546,0.021798,0.028955,0.034865,0.021114,0.494403,0.007841,0.013751
3,032_ovr_tabm,040_gpu_logreg_add039,0.990036,0.949985,0.021753,0.029062,0.034865,0.021195,0.496007,0.007867,0.013669
4,040_gpu_logreg_add039,048_ovr_xgb_seed2027_fe_foldvariant,0.992544,0.943643,0.017956,0.034865,0.029287,0.023194,0.566287,0.011671,0.006093
5,018_xgb_shared003,040_gpu_logreg_add039,0.994166,0.963306,0.014267,0.033536,0.034865,0.027134,0.657545,0.006402,0.007730
6,015_realmlp_seed42,040_gpu_logreg_add039,0.996843,0.927797,0.010510,0.034388,0.034865,0.029495,0.741875,0.004893,0.005369
7,017_realmlp_bias,040_gpu_logreg_add039,0.996997,0.925200,0.010458,0.035542,0.034865,0.030093,0.746466,0.005449,0.004772
8,040_gpu_logreg_add039,042_realmlp_v5_seed2026_foldvariant,0.997561,0.859032,0.008543,0.034865,0.035949,0.031236,0.789234,0.003629,0.004713
9,040_gpu_logreg_add039,044_shared001_updated_seed2027_foldvariant,0.997731,0.893517,0.008676,0.034865,0.035833,0.031110,0.785833,0.003755,0.004723
10,026_realmlp_v5,040_gpu_logreg_add039,0.997798,0.861649,0.008385,0.035388,0.034865,0.031044,0.791757,0.004344,0.003821
11,035_shared001_updated,040_gpu_logreg_add039,0.997811,0.902374,0.008593,0.034984,0.034865,0.030728,0.785487,0.004256,0.004136
12,039_cat_v3_seed2026_qbin_variant,040_gpu_logreg_add039,0.998130,0.968624,0.008123,0.035587,0.034865,0.031245,0.796916,0.004342,0.003620
13,019_blend_best,040_gpu_logreg_add039,0.998178,0.940981,0.008153,0.032528,0.034865,0.029693,0.787605,0.002835,0.005172
14,028_cat_v3,040_gpu_logreg_add039,0.998209,0.969897,0.008044,0.035277,0.034865,0.031127,0.797825,0.004150,0.003738
15,020_blend_bias,040_gpu_logreg_add039,0.998610,0.947194,0.007093,0.034489,0.034865,0.031194,0.817484,0.003294,0.003670
16,024_seed_ensemble_blend,040_gpu_logreg_add039,0.998693,0.953361,0.006907,0.033962,0.034865,0.031035,0.821211,0.002927,0.003830
17,027_blend_add026,040_gpu_logreg_add039,0.998835,0.920134,0.006502,0.034163,0.034865,0.031343,0.831732,0.002820,0.003521
18,033_blend_add032,040_gpu_logreg_add039,0.999463,0.915413,0.004006,0.033838,0.034865,0.032402,0.892595,0.001436,0.002463
19,031_blend_add030,040_gpu_logreg_add039,0.999463,0.915366,0.003996,0.033858,0.034865,0.032417,0.892896,0.001441,0.002447
20,029_blend_add028,040_gpu_logreg_add039,0.999494,0.916822,0.003845,0.034083,0.034865,0.032604,0.897107,0.001479,0.002260
21,036_blend_add035,040_gpu_logreg_add039,0.999775,0.960206,0.002673,0.034264,0.034865,0.033257,0.927137,0.001006,0.001607
22,036_gpu_logreg_add035,040_gpu_logreg_add039,0.999789,0.997822,0.002906,0.035419,0.034865,0.033713,0.921853,0.001706,0.001152
23,034_gpu_logreg_default,040_gpu_logreg_add039,0.999845,0.998313,0.002418,0.034731,0.034865,0.033607,0.933824,0.001124,0.001257
24,038_gpu_logreg_add037,040_gpu_logreg_add039,0.999884,0.998178,0.002068,0.035533,0.034865,0.034180,0.943759,0.001353,0.000684
25,040_gpu_logreg_add039,049_gpu_logreg_add048,0.999947,0.998655,0.001389,0.034865,0.034452,0.033986,0.961957,0.000878,0.000466
26,040_gpu_logreg_add039,045_gpu_logreg_add044,0.999966,0.999174,0.001102,0.034865,0.034525,0.034158,0.969520,0.000707,0.000367

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,037_tabicl_v2,038_gpu_logreg_add037,0.984509,0.953093,0.027354,0.049665,0.035533,0.029073,0.517992,0.020592,0.006461
1,038_gpu_logreg_add037,047_xgb_multiclass_fe_objective_foldvariant,0.987637,0.937710,0.023721,0.035533,0.029753,0.020922,0.471578,0.014612,0.008832
2,030_ovr_xgb,038_gpu_logreg_add037,0.989016,0.936473,0.022898,0.028955,0.035533,0.020903,0.479574,0.008052,0.014631
3,032_ovr_tabm,038_gpu_logreg_add037,0.989262,0.945291,0.022799,0.029062,0.035533,0.021006,0.481920,0.008056,0.014527
4,038_gpu_logreg_add037,048_ovr_xgb_seed2027_fe_foldvariant,0.991878,0.939663,0.019054,0.035533,0.029287,0.022981,0.549263,0.012552,0.006306
5,018_xgb_shared003,038_gpu_logreg_add037,0.993836,0.961689,0.014768,0.033536,0.035533,0.027219,0.650401,0.006317,0.008314
6,015_realmlp_seed42,038_gpu_logreg_add037,0.996779,0.922695,0.010654,0.034388,0.035533,0.029757,0.740869,0.004632,0.005776
7,017_realmlp_bias,038_gpu_logreg_add037,0.996982,0.920486,0.010491,0.035542,0.035533,0.030408,0.747732,0.005134,0.005125
8,038_gpu_logreg_add037,042_realmlp_v5_seed2026_foldvariant,0.997556,0.865760,0.008653,0.035533,0.035949,0.031518,0.788671,0.004015,0.004431
9,038_gpu_logreg_add037,039_cat_v3_seed2026_qbin_variant,0.997587,0.963981,0.009395,0.035533,0.035587,0.030954,0.770634,0.004580,0.004633
10,038_gpu_logreg_add037,044_shared001_updated_seed2027_foldvariant,0.997696,0.892139,0.008839,0.035533,0.035833,0.031369,0.784298,0.004164,0.004464
11,035_shared001_updated,038_gpu_logreg_add037,0.997770,0.899700,0.008749,0.034984,0.035533,0.030988,0.783937,0.003996,0.004545
12,026_realmlp_v5,038_gpu_logreg_add037,0.997836,0.869126,0.008323,0.035388,0.035533,0.031407,0.794854,0.003980,0.004126
13,019_blend_best,038_gpu_logreg_add037,0.997989,0.935244,0.008709,0.032528,0.035533,0.029750,0.776527,0.002778,0.005783
14,028_cat_v3,038_gpu_logreg_add037,0.998150,0.967380,0.008354,0.035277,0.035533,0.031314,0.792834,0.003963,0.004219
15,020_blend_bias,038_gpu_logreg_add037,0.998573,0.943446,0.007138,0.034489,0.035533,0.031504,0.817924,0.002984,0.004029
16,024_seed_ensemble_blend,038_gpu_logreg_add037,0.998643,0.951395,0.007022,0.033962,0.035533,0.031309,0.819885,0.002654,0.004224
17,027_blend_add026,038_gpu_logreg_add037,0.998808,0.924612,0.006632,0.034163,0.035533,0.031610,0.829960,0.002553,0.003923
18,033_blend_add032,038_gpu_logreg_add037,0.999421,0.920306,0.004458,0.033838,0.035533,0.032514,0.882184,0.001323,0.003019
19,031_blend_add030,038_gpu_logreg_add037,0.999422,0.920266,0.004441,0.033858,0.035533,0.032533,0.882660,0.001325,0.003000
20,029_blend_add028,038_gpu_logreg_add037,0.999470,0.921697,0.004214,0.034083,0.035533,0.032758,0.888769,0.001325,0.002775
21,036_blend_add035,038_gpu_logreg_add037,0.999776,0.963825,0.002896,0.034264,0.035533,0.033479,0.921833,0.000785,0.002054
22,038_gpu_logreg_add037,049_gpu_logreg_add048,0.999855,0.997559,0.002369,0.035533,0.034452,0.033829,0.935617,0.001704,0.000624
23,038_gpu_logreg_add037,045_gpu_logreg_add044,0.999870,0.998229,0.002234,0.035533,0.034525,0.033926,0.938929,0.001607,0.000599
24,038_gpu_logreg_add037,040_gpu_logreg_add039,0.999884,0.998178,0.002068,0.035533,0.034865,0.034180,0.943759,0.001353,0.000684
25,034_gpu_logreg_default,038_gpu_logreg_add037,0.999886,0.998602,0.002065,0.034731,0.035533,0.034113,0.943609,0.000618,0.001420
26,036_gpu_logreg_add035,038_gpu_logreg_add037,0.999909,0.998891,0.001909,0.035419,0.035533,0.034539,0.948533,0.000880,0.000994

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,033_blend_add032,037_tabicl_v2,0.984870,0.865547,0.027770,0.033838,0.049665,0.028016,0.504916,0.005821,0.021649
1,033_blend_add032,047_xgb_multiclass_fe_objective_foldvariant,0.989490,0.824570,0.021062,0.033838,0.029753,0.021408,0.507514,0.012429,0.008345
2,030_ovr_xgb,033_blend_add032,0.990558,0.821940,0.020357,0.028955,0.033838,0.021344,0.514960,0.007611,0.012493
3,032_ovr_tabm,033_blend_add032,0.990801,0.830690,0.020230,0.029062,0.033838,0.021446,0.517361,0.007616,0.012391
4,033_blend_add032,048_ovr_xgb_seed2027_fe_foldvariant,0.993213,0.827104,0.016534,0.033838,0.029287,0.023405,0.589264,0.010432,0.005882
5,018_xgb_shared003,033_blend_add032,0.993883,0.858653,0.014542,0.033536,0.033838,0.026513,0.648849,0.007024,0.007325
6,015_realmlp_seed42,033_blend_add032,0.997205,0.868130,0.009731,0.034388,0.033838,0.029355,0.755191,0.005033,0.004483
7,017_realmlp_bias,033_blend_add032,0.997258,0.881385,0.009920,0.035542,0.033838,0.029828,0.754149,0.005714,0.004010
8,033_blend_add032,042_realmlp_v5_seed2026_foldvariant,0.997788,0.944717,0.008588,0.033838,0.035949,0.030692,0.785078,0.003145,0.005257
9,033_blend_add032,044_shared001_updated_seed2027_foldvariant,0.997856,0.858801,0.008497,0.033838,0.035833,0.030677,0.786701,0.003161,0.005156
10,033_blend_add032,039_cat_v3_seed2026_qbin_variant,0.997930,0.870715,0.008723,0.033838,0.035587,0.030439,0.780789,0.003398,0.005148
11,033_blend_add032,035_shared001_updated,0.998127,0.842031,0.007886,0.033838,0.034984,0.030554,0.798407,0.003284,0.004431
12,019_blend_best,033_blend_add032,0.998300,0.878981,0.007554,0.032528,0.033838,0.029478,0.799127,0.003050,0.004360
13,020_blend_bias,033_blend_add032,0.998542,0.899930,0.007273,0.034489,0.033838,0.030592,0.810704,0.003897,0.003246
14,026_realmlp_v5,033_blend_add032,0.998543,0.976770,0.007065,0.035388,0.033838,0.031158,0.818500,0.004230,0.002679
15,028_cat_v3,033_blend_add032,0.998737,0.872920,0.006963,0.035277,0.033838,0.031146,0.820309,0.004131,0.002692
16,024_seed_ensemble_blend,033_blend_add032,0.998746,0.900790,0.006750,0.033962,0.033838,0.030590,0.822092,0.003372,0.003248
17,027_blend_add026,033_blend_add032,0.999060,0.992074,0.006028,0.034163,0.033838,0.031049,0.840255,0.003114,0.002789
18,033_blend_add032,036_gpu_logreg_add035,0.999414,0.919516,0.004438,0.033838,0.035419,0.032467,0.882533,0.001370,0.002951
19,033_blend_add032,038_gpu_logreg_add037,0.999421,0.920306,0.004458,0.033838,0.035533,0.032514,0.882184,0.001323,0.003019
20,033_blend_add032,040_gpu_logreg_add039,0.999463,0.915413,0.004006,0.033838,0.034865,0.032402,0.892595,0.001436,0.002463
21,033_blend_add032,049_gpu_logreg_add048,0.999469,0.910155,0.003811,0.033838,0.034452,0.032298,0.897353,0.001540,0.002155
22,033_blend_add032,045_gpu_logreg_add044,0.999479,0.914281,0.003928,0.033838,0.034525,0.032273,0.894270,0.001564,0.002252
23,033_blend_add032,034_gpu_logreg_default,0.999534,0.918898,0.003618,0.033838,0.034731,0.032526,0.902446,0.001311,0.002205
24,033_blend_add032,036_blend_add035,0.999863,0.983102,0.002084,0.033838,0.034264,0.033037,0.942205,0.000800,0.001226
25,029_blend_add028,033_blend_add032,0.999993,0.999794,0.000438,0.034083,0.033838,0.033749,0.987632,0.000334,0.000088
26,031_blend_add030,033_blend_add032,1.000000,0.999999,0.000031,0.033858,0.033838,0.033832,0.999079,0.000026,0.000005

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,031_blend_add030,037_tabicl_v2,0.984873,0.865479,0.027770,0.033858,0.049665,0.028026,0.505009,0.005832,0.021639
1,031_blend_add030,047_xgb_multiclass_fe_objective_foldvariant,0.989468,0.824466,0.021090,0.033858,0.029753,0.021405,0.507141,0.012454,0.008349
2,030_ovr_xgb,031_blend_add030,0.990536,0.821836,0.020385,0.028955,0.033858,0.021341,0.514576,0.007614,0.012518
3,031_blend_add030,032_ovr_tabm,0.990777,0.830573,0.020262,0.033858,0.029062,0.021441,0.516912,0.012417,0.007621
4,031_blend_add030,048_ovr_xgb_seed2027_fe_foldvariant,0.993196,0.827006,0.016562,0.033858,0.029287,0.023402,0.588817,0.010456,0.005886
5,018_xgb_shared003,031_blend_add030,0.993874,0.858577,0.014553,0.033536,0.033858,0.026518,0.648729,0.007018,0.007340
6,015_realmlp_seed42,031_blend_add030,0.997199,0.868061,0.009734,0.034388,0.033858,0.029364,0.755178,0.005025,0.004495
7,017_realmlp_bias,031_blend_add030,0.997253,0.881326,0.009913,0.035542,0.033858,0.029842,0.754368,0.005700,0.004017
8,031_blend_add030,042_realmlp_v5_seed2026_foldvariant,0.997786,0.944782,0.008584,0.033858,0.035949,0.030704,0.785214,0.003154,0.005245
9,031_blend_add030,044_shared001_updated_seed2027_foldvariant,0.997853,0.858744,0.008487,0.033858,0.035833,0.030692,0.786996,0.003166,0.005141
10,031_blend_add030,039_cat_v3_seed2026_qbin_variant,0.997933,0.870672,0.008719,0.033858,0.035587,0.030451,0.780927,0.003407,0.005136
11,031_blend_add030,035_shared001_updated,0.998123,0.841979,0.007883,0.033858,0.034984,0.030566,0.798543,0.003293,0.004418
12,019_blend_best,031_blend_add030,0.998293,0.878896,0.007571,0.032528,0.033858,0.029480,0.798761,0.003048,0.004379
13,020_blend_bias,031_blend_add030,0.998538,0.899859,0.007276,0.034489,0.033858,0.030600,0.810673,0.003888,0.003258
14,026_realmlp_v5,031_blend_add030,0.998540,0.976821,0.007079,0.035388,0.033858,0.031162,0.818219,0.004226,0.002697
15,024_seed_ensemble_blend,031_blend_add030,0.998741,0.900716,0.006753,0.033962,0.033858,0.030599,0.822057,0.003364,0.003260
16,028_cat_v3,031_blend_add030,0.998742,0.872885,0.006942,0.035277,0.033858,0.031167,0.820857,0.004110,0.002692
17,027_blend_add026,031_blend_add030,0.999055,0.992043,0.006038,0.034163,0.033858,0.031054,0.840041,0.003109,0.002804
18,031_blend_add030,036_gpu_logreg_add035,0.999415,0.919475,0.004420,0.033858,0.035419,0.032487,0.883009,0.001372,0.002932
19,031_blend_add030,038_gpu_logreg_add037,0.999422,0.920266,0.004441,0.033858,0.035533,0.032533,0.882660,0.001325,0.003000
20,031_blend_add030,040_gpu_logreg_add039,0.999463,0.915366,0.003996,0.033858,0.034865,0.032417,0.892896,0.001441,0.002447
21,031_blend_add030,049_gpu_logreg_add048,0.999469,0.910104,0.003804,0.033858,0.034452,0.032312,0.897565,0.001547,0.002141
22,031_blend_add030,045_gpu_logreg_add044,0.999479,0.914232,0.003925,0.033858,0.034525,0.032286,0.894391,0.001573,0.002240
23,031_blend_add030,034_gpu_logreg_default,0.999534,0.918851,0.003608,0.033858,0.034731,0.032542,0.902748,0.001316,0.002189
24,031_blend_add030,036_blend_add035,0.999862,0.983076,0.002077,0.033858,0.034264,0.033051,0.942414,0.000807,0.001212
25,029_blend_add028,031_blend_add030,0.999993,0.999801,0.000421,0.034083,0.033858,0.033768,0.988140,0.000315,0.000090
26,031_blend_add030,033_blend_add032,1.000000,0.999999,0.000031,0.033858,0.033838,0.033832,0.999079,0.000026,0.000005

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,030_ovr_xgb,037_tabicl_v2,0.974477,0.953569,0.037044,0.028955,0.049665,0.020975,0.363871,0.007980,0.028690
1,030_ovr_xgb,042_realmlp_v5_seed2026_foldvariant,0.987105,0.749468,0.023140,0.028955,0.035949,0.021019,0.478944,0.007936,0.014930
2,026_realmlp_v5,030_ovr_xgb,0.987581,0.751435,0.022543,0.035388,0.028955,0.021039,0.485861,0.014348,0.007916
3,017_realmlp_bias,030_ovr_xgb,0.988127,0.889617,0.022371,0.035542,0.028955,0.021218,0.490255,0.014324,0.007737
4,030_ovr_xgb,044_shared001_updated_seed2027_foldvariant,0.988672,0.878785,0.022475,0.028955,0.035833,0.021294,0.489586,0.007661,0.014539
5,030_ovr_xgb,039_cat_v3_seed2026_qbin_variant,0.988783,0.964342,0.022205,0.028955,0.035587,0.021308,0.492849,0.007647,0.014279
6,028_cat_v3,030_ovr_xgb,0.988941,0.965161,0.021862,0.035277,0.028955,0.021330,0.497194,0.013947,0.007625
7,030_ovr_xgb,038_gpu_logreg_add037,0.989016,0.936473,0.022898,0.028955,0.035533,0.020903,0.479574,0.008052,0.014631
8,030_ovr_xgb,035_shared001_updated,0.989101,0.885761,0.021524,0.028955,0.034984,0.021342,0.501037,0.007612,0.013642
9,030_ovr_xgb,036_gpu_logreg_add035,0.989202,0.937636,0.022671,0.028955,0.035419,0.020958,0.482726,0.007997,0.014461
10,015_realmlp_seed42,030_ovr_xgb,0.989464,0.904945,0.020662,0.034388,0.028955,0.021493,0.513575,0.012895,0.007462
11,030_ovr_xgb,040_gpu_logreg_add039,0.989809,0.940546,0.021798,0.028955,0.034865,0.021114,0.494403,0.007841,0.013751
12,030_ovr_xgb,034_gpu_logreg_default,0.990145,0.939215,0.021476,0.028955,0.034731,0.021218,0.499613,0.007737,0.013514
13,030_ovr_xgb,045_gpu_logreg_add044,0.990156,0.942695,0.021306,0.028955,0.034525,0.021187,0.500942,0.007768,0.013339
14,029_blend_add028,030_ovr_xgb,0.990184,0.822720,0.020717,0.034083,0.028955,0.021287,0.509853,0.012796,0.007668
15,030_ovr_xgb,049_gpu_logreg_add048,0.990255,0.947497,0.021169,0.028955,0.034452,0.021225,0.503162,0.007730,0.013228
16,027_blend_add026,030_ovr_xgb,0.990340,0.828804,0.020643,0.034163,0.028955,0.021363,0.511636,0.012800,0.007592
17,020_blend_bias,030_ovr_xgb,0.990453,0.910471,0.020724,0.034489,0.028955,0.021488,0.512158,0.013001,0.007467
18,030_ovr_xgb,036_blend_add035,0.990463,0.869145,0.020823,0.028955,0.034264,0.021310,0.508472,0.007645,0.012954
19,030_ovr_xgb,031_blend_add030,0.990536,0.821836,0.020385,0.028955,0.033858,0.021341,0.514576,0.007614,0.012518
20,030_ovr_xgb,033_blend_add032,0.990558,0.821940,0.020357,0.028955,0.033838,0.021344,0.514960,0.007611,0.012493
21,024_seed_ensemble_blend,030_ovr_xgb,0.990816,0.921454,0.020201,0.033962,0.028955,0.021479,0.518350,0.012483,0.007476
22,018_xgb_shared003,030_ovr_xgb,0.991339,0.969567,0.017707,0.033536,0.028955,0.022513,0.563147,0.011023,0.006442
23,019_blend_best,030_ovr_xgb,0.992669,0.920682,0.017269,0.032528,0.028955,0.022219,0.565883,0.010309,0.006736
24,030_ovr_xgb,047_xgb_multiclass_fe_objective_foldvariant,0.997424,0.979295,0.008910,0.028955,0.029753,0.024994,0.741331,0.003961,0.004760
25,030_ovr_xgb,032_ovr_tabm,0.998351,0.984010,0.006651,0.028955,0.029062,0.025754,0.798250,0.003201,0.003308
26,030_ovr_xgb,048_ovr_xgb_seed2027_fe_foldvariant,0.998682,0.993460,0.006606,0.028955,0.029287,0.025889,0.800203,0.003066,0.003398

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,037_tabicl_v2,044_shared001_updated_seed2027_foldvariant,0.983156,0.882472,0.029218,0.049665,0.035833,0.028319,0.495274,0.021346,0.007514
1,044_shared001_updated_seed2027_foldvariant,047_xgb_multiclass_fe_objective_foldvariant,0.987750,0.880705,0.023059,0.035833,0.029753,0.021417,0.484883,0.014416,0.008336
2,030_ovr_xgb,044_shared001_updated_seed2027_foldvariant,0.988672,0.878785,0.022475,0.028955,0.035833,0.021294,0.489586,0.007661,0.014539
3,032_ovr_tabm,044_shared001_updated_seed2027_foldvariant,0.989198,0.883758,0.022169,0.029062,0.035833,0.021491,0.495151,0.007571,0.014341
4,018_xgb_shared003,044_shared001_updated_seed2027_foldvariant,0.991347,0.884525,0.017563,0.033536,0.035833,0.026031,0.600655,0.007505,0.009802
5,044_shared001_updated_seed2027_foldvariant,048_ovr_xgb_seed2027_fe_foldvariant,0.991437,0.882209,0.018930,0.035833,0.029287,0.023223,0.554302,0.012609,0.006064
6,039_cat_v3_seed2026_qbin_variant,044_shared001_updated_seed2027_foldvariant,0.995318,0.892239,0.012985,0.035587,0.035833,0.029345,0.697431,0.006242,0.006488
7,028_cat_v3,044_shared001_updated_seed2027_foldvariant,0.995321,0.892453,0.013127,0.035277,0.035833,0.029130,0.693898,0.006147,0.006703
8,015_realmlp_seed42,044_shared001_updated_seed2027_foldvariant,0.996538,0.876838,0.010829,0.034388,0.035833,0.029802,0.737316,0.004586,0.006031
9,017_realmlp_bias,044_shared001_updated_seed2027_foldvariant,0.996663,0.875192,0.010869,0.035542,0.035833,0.030353,0.739909,0.005189,0.005480
10,019_blend_best,044_shared001_updated_seed2027_foldvariant,0.996878,0.884204,0.010387,0.032528,0.035833,0.029074,0.740058,0.003454,0.006759
11,020_blend_bias,044_shared001_updated_seed2027_foldvariant,0.997250,0.884472,0.009850,0.034489,0.035833,0.030327,0.758261,0.004162,0.005506
12,026_realmlp_v5,044_shared001_updated_seed2027_foldvariant,0.997433,0.816686,0.008925,0.035388,0.035833,0.031236,0.781200,0.004152,0.004597
13,042_realmlp_v5_seed2026_foldvariant,044_shared001_updated_seed2027_foldvariant,0.997586,0.816522,0.008565,0.035949,0.035833,0.031693,0.790581,0.004256,0.004140
14,038_gpu_logreg_add037,044_shared001_updated_seed2027_foldvariant,0.997696,0.892139,0.008839,0.035533,0.035833,0.031369,0.784298,0.004164,0.004464
15,036_gpu_logreg_add035,044_shared001_updated_seed2027_foldvariant,0.997710,0.892276,0.008820,0.035419,0.035833,0.031317,0.784221,0.004102,0.004515
16,044_shared001_updated_seed2027_foldvariant,049_gpu_logreg_add048,0.997714,0.893090,0.008679,0.035833,0.034452,0.030896,0.784398,0.004936,0.003556
17,044_shared001_updated_seed2027_foldvariant,045_gpu_logreg_add044,0.997719,0.892361,0.008721,0.035833,0.034525,0.030914,0.783735,0.004919,0.003611
18,040_gpu_logreg_add039,044_shared001_updated_seed2027_foldvariant,0.997731,0.893517,0.008676,0.034865,0.035833,0.031110,0.785833,0.003755,0.004723
19,034_gpu_logreg_default,044_shared001_updated_seed2027_foldvariant,0.997763,0.893069,0.008634,0.034731,0.035833,0.031066,0.786529,0.003665,0.004767
20,031_blend_add030,044_shared001_updated_seed2027_foldvariant,0.997853,0.858744,0.008487,0.033858,0.035833,0.030692,0.786996,0.003166,0.005141
21,033_blend_add032,044_shared001_updated_seed2027_foldvariant,0.997856,0.858801,0.008497,0.033838,0.035833,0.030677,0.786701,0.003161,0.005156
22,029_blend_add028,044_shared001_updated_seed2027_foldvariant,0.997897,0.859606,0.008387,0.034083,0.035833,0.030850,0.789670,0.003234,0.004983
23,024_seed_ensemble_blend,044_shared001_updated_seed2027_foldvariant,0.997940,0.891240,0.008589,0.033962,0.035833,0.030678,0.784272,0.003284,0.005155
24,036_blend_add035,044_shared001_updated_seed2027_foldvariant,0.998039,0.879508,0.008146,0.034264,0.035833,0.031065,0.795873,0.003199,0.004768
25,035_shared001_updated,044_shared001_updated_seed2027_foldvariant,0.998062,0.870384,0.008078,0.034984,0.035833,0.031446,0.798689,0.003539,0.004387
26,027_blend_add026,044_shared001_updated_seed2027_foldvariant,0.998152,0.864096,0.008073,0.034163,0.035833,0.031035,0.796568,0.003128,0.004798

,left,right,pearson_flat_proba,spearman_flat_proba,disagreement_rate,wrong_rate_left,wrong_rate_right,both_wrong_rate,error_overlap_jaccard,left_wrong_right_correct_rate,right_wrong_left_correct_rate
0,037_tabicl_v2,042_realmlp_v5_seed2026_foldvariant,0.982745,0.808008,0.029559,0.049665,0.035949,0.028224,0.491791,0.021441,0.007725
1,042_realmlp_v5_seed2026_foldvariant,047_xgb_multiclass_fe_objective_foldvariant,0.986131,0.752138,0.023714,0.035949,0.029753,0.021140,0.474386,0.014809,0.008614
2,030_ovr_xgb,042_realmlp_v5_seed2026_foldvariant,0.987105,0.749468,0.023140,0.028955,0.035949,0.021019,0.478944,0.007936,0.014930
3,032_ovr_tabm,042_realmlp_v5_seed2026_foldvariant,0.987614,0.759791,0.022775,0.029062,0.035949,0.021237,0.485142,0.007825,0.014712
4,042_realmlp_v5_seed2026_foldvariant,048_ovr_xgb_seed2027_fe_foldvariant,0.990047,0.755354,0.019548,0.035949,0.029287,0.022971,0.543480,0.012978,0.006317
5,018_xgb_shared003,042_realmlp_v5_seed2026_foldvariant,0.990835,0.795267,0.017691,0.033536,0.035949,0.026028,0.598924,0.007508,0.009921
6,028_cat_v3,042_realmlp_v5_seed2026_foldvariant,0.994809,0.806349,0.013633,0.035277,0.035949,0.028948,0.684706,0.006329,0.007001
7,039_cat_v3_seed2026_qbin_variant,042_realmlp_v5_seed2026_foldvariant,0.995016,0.804879,0.013191,0.035587,0.035949,0.029310,0.694122,0.006277,0.006639
8,015_realmlp_seed42,042_realmlp_v5_seed2026_foldvariant,0.996174,0.813865,0.011006,0.034388,0.035949,0.029778,0.734167,0.004611,0.006171
9,017_realmlp_bias,042_realmlp_v5_seed2026_foldvariant,0.996396,0.832858,0.010867,0.035542,0.035949,0.030420,0.740680,0.005122,0.005529
10,019_blend_best,042_realmlp_v5_seed2026_foldvariant,0.996426,0.819799,0.010605,0.032528,0.035949,0.029017,0.735361,0.003511,0.006932
11,020_blend_bias,042_realmlp_v5_seed2026_foldvariant,0.996972,0.845963,0.009750,0.034489,0.035949,0.030427,0.760476,0.004062,0.005522
12,035_shared001_updated,042_realmlp_v5_seed2026_foldvariant,0.997450,0.816058,0.008688,0.034984,0.035949,0.031217,0.786001,0.003767,0.004732
13,036_gpu_logreg_add035,042_realmlp_v5_seed2026_foldvariant,0.997532,0.864218,0.008771,0.035419,0.035949,0.031397,0.785501,0.004022,0.004552
14,042_realmlp_v5_seed2026_foldvariant,049_gpu_logreg_add048,0.997536,0.853026,0.008517,0.035949,0.034452,0.031042,0.788682,0.004907,0.003410
15,034_gpu_logreg_default,042_realmlp_v5_seed2026_foldvariant,0.997536,0.861834,0.008634,0.034731,0.035949,0.031118,0.786568,0.003613,0.004831
16,042_realmlp_v5_seed2026_foldvariant,045_gpu_logreg_add044,0.997539,0.857610,0.008610,0.035949,0.034525,0.031032,0.786756,0.004917,0.003494
17,038_gpu_logreg_add037,042_realmlp_v5_seed2026_foldvariant,0.997556,0.865760,0.008653,0.035533,0.035949,0.031518,0.788671,0.004015,0.004431
18,040_gpu_logreg_add039,042_realmlp_v5_seed2026_foldvariant,0.997561,0.859032,0.008543,0.034865,0.035949,0.031236,0.789234,0.003629,0.004713
19,042_realmlp_v5_seed2026_foldvariant,044_shared001_updated_seed2027_foldvariant,0.997586,0.816522,0.008565,0.035949,0.035833,0.031693,0.790581,0.004256,0.004140
20,024_seed_ensemble_blend,042_realmlp_v5_seed2026_foldvariant,0.997713,0.837943,0.008258,0.033962,0.035949,0.030893,0.791761,0.003069,0.005056
21,031_blend_add030,042_realmlp_v5_seed2026_foldvariant,0.997786,0.944782,0.008584,0.033858,0.035949,0.030704,0.785214,0.003154,0.005245
22,033_blend_add032,042_realmlp_v5_seed2026_foldvariant,0.997788,0.944717,0.008588,0.033838,0.035949,0.030692,0.785078,0.003145,0.005257
23,029_blend_add028,042_realmlp_v5_seed2026_foldvariant,0.997844,0.944824,0.008454,0.034083,0.035949,0.030877,0.788596,0.003206,0.005071
24,036_blend_add035,042_realmlp_v5_seed2026_foldvariant,0.997856,0.923022,0.008200,0.034264,0.035949,0.031092,0.794784,0.003171,0.004857
25,026_realmlp_v5,042_realmlp_v5_seed2026_foldvariant,0.998107,0.959599,0.007857,0.035388,0.035949,0.031816,0.805058,0.003572,0.004133
26,027_blend_add026,042_realmlp_v5_seed2026_foldvariant,0.998153,0.938075,0.007548,0.034163,0.035949,0.031349,0.808713,0.002815,0.004600

In [5]:
# ============================================================
# 4. Blend diagnostics
# ============================================================

blend_rows = {}
blend_probas = {}

def _weight_of(keys, weights, target_key):
    if weights is None or target_key not in keys:
        return None
    return float(dict(zip(keys, weights)).get(target_key, 0.0))

def record_blend(set_name, method, keys, oof_p, test_p=None, weights=None, extra=None):
    ev = evaluate_proba(y, oof_p, class_names)
    row = {
        "set_name": set_name,
        "method": method,
        "keys": ",".join(keys),
        "n_models": len(keys),
        "balanced_accuracy": ev["balanced_accuracy"],
        "weights_json": json.dumps({k: float(w) for k, w in zip(keys, weights)}, ensure_ascii=False) if weights is not None else None,
    }
    for short_name, target_key in TRACK_KEYS.items():
        row[f"includes_{short_name}"] = target_key in keys
        row[f"weight_{short_name}"] = _weight_of(keys, weights, target_key)
    row.update({k: v for k, v in ev.items() if k != "balanced_accuracy"})
    if extra:
        row.update(extra)
    blend_rows[(set_name, method)] = row
    if test_p is not None:
        blend_probas[(set_name, method)] = (normalize_rows(oof_p), normalize_rows(test_p))

for set_name, keys in BLEND_SETS.items():
    print("\n===", set_name, keys, "===")

    # 1) Simple average.
    avg_oof, avg_pred = average_proba(keys, oof, pred)
    record_blend(set_name, "avg", keys, avg_oof, avg_pred)

    # 2) Hill climb nonnegative raw probabilities.
    try:
        w, score, hist = hill_climb_weights(y, [oof[k] for k in keys])
        hc_oof = normalize_rows(sum(w[i] * oof[keys[i]] for i in range(len(keys))))
        hc_pred = normalize_rows(sum(w[i] * pred[keys[i]] for i in range(len(keys))))
        record_blend(set_name, "hc_nonnegative_raw", keys, hc_oof, hc_pred, weights=w, extra={"hc_score_internal": score, "hc_n_steps": len(hist)})
    except Exception as e:
        print(f"[WARN] HC failed: {set_name}: {e}")

    # 3) Nelder-Mead softmax weights.
    try:
        w, score, res = nm_softmax_weights(y, [oof[k] for k in keys])
        nm_oof = normalize_rows(sum(w[i] * oof[keys[i]] for i in range(len(keys))))
        nm_pred = normalize_rows(sum(w[i] * pred[keys[i]] for i in range(len(keys))))
        record_blend(set_name, "nm_softmax_raw", keys, nm_oof, nm_pred, weights=w, extra={"nm_score_internal": score, "nm_success": bool(res.success), "nm_message": str(res.message)})
    except Exception as e:
        print(f"[WARN] NM failed: {set_name}: {e}")

    # 4) In-sample meta models. Diagnostic only; do not use as final candidates.
    for mode in ["raw", "rank", "logit", "raw_logit", "raw_rank_logit"]:
        X_meta = build_meta_features(keys, oof, mode)
        X_test_meta = build_meta_features(keys, pred, mode)
        try:
            lr = LogisticRegression(C=0.05, multi_class="multinomial", solver="lbfgs", max_iter=2000, random_state=SEED)
            lr.fit(X_meta, y)
            record_blend(set_name, f"logreg_{mode}", keys, lr.predict_proba(X_meta), lr.predict_proba(X_test_meta), extra={"C": 0.05, "risk": "in_sample_meta_screening"})
        except Exception as e:
            print(f"[WARN] logreg failed: {set_name} {mode}: {e}")
        try:
            rc = RidgeClassifier(alpha=10.0, random_state=SEED)
            rc.fit(X_meta, y)
            record_blend(set_name, f"ridgeclf_{mode}", keys, softmax_np(rc.decision_function(X_meta)), softmax_np(rc.decision_function(X_test_meta)), extra={"alpha": 10.0, "risk": "in_sample_meta_screening"})
        except Exception as e:
            print(f"[WARN] ridgeclf failed: {set_name} {mode}: {e}")
        try:
            y_oh = onehot_y(y, n_classes)
            rr = Ridge(alpha=10.0, random_state=SEED)
            rr.fit(X_meta, y_oh)
            record_blend(set_name, f"ridge_reg_{mode}", keys, normalize_rows(np.clip(rr.predict(X_meta), 1e-12, None)), normalize_rows(np.clip(rr.predict(X_test_meta), 1e-12, None)), extra={"alpha": 10.0, "risk": "in_sample_meta_screening"})
        except Exception as e:
            print(f"[WARN] ridge_reg failed: {set_name} {mode}: {e}")
        try:
            y_oh = onehot_y(y, n_classes)
            oof_cols, test_cols = [], []
            for c in range(n_classes):
                en = ElasticNet(alpha=0.0005, l1_ratio=0.05, random_state=SEED, max_iter=2000)
                en.fit(X_meta, y_oh[:, c])
                oof_cols.append(en.predict(X_meta))
                test_cols.append(en.predict(X_test_meta))
            en_oof = normalize_rows(np.clip(np.vstack(oof_cols).T, 1e-12, None))
            en_pred = normalize_rows(np.clip(np.vstack(test_cols).T, 1e-12, None))
            record_blend(set_name, f"elasticnet_reg_{mode}", keys, en_oof, en_pred, extra={"alpha": 0.0005, "l1_ratio": 0.05, "risk": "in_sample_meta_screening"})
        except Exception as e:
            print(f"[WARN] elasticnet_reg failed: {set_name} {mode}: {e}")

blend_df = pd.DataFrame(list(blend_rows.values())).sort_values("balanced_accuracy", ascending=False).reset_index(drop=True)
display(blend_df.head(200))
blend_df.to_csv(OUTDIR / "blend_diagnostics.csv", index=False)

safe_methods = ["avg", "hc_nonnegative_raw", "nm_softmax_raw"]
safe_blend_df = blend_df[blend_df["method"].isin(safe_methods)].copy().sort_values("balanced_accuracy", ascending=False).reset_index(drop=True)
display(safe_blend_df.head(100))
safe_blend_df.to_csv(OUTDIR / "safe_blend_diagnostics.csv", index=False)

focus_blend_tables = {}
for short_name, target_key in TRACK_KEYS.items():
    include_col = f"includes_{short_name}"
    if include_col in safe_blend_df.columns:
        df = safe_blend_df[safe_blend_df[include_col]].copy().sort_values("balanced_accuracy", ascending=False).reset_index(drop=True)
        focus_blend_tables[short_name] = df
        display(df.head(80))
        df.to_csv(OUTDIR / f"safe_blend_diagnostics_focus_{short_name}.csv", index=False)

# Backward-compatible variables for easy notebook inspection.
focus_040_blend_df = focus_blend_tables.get("040", pd.DataFrame())
focus_039_blend_df = focus_blend_tables.get("039", pd.DataFrame())
focus_038_blend_df = focus_blend_tables.get("038", pd.DataFrame())
focus_037_blend_df = focus_blend_tables.get("037", pd.DataFrame())
focus_033_blend_df = focus_blend_tables.get("033", pd.DataFrame())

=== A_049_only ['049_gpu_logreg_add048'] ===

=== B_045_only ['045_gpu_logreg_add044'] ===

=== C_040_only ['040_gpu_logreg_add039'] ===

=== D_038_only ['038_gpu_logreg_add037'] ===

=== E_033_only ['033_blend_add032'] ===

=== F_048_only ['048_ovr_xgb_seed2027_fe_foldvariant'] ===

=== G_047_only ['047_xgb_multiclass_fe_objective_foldvariant'] ===

=== H_044_only ['044_shared001_updated_seed2027_foldvariant'] ===

=== I_042_only ['042_realmlp_v5_seed2026_foldvariant'] ===

=== J_039_only ['039_cat_v3_seed2026_qbin_variant'] ===

=== K_036_gpu_only ['036_gpu_logreg_add035'] ===

=== L_036_blend_only ['036_blend_add035'] ===

=== M_031_only ['031_blend_add030'] ===

=== N_049_040 ['049_gpu_logreg_add048', '040_gpu_logreg_add039'] ===

=== O_049_038 ['049_gpu_logreg_add048', '038_gpu_logreg_add037'] ===

=== P_049_033 ['049_gpu_logreg_add048', '033_blend_add032'] ===

=== Q_049_045 ['049_gpu_logreg_add048', '045_gpu_logreg_add044'] ===

=== R_049_040_038 ['049_gpu_logreg_add048', '040_gpu_logreg_add039', '038_gpu_logreg_add037'] ===

=== S_049_040_033 ['049_gpu_logreg_add048', '040_gpu_logreg_add039', '033_blend_add032'] ===

=== T_049_038_033 ['049_gpu_logreg_add048', '038_gpu_logreg_add037', '033_blend_add032'] ===

=== U_049_045_040 ['049_gpu_logreg_add048', '045_gpu_logreg_add044', '040_gpu_logreg_add039'] ===

=== V_049_045_038 ['049_gpu_logreg_add048', '045_gpu_logreg_add044', '038_gpu_logreg_add037'] ===

=== W_049_045_040_038 ['049_gpu_logreg_add048', '045_gpu_logreg_add044', '040_gpu_logreg_add039', '038_gpu_logreg_add037'] ===

=== X_049_045_040_038_033 ['049_gpu_logreg_add048', '045_gpu_logreg_add044', '040_gpu_logreg_add039', '038_gpu_logreg_add037', '033_blend_add032'] ===

=== Y_048_040 ['048_ovr_xgb_seed2027_fe_foldvariant', '040_gpu_logreg_add039'] ===

=== Z01_048_038 ['048_ovr_xgb_seed2027_fe_foldvariant', '038_gpu_logreg_add037'] ===

=== Z02_048_033 ['048_ovr_xgb_seed2027_fe_foldvariant', '033_blend_add032'] ===

=== Z03_048_045 ['048_ovr_xgb_seed2027_fe_foldvariant', '045_gpu_logreg_add044'] ===

=== Z04_048_049 ['048_ovr_xgb_seed2027_fe_foldvariant', '049_gpu_logreg_add048'] ===

=== Z05_048_049_040_038 ['048_ovr_xgb_seed2027_fe_foldvariant', '049_gpu_logreg_add048', '040_gpu_logreg_add039', '038_gpu_logreg_add037'] ===

=== Z06_048_049_045_040_038_033 ['048_ovr_xgb_seed2027_fe_foldvariant', '049_gpu_logreg_add048', '045_gpu_logreg_add044', '040_gpu_logreg_add039', '038_gpu_logreg_add037', '033_blend_add032'] ===

=== Z07_047_040 ['047_xgb_multiclass_fe_objective_foldvariant', '040_gpu_logreg_add039'] ===

=== Z08_047_038 ['047_xgb_multiclass_fe_objective_foldvariant', '038_gpu_logreg_add037'] ===

=== Z09_047_033 ['047_xgb_multiclass_fe_objective_foldvariant', '033_blend_add032'] ===

=== Z10_047_045 ['047_xgb_multiclass_fe_objective_foldvariant', '045_gpu_logreg_add044'] ===

=== Z11_047_049 ['047_xgb_multiclass_fe_objective_foldvariant', '049_gpu_logreg_add048'] ===

=== Z12_047_048_049 ['047_xgb_multiclass_fe_objective_foldvariant', '048_ovr_xgb_seed2027_fe_foldvariant', '049_gpu_logreg_add048'] ===

=== Z13_047_048_049_040_038 ['047_xgb_multiclass_fe_objective_foldvariant', '048_ovr_xgb_seed2027_fe_foldvariant', '049_gpu_logreg_add048', '040_gpu_logreg_add039', '038_gpu_logreg_add037'] ===

=== Z14_047_048_049_045_040_038_033 ['047_xgb_multiclass_fe_objective_foldvariant', '048_ovr_xgb_seed2027_fe_foldvariant', '049_gpu_logreg_add048', '045_gpu_logreg_add044', '040_gpu_logreg_add039', '038_gpu_logreg_add037', '033_blend_add032'] ===

=== Z15_045_040_038 ['045_gpu_logreg_add044', '040_gpu_logreg_add039', '038_gpu_logreg_add037'] ===

=== Z16_045_040_033_038 ['045_gpu_logreg_add044', '040_gpu_logreg_add039', '033_blend_add032', '038_gpu_logreg_add037'] ===

=== Z17_045_040_033_038_044_042 ['045_gpu_logreg_add044', '040_gpu_logreg_add039', '033_blend_add032', '038_gpu_logreg_add037', '044_shared001_updated_seed2027_foldvariant', '042_realmlp_v5_seed2026_foldvariant'] ===

=== Z18_041_old_best_like_plus_new049 ['040_gpu_logreg_add039', '033_blend_add032', '038_gpu_logreg_add037', '036_gpu_logreg_add035', '036_blend_add035', '039_cat_v3_seed2026_qbin_variant', '037_tabicl_v2', '044_shared001_updated_seed2027_foldvariant', '042_realmlp_v5_seed2026_foldvariant', '045_gpu_logreg_add044', '049_gpu_logreg_add048'] ===

=== Z19_040_033_038_036gpu_036blend_039_044_042_048_049 ['040_gpu_logreg_add039', '033_blend_add032', '038_gpu_logreg_add037', '036_gpu_logreg_add035', '036_blend_add035', '039_cat_v3_seed2026_qbin_variant', '044_shared001_updated_seed2027_foldvariant', '042_realmlp_v5_seed2026_foldvariant', '048_ovr_xgb_seed2027_fe_foldvariant', '049_gpu_logreg_add048'] ===

=== Z20_component_diagnostics_xgb_and_core ['027_blend_add026', '026_realmlp_v5', '028_cat_v3', '039_cat_v3_seed2026_qbin_variant', '030_ovr_xgb', '032_ovr_tabm', '035_shared001_updated', '037_tabicl_v2', '047_xgb_multiclass_fe_objective_foldvariant', '048_ovr_xgb_seed2027_fe_foldvariant', '049_gpu_logreg_add048'] ===

=== Z21_full_all_loaded ['015_realmlp_seed42', '017_realmlp_bias', '018_xgb_shared003', '019_blend_best', '020_blend_bias', '024_seed_ensemble_blend', '026_realmlp_v5', '027_blend_add026', '028_cat_v3', '029_blend_add028', '030_ovr_xgb', '031_blend_add030', '032_ovr_tabm', '033_blend_add032', '034_gpu_logreg_default', '035_shared001_updated', '036_gpu_logreg_add035', '036_blend_add035', '037_tabicl_v2', '038_gpu_logreg_add037', '039_cat_v3_seed2026_qbin_variant', '040_gpu_logreg_add039', '042_realmlp_v5_seed2026_foldvariant', '044_shared001_updated_seed2027_foldvariant', '045_gpu_logreg_add044', '047_xgb_multiclass_fe_objective_foldvariant', '048_ovr_xgb_seed2027_fe_foldvariant', '049_gpu_logreg_add048'] ===

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.0,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,X_049_045_040_038_033,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970264,"{""049_gpu_logreg_add048"": 0.19068397962763695,...",True,0.190684,False,NaN,...,0.973925,0.970264,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,W_049_045_040_038,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970264,"{""049_gpu_logreg_add048"": 0.18640369818787422,...",True,0.186404,False,NaN,...,0.973901,0.970264,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,W_049_045_040_038,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970255,"{""049_gpu_logreg_add048"": 0.2388205117412317, ...",True,0.238821,False,NaN,...,0.973829,NaN,NaN,0.970255,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
4,Z15_045_040_038,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970253,"{""045_gpu_logreg_add044"": 0.5144616346780971, ...",False,NaN,False,NaN,...,0.973937,0.970253,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,K_036_gpu_only,ridge_reg_raw_logit,036_gpu_logreg_add035,1,0.969234,None,False,NaN,False,NaN,...,0.964267,NaN,NaN,NaN,NaN,NaN,NaN,in_sample_meta_screening,10.0000,NaN
196,N_049_040,elasticnet_reg_raw_logit,"049_gpu_logreg_add048,040_gpu_logreg_add039",2,0.969229,None,True,NaN,False,NaN,...,0.964400,NaN,NaN,NaN,NaN,NaN,NaN,in_sample_meta_screening,0.0005,0.05
197,K_036_gpu_only,ridge_reg_raw_rank_logit,036_gpu_logreg_add035,1,0.969211,None,False,NaN,False,NaN,...,0.964073,NaN,NaN,NaN,NaN,NaN,NaN,in_sample_meta_screening,10.0000,NaN
198,K_036_gpu_only,ridgeclf_raw_rank_logit,036_gpu_logreg_add035,1,0.969211,None,False,NaN,False,NaN,...,0.964073,NaN,NaN,NaN,NaN,NaN,NaN,in_sample_meta_screening,10.0000,NaN
199,U_049_045_040,elasticnet_reg_raw_rank_logit,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",3,0.969209,None,True,NaN,False,NaN,...,0.964097,NaN,NaN,NaN,NaN,NaN,NaN,in_sample_meta_screening,0.0005,0.05

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,X_049_045_040_038_033,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970264,"{""049_gpu_logreg_add048"": 0.19068397962763695,...",True,0.190684,False,NaN,...,0.973925,0.970264,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,W_049_045_040_038,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970264,"{""049_gpu_logreg_add048"": 0.18640369818787422,...",True,0.186404,False,NaN,...,0.973901,0.970264,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,W_049_045_040_038,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970255,"{""049_gpu_logreg_add048"": 0.2388205117412317, ...",True,0.238821,False,NaN,...,0.973829,NaN,NaN,0.970255,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
4,Z15_045_040_038,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970253,"{""045_gpu_logreg_add044"": 0.5144616346780971, ...",False,NaN,False,NaN,...,0.973937,0.970253,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Z02_048_033,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,033_blend_...",2,0.970040,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 1.8166...",False,NaN,True,0.000018,...,0.972571,NaN,NaN,0.970040,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
96,Z02_048_033,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,033_blend_...",2,0.970040,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0, ""...",False,NaN,True,0.000000,...,0.972571,0.970040,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
98,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,M_031_only,avg,031_blend_add030,1,0.970033,None,False,NaN,False,NaN,...,0.972571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.0,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,X_049_045_040_038_033,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970264,"{""049_gpu_logreg_add048"": 0.19068397962763695,...",True,0.190684,False,NaN,...,0.973925,0.970264,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,W_049_045_040_038,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970264,"{""049_gpu_logreg_add048"": 0.18640369818787422,...",True,0.186404,False,NaN,...,0.973901,0.970264,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,W_049_045_040_038,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970255,"{""049_gpu_logreg_add048"": 0.2388205117412317, ...",True,0.238821,False,NaN,...,0.973829,NaN,NaN,0.970255,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
4,Z19_040_033_038_036gpu_036blend_039_044_042_04...,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970253,"{""040_gpu_logreg_add039"": 0.08407327347212103,...",True,0.365774,True,0.0,...,0.973551,0.970253,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,Z13_047_048_049_040_038,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.969089,None,True,NaN,True,NaN,...,0.964992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Z20_component_diagnostics_xgb_and_core,avg,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.968865,None,True,NaN,True,NaN,...,0.964376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Z04_048_049,avg,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",2,0.968481,None,True,NaN,True,NaN,...,0.962393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Z11_047_049,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.967681,None,True,NaN,False,NaN,...,0.958827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Z12_047_048_049,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",3,0.966704,None,True,NaN,True,NaN,...,0.955067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z19_040_033_038_036gpu_036blend_039_044_042_04...,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970253,"{""040_gpu_logreg_add039"": 0.08407327347212103,...",True,0.365774,True,0.000000,...,0.973551,0.970253,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z20_component_diagnostics_xgb_and_core,hc_nonnegative_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.970250,"{""027_blend_add026"": 0.09266904710786944, ""026...",True,0.510185,True,0.000000,...,0.973079,0.970250,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Z03_048_045,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,045_gpu_lo...",2,0.970245,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 1.9751...",False,NaN,True,0.000020,...,0.973490,NaN,NaN,0.970245,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
4,Z03_048_045,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,045_gpu_lo...",2,0.970245,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0, ""...",False,NaN,True,0.000000,...,0.973490,0.970245,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Z14_047_048_049_045_040_038_033,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.970220,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.233447,True,0.083548,...,0.972366,0.970220,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Z13_047_048_049_040_038,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.970213,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.322251,True,0.000000,...,0.973478,0.970213,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Z06_048_049_045_040_038_033,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.970212,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0851...",True,0.230418,True,0.085110,...,0.972318,0.970212,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Z04_048_049,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",2,0.970206,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0013...",True,0.998695,True,0.001305,...,0.973115,NaN,NaN,0.970206,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
9,Y_048_040,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,040_gpu_lo...",2,0.970204,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0002...",False,NaN,True,0.000278,...,0.974240,NaN,NaN,0.970204,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
10,Z12_047_048_049,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",3,0.970204,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.999434,True,0.000123,...,0.973115,NaN,NaN,0.970204,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
11,Y_048_040,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,040_gpu_lo...",2,0.970202,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0, ""...",False,NaN,True,0.000000,...,0.974240,0.970202,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Z05_048_049_040_038,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",4,0.970198,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0194...",True,0.404311,True,0.019421,...,0.973551,0.970198,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Z12_047_048_049,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",3,0.970196,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,1.000000,True,0.000000,...,0.973115,0.970196,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Z04_048_049,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",2,0.970196,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0, ""...",True,1.000000,True,0.000000,...,0.973115,0.970196,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Z05_048_049_040_038,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",4,0.970188,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0912...",True,0.339552,True,0.091253,...,0.972451,NaN,NaN,0.970188,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
16,Z13_047_048_049_040_038,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.970177,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.038111,True,0.028387,...,0.973732,NaN,NaN,0.970177,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
17,Z01_048_038,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,038_gpu_lo...",2,0.970135,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 1.9751...",False,NaN,True,0.000020,...,0.974336,NaN,NaN,0.970135,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
18,Z19_040_033_038_036gpu_036blend_039_044_042_04...,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970086,"{""040_gpu_logreg_add039"": 0.16145611392049694,...",True,0.111405,True,0.076546,...,0.972366,NaN,NaN,0.970086,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
19,Z01_048_038,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,038_gpu_lo...",2,0.970055,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.1423...",False,NaN,True,0.142302,...,0.972052,0.970055,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Z19_040_033_038_036gpu_036blend_039_044_042_04...,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970048,None,True,NaN,True,NaN,...,0.971894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Z02_048_033,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,033_blend_...",2,0.970040,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 1.8166...",False,NaN,True,0.000018,...,0.972571,NaN,NaN,0.970040,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
22,Z02_048_033,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,033_blend_...",2,0.970040,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0, ""...",False,NaN,True,0.000000,...,0.972571,0.970040,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Z06_048_049_045_040_038_033,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.970012,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.1660...",True,0.149002,True,0.166031,...,0.970758,NaN,NaN,0.970012,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
24,Z06_048_049_045_040_038_033,avg,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.969984,None,True,NaN,True,NaN,...,0.970734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
26,Z05_048_049_040_038,avg,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",4,0.969758,None,True,NaN,True,NaN,...,0.969392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Z14_047_048_049_045_040_038_033,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969607,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.107023,True,0.131908,...,0.968365,NaN,NaN,0.969607,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
29,Z14_047_048_049_045_040_038_033,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969557,None,True,NaN,True,NaN,...,0.967784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Z20_component_diagnostics_xgb_and_core,nm_softmax_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.969527,"{""027_blend_add026"": 0.49613240081968846, ""026...",True,0.042539,True,0.058864,...,0.968232,NaN,NaN,0.969527,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
31,Z13_047_048_049_040_038,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.969089,None,True,NaN,True,NaN,...,0.964992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Z20_component_diagnostics_xgb_and_core,avg,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.968865,None,True,NaN,True,NaN,...,0.964376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Z01_048_038,avg,"048_ovr_xgb_seed2027_fe_foldvariant,038_gpu_lo...",2,0.968738,None,False,NaN,True,NaN,...,0.963541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Y_048_040,avg,"048_ovr_xgb_seed2027_fe_foldvariant,040_gpu_lo...",2,0.968633,None,False,NaN,True,NaN,...,0.963263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Z03_048_045,avg,"048_ovr_xgb_seed2027_fe_foldvariant,045_gpu_lo...",2,0.968591,None,False,NaN,True,NaN,...,0.962683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Z04_048_049,avg,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",2,0.968481,None,True,NaN,True,NaN,...,0.962393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Z02_048_033,avg,"048_ovr_xgb_seed2027_fe_foldvariant,033_blend_...",2,0.968327,None,False,NaN,True,NaN,...,0.961486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Z12_047_048_049,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",3,0.966704,None,True,NaN,True,NaN,...,0.955067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,F_048_only,hc_nonnegative_raw,048_ovr_xgb_seed2027_fe_foldvariant,1,0.963697,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 1.0}",False,NaN,True,1.000000,...,0.946001,0.963697,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,F_048_only,avg,048_ovr_xgb_seed2027_fe_foldvariant,1,0.963697,None,False,NaN,True,NaN,...,0.946001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,F_048_only,nm_softmax_raw,048_ovr_xgb_seed2027_fe_foldvariant,1,0.963697,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 1.0}",False,NaN,True,1.000000,...,0.946001,NaN,NaN,0.963697,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z20_component_diagnostics_xgb_and_core,hc_nonnegative_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.970250,"{""027_blend_add026"": 0.09266904710786944, ""026...",True,0.510185,True,0.000000,...,0.973079,0.970250,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z10_047_045,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.970249,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.973490,NaN,NaN,0.970249,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
3,Z10_047_045,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.970245,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.973490,0.970245,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Z14_047_048_049_045_040_038_033,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.970220,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.233447,True,0.083548,...,0.972366,0.970220,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Z13_047_048_049_040_038,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.970213,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.322251,True,0.000000,...,0.973478,0.970213,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Z12_047_048_049,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",3,0.970204,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.999434,True,0.000123,...,0.973115,NaN,NaN,0.970204,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
7,Z11_047_049,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.970203,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.999583,False,NaN,...,0.973115,NaN,NaN,0.970203,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
8,Z07_047_040,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.970203,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.974240,NaN,NaN,0.970203,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
9,Z07_047_040,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.970202,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.974240,0.970202,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Z11_047_049,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.970196,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,1.000000,False,NaN,...,0.973115,0.970196,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Z12_047_048_049,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",3,0.970196,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,1.000000,True,0.000000,...,0.973115,0.970196,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Z13_047_048_049_040_038,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.970177,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.038111,True,0.028387,...,0.973732,NaN,NaN,0.970177,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
13,Z08_047_038,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.970135,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.974336,0.970135,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Z08_047_038,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.970135,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.974336,NaN,NaN,0.970135,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
15,Z09_047_033,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.970040,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.972571,0.970040,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Z09_047_033,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.970040,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.972571,NaN,NaN,0.970040,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
17,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
18,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Z14_047_048_049_045_040_038_033,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969607,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.107023,True,0.131908,...,0.968365,NaN,NaN,0.969607,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
20,Z14_047_048_049_045_040_038_033,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969557,None,True,NaN,True,NaN,...,0.967784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Z20_component_diagnostics_xgb_and_core,nm_softmax_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.969527,"{""027_blend_add026"": 0.49613240081968846, ""026...",True,0.042539,True,0.058864,...,0.968232,NaN,NaN,0.969527,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
22,Z13_047_048_049_040_038,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.969089,None,True,NaN,True,NaN,...,0.964992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Z20_component_diagnostics_xgb_and_core,avg,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.968865,None,True,NaN,True,NaN,...,0.964376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Z08_047_038,avg,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.967877,None,False,NaN,False,NaN,...,0.959625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Z07_047_040,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.967796,None,False,NaN,False,NaN,...,0.959504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Z10_047_045,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.967733,None,False,NaN,False,NaN,...,0.959032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Z11_047_049,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.967681,None,True,NaN,False,NaN,...,0.958827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Z09_047_033,avg,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.967331,None,False,NaN,False,NaN,...,0.957437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Z12_047_048_049,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",3,0.966704,None,True,NaN,True,NaN,...,0.955067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,G_047_only,avg,047_xgb_multiclass_fe_objective_foldvariant,1,0.959687,None,False,NaN,False,NaN,...,0.934674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,G_047_only,nm_softmax_raw,047_xgb_multiclass_fe_objective_foldvariant,1,0.959687,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.934674,NaN,NaN,0.959687,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
32,G_047_only,hc_nonnegative_raw,047_xgb_multiclass_fe_objective_foldvariant,1,0.959687,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.934674,0.959687,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,X_049_045_040_038_033,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970264,"{""049_gpu_logreg_add048"": 0.19068397962763695,...",True,0.190684,False,NaN,...,0.973925,0.970264,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,W_049_045_040_038,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970264,"{""049_gpu_logreg_add048"": 0.18640369818787422,...",True,0.186404,False,NaN,...,0.973901,0.970264,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,W_049_045_040_038,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970255,"{""049_gpu_logreg_add048"": 0.2388205117412317, ...",True,0.238821,False,NaN,...,0.973829,NaN,NaN,0.970255,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
4,Z15_045_040_038,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970253,"{""045_gpu_logreg_add044"": 0.5144616346780971, ...",False,NaN,False,NaN,...,0.973937,0.970253,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Z16_045_040_033_038,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970252,"{""045_gpu_logreg_add044"": 0.32558062578057534,...",False,NaN,False,NaN,...,0.974022,0.970252,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Z10_047_045,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.970249,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.973490,NaN,NaN,0.970249,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
7,Z17_045_040_033_038_044_042,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970246,"{""045_gpu_logreg_add044"": 0.1953383167534802, ...",False,NaN,False,NaN,...,0.974252,0.970246,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Z10_047_045,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.970245,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.973490,0.970245,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,B_045_only,avg,045_gpu_logreg_add044,1,0.970245,None,False,NaN,False,NaN,...,0.973490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,B_045_only,nm_softmax_raw,045_gpu_logreg_add044,1,0.970245,"{""045_gpu_logreg_add044"": 1.0}",False,NaN,False,NaN,...,0.973490,NaN,NaN,0.970245,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
11,Z03_048_045,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,045_gpu_lo...",2,0.970245,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 1.9751...",False,NaN,True,0.000020,...,0.973490,NaN,NaN,0.970245,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
12,B_045_only,hc_nonnegative_raw,045_gpu_logreg_add044,1,0.970245,"{""045_gpu_logreg_add044"": 1.0}",False,NaN,False,NaN,...,0.973490,0.970245,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Z03_048_045,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,045_gpu_lo...",2,0.970245,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0, ""...",False,NaN,True,0.000000,...,0.973490,0.970245,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,W_049_045_040_038,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970231,None,True,NaN,False,NaN,...,0.973841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,U_049_045_040,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",3,0.970230,"{""049_gpu_logreg_add048"": 0.23659223446917643,...",True,0.236592,False,NaN,...,0.973671,0.970230,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,V_049_045_038,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,03...",3,0.970223,"{""049_gpu_logreg_add048"": 0.2628329356047728, ...",True,0.262833,False,NaN,...,0.973804,0.970223,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,U_049_045_040,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",3,0.970222,"{""049_gpu_logreg_add048"": 0.2471956306120028, ...",True,0.247196,False,NaN,...,0.973708,NaN,NaN,0.970222,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
18,Z14_047_048_049_045_040_038_033,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.970220,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.233447,True,0.083548,...,0.972366,0.970220,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,X_049_045_040_038_033,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970219,"{""049_gpu_logreg_add048"": 0.21931056260523232,...",True,0.219311,False,NaN,...,0.973804,NaN,NaN,0.970219,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
20,Z15_045_040_038,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970218,"{""045_gpu_logreg_add044"": 0.48768090588066687,...",False,NaN,False,NaN,...,0.973937,NaN,NaN,0.970218,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
21,Q_049_045,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044",2,0.970213,"{""049_gpu_logreg_add048"": 0.4357298474945534, ...",True,0.435730,False,NaN,...,0.973333,0.970213,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Q_049_045,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044",2,0.970213,"{""049_gpu_logreg_add048"": 0.43696890198323834,...",True,0.436969,False,NaN,...,0.973333,NaN,NaN,0.970213,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
23,Z06_048_049_045_040_038_033,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.970212,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0851...",True,0.230418,True,0.085110,...,0.972318,0.970212,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Z18_041_old_best_like_plus_new049,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970211,"{""040_gpu_logreg_add039"": 0.14146687686396553,...",True,0.136492,False,NaN,...,0.973551,0.970211,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,V_049_045_038,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,03...",3,0.970209,"{""049_gpu_logreg_add048"": 0.24629912303424575,...",True,0.246299,False,NaN,...,0.973792,NaN,NaN,0.970209,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
26,Z15_045_040_038,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970207,None,False,NaN,False,NaN,...,0.974046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Q_049_045,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044",2,0.970202,None,True,NaN,False,NaN,...,0.973309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,U_049_045_040,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",3,0.970199,None,True,NaN,False,NaN,...,0.973587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,V_049_045_038,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,03...",3,0.970186,None,True,NaN,False,NaN,...,0.973647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Z16_045_040_033_038,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970164,"{""045_gpu_logreg_add044"": 0.25, ""040_gpu_logre...",False,NaN,False,NaN,...,0.973611,NaN,NaN,0.970164,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
31,Z16_045_040_033_038,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970164,None,False,NaN,False,NaN,...,0.973611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Z17_045_040_033_038_044_042,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970145,"{""045_gpu_logreg_add044"": 0.19161509400530638,...",False,NaN,False,NaN,...,0.973611,NaN,NaN,0.970145,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
33,X_049_045_040_038_033,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970145,None,True,NaN,False,NaN,...,0.973454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Z17_045_040_033_038_044_042,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970117,None,False,NaN,False,NaN,...,0.973732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
36,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Z06_048_049_045_040_038_033,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.970012,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.1660...",True,0.149002,True,0.166031,...,0.970758,NaN,NaN,0.970012,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
38,Z06_048_049_045_040_038_033,avg,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.969984,None,True,NaN,True,NaN,...,0.970734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
40,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Z14_047_048_049_045_040_038_033,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969607,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.107023,True,0.131908,...,0.968365,NaN,NaN,0.969607,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
42,Z14_047_048_049_045_040_038_033,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969557,None,True,NaN,True,NaN,...,0.967784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Z03_048_045,avg,"048_ovr_xgb_seed2027_fe_foldvariant,045_gpu_lo...",2,0.968591,None,False,NaN,True,NaN,...,0.962683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Z10_047_045,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.967733,None,False,NaN,False,NaN,...,0.959032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z19_040_033_038_036gpu_036blend_039_044_042_04...,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970253,"{""040_gpu_logreg_add039"": 0.08407327347212103,...",True,0.365774,True,0.000000,...,0.973551,0.970253,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z17_045_040_033_038_044_042,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970246,"{""045_gpu_logreg_add044"": 0.1953383167534802, ...",False,NaN,False,NaN,...,0.974252,0.970246,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Z18_041_old_best_like_plus_new049,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970211,"{""040_gpu_logreg_add039"": 0.14146687686396553,...",True,0.136492,False,NaN,...,0.973551,0.970211,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Z17_045_040_033_038_044_042,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970145,"{""045_gpu_logreg_add044"": 0.19161509400530638,...",False,NaN,False,NaN,...,0.973611,NaN,NaN,0.970145,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
5,Z17_045_040_033_038_044_042,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970117,None,False,NaN,False,NaN,...,0.973732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Z19_040_033_038_036gpu_036blend_039_044_042_04...,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970086,"{""040_gpu_logreg_add039"": 0.16145611392049694,...",True,0.111405,True,0.076546,...,0.972366,NaN,NaN,0.970086,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
7,Z19_040_033_038_036gpu_036blend_039_044_042_04...,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970048,None,True,NaN,True,NaN,...,0.971894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
9,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
11,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,H_044_only,avg,044_shared001_updated_seed2027_foldvariant,1,0.968604,None,False,NaN,False,NaN,...,0.970976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,H_044_only,hc_nonnegative_raw,044_shared001_updated_seed2027_foldvariant,1,0.968604,"{""044_shared001_updated_seed2027_foldvariant"":...",False,NaN,False,NaN,...,0.970976,0.968604,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,H_044_only,nm_softmax_raw,044_shared001_updated_seed2027_foldvariant,1,0.968604,"{""044_shared001_updated_seed2027_foldvariant"":...",False,NaN,False,NaN,...,0.970976,NaN,NaN,0.968604,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z19_040_033_038_036gpu_036blend_039_044_042_04...,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970253,"{""040_gpu_logreg_add039"": 0.08407327347212103,...",True,0.365774,True,0.000000,...,0.973551,0.970253,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z17_045_040_033_038_044_042,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970246,"{""045_gpu_logreg_add044"": 0.1953383167534802, ...",False,NaN,False,NaN,...,0.974252,0.970246,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Z18_041_old_best_like_plus_new049,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970211,"{""040_gpu_logreg_add039"": 0.14146687686396553,...",True,0.136492,False,NaN,...,0.973551,0.970211,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Z17_045_040_033_038_044_042,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970145,"{""045_gpu_logreg_add044"": 0.19161509400530638,...",False,NaN,False,NaN,...,0.973611,NaN,NaN,0.970145,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
5,Z17_045_040_033_038_044_042,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970117,None,False,NaN,False,NaN,...,0.973732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Z19_040_033_038_036gpu_036blend_039_044_042_04...,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970086,"{""040_gpu_logreg_add039"": 0.16145611392049694,...",True,0.111405,True,0.076546,...,0.972366,NaN,NaN,0.970086,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
7,Z19_040_033_038_036gpu_036blend_039_044_042_04...,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970048,None,True,NaN,True,NaN,...,0.971894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
9,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
11,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,I_042_only,hc_nonnegative_raw,042_realmlp_v5_seed2026_foldvariant,1,0.968948,"{""042_realmlp_v5_seed2026_foldvariant"": 1.0}",False,NaN,False,NaN,...,0.971834,0.968948,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,I_042_only,avg,042_realmlp_v5_seed2026_foldvariant,1,0.968948,None,False,NaN,False,NaN,...,0.971834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,I_042_only,nm_softmax_raw,042_realmlp_v5_seed2026_foldvariant,1,0.968948,"{""042_realmlp_v5_seed2026_foldvariant"": 1.0}",False,NaN,False,NaN,...,0.971834,NaN,NaN,0.968948,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,X_049_045_040_038_033,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970264,"{""049_gpu_logreg_add048"": 0.19068397962763695,...",True,0.190684,False,NaN,...,0.973925,0.970264,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,W_049_045_040_038,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970264,"{""049_gpu_logreg_add048"": 0.18640369818787422,...",True,0.186404,False,NaN,...,0.973901,0.970264,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,W_049_045_040_038,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970255,"{""049_gpu_logreg_add048"": 0.2388205117412317, ...",True,0.238821,False,NaN,...,0.973829,NaN,NaN,0.970255,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
4,Z15_045_040_038,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970253,"{""045_gpu_logreg_add044"": 0.5144616346780971, ...",False,NaN,False,NaN,...,0.973937,0.970253,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Z19_040_033_038_036gpu_036blend_039_044_042_04...,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970253,"{""040_gpu_logreg_add039"": 0.08407327347212103,...",True,0.365774,True,0.000000,...,0.973551,0.970253,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Z16_045_040_033_038,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970252,"{""045_gpu_logreg_add044"": 0.32558062578057534,...",False,NaN,False,NaN,...,0.974022,0.970252,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Z17_045_040_033_038_044_042,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970246,"{""045_gpu_logreg_add044"": 0.1953383167534802, ...",False,NaN,False,NaN,...,0.974252,0.970246,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,W_049_045_040_038,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970231,None,True,NaN,False,NaN,...,0.973841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,U_049_045_040,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",3,0.970230,"{""049_gpu_logreg_add048"": 0.23659223446917643,...",True,0.236592,False,NaN,...,0.973671,0.970230,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,S_049_040_033,hc_nonnegative_raw,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970222,"{""049_gpu_logreg_add048"": 0.4105671033185198, ...",True,0.410567,False,NaN,...,0.973176,0.970222,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,U_049_045_040,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",3,0.970222,"{""049_gpu_logreg_add048"": 0.2471956306120028, ...",True,0.247196,False,NaN,...,0.973708,NaN,NaN,0.970222,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
12,Z14_047_048_049_045_040_038_033,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.970220,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.233447,True,0.083548,...,0.972366,0.970220,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,X_049_045_040_038_033,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970219,"{""049_gpu_logreg_add048"": 0.21931056260523232,...",True,0.219311,False,NaN,...,0.973804,NaN,NaN,0.970219,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
14,Z15_045_040_038,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970218,"{""045_gpu_logreg_add044"": 0.48768090588066687,...",False,NaN,False,NaN,...,0.973937,NaN,NaN,0.970218,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
15,Z13_047_048_049_040_038,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.970213,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.322251,True,0.000000,...,0.973478,0.970213,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Z06_048_049_045_040_038_033,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.970212,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0851...",True,0.230418,True,0.085110,...,0.972318,0.970212,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Z18_041_old_best_like_plus_new049,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970211,"{""040_gpu_logreg_add039"": 0.14146687686396553,...",True,0.136492,False,NaN,...,0.973551,0.970211,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Z15_045_040_038,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970207,None,False,NaN,False,NaN,...,0.974046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,R_049_040_038,hc_nonnegative_raw,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970205,"{""049_gpu_logreg_add048"": 0.2545167072366898, ...",True,0.254517,False,NaN,...,0.973974,0.970205,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Y_048_040,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,040_gpu_lo...",2,0.970204,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0002...",False,NaN,True,0.000278,...,0.974240,NaN,NaN,0.970204,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
21,Z07_047_040,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.970203,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.974240,NaN,NaN,0.970203,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
22,C_040_only,nm_softmax_raw,040_gpu_logreg_add039,1,0.970202,"{""040_gpu_logreg_add039"": 1.0}",False,NaN,False,NaN,...,0.974240,NaN,NaN,0.970202,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
23,Z07_047_040,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.970202,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.974240,0.970202,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,C_040_only,hc_nonnegative_raw,040_gpu_logreg_add039,1,0.970202,"{""040_gpu_logreg_add039"": 1.0}",False,NaN,False,NaN,...,0.974240,0.970202,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,C_040_only,avg,040_gpu_logreg_add039,1,0.970202,None,False,NaN,False,NaN,...,0.974240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Y_048_040,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,040_gpu_lo...",2,0.970202,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0, ""...",False,NaN,True,0.000000,...,0.974240,0.970202,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,U_049_045_040,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",3,0.970199,None,True,NaN,False,NaN,...,0.973587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Z05_048_049_040_038,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",4,0.970198,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0194...",True,0.404311,True,0.019421,...,0.973551,0.970198,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,S_049_040_033,nm_softmax_raw,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970197,"{""049_gpu_logreg_add048"": 0.35748134880005844,...",True,0.357481,False,NaN,...,0.973248,NaN,NaN,0.970197,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
30,N_049_040,hc_nonnegative_raw,"049_gpu_logreg_add048,040_gpu_logreg_add039",2,0.970189,"{""049_gpu_logreg_add048"": 0.43174738721097966,...",True,0.431747,False,NaN,...,0.973744,0.970189,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Z05_048_049_040_038,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",4,0.970188,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0912...",True,0.339552,True,0.091253,...,0.972451,NaN,NaN,0.970188,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
32,Z13_047_048_049_040_038,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.970177,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.038111,True,0.028387,...,0.973732,NaN,NaN,0.970177,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
33,N_049_040,nm_softmax_raw,"049_gpu_logreg_add048,040_gpu_logreg_add039",2,0.970172,"{""049_gpu_logreg_add048"": 0.4821102113387022, ...",True,0.482110,False,NaN,...,0.973671,NaN,NaN,0.970172,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
34,R_049_040_038,nm_softmax_raw,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970169,"{""049_gpu_logreg_add048"": 0.3530603097122465, ...",True,0.353060,False,NaN,...,0.973937,NaN,NaN,0.970169,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
35,N_049_040,avg,"049_gpu_logreg_add048,040_gpu_logreg_add039",2,0.970168,None,True,NaN,False,NaN,...,0.973635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Z16_045_040_033_038,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970164,"{""045_gpu_logreg_add044"": 0.25, ""040_gpu_logre...",False,NaN,False,NaN,...,0.973611,NaN,NaN,0.970164,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
37,Z16_045_040_033_038,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970164,None,False,NaN,False,NaN,...,0.973611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,R_049_040_038,avg,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970162,None,True,NaN,False,NaN,...,0.973913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,S_049_040_033,avg,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970161,None,True,NaN,False,NaN,...,0.973285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Z17_045_040_033_038_044_042,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970145,"{""045_gpu_logreg_add044"": 0.19161509400530638,...",False,NaN,False,NaN,...,0.973611,NaN,NaN,0.970145,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
41,X_049_045_040_038_033,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970145,None,True,NaN,False,NaN,...,0.973454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Z17_045_040_033_038_044_042,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970117,None,False,NaN,False,NaN,...,0.973732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Z19_040_033_038_036gpu_036blend_039_044_042_04...,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970086,"{""040_gpu_logreg_add039"": 0.16145611392049694,...",True,0.111405,True,0.076546,...,0.972366,NaN,NaN,0.970086,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
44,Z19_040_033_038_036gpu_036blend_039_044_042_04...,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970048,None,True,NaN,True,NaN,...,0.971894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
46,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Z06_048_049_045_040_038_033,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.970012,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.1660...",True,0.149002,True,0.166031,...,0.970758,NaN,NaN,0.970012,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
48,Z06_048_049_045_040_038_033,avg,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.969984,None,True,NaN,True,NaN,...,0.970734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
50,Z05_048_049_040_038,avg,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",4,0.969758,None,True,NaN,True,NaN,...,0.969392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Z14_047_048_049_045_040_038_033,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969607,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.107023,True,0.131908,...,0.968365,NaN,NaN,0.969607,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
53,Z14_047_048_049_045_040_038_033,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969557,None,True,NaN,True,NaN,...,0.967784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Z13_047_048_049_040_038,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.969089,None,True,NaN,True,NaN,...,0.964992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Y_048_040,avg,"048_ovr_xgb_seed2027_fe_foldvariant,040_gpu_lo...",2,0.968633,None,False,NaN,True,NaN,...,0.963263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Z07_047_040,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",2,0.967796,None,False,NaN,False,NaN,...,0.959504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z19_040_033_038_036gpu_036blend_039_044_042_04...,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970253,"{""040_gpu_logreg_add039"": 0.08407327347212103,...",True,0.365774,True,0.000000,...,0.973551,0.970253,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z20_component_diagnostics_xgb_and_core,hc_nonnegative_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.970250,"{""027_blend_add026"": 0.09266904710786944, ""026...",True,0.510185,True,0.000000,...,0.973079,0.970250,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Z18_041_old_best_like_plus_new049,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970211,"{""040_gpu_logreg_add039"": 0.14146687686396553,...",True,0.136492,False,NaN,...,0.973551,0.970211,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Z19_040_033_038_036gpu_036blend_039_044_042_04...,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970086,"{""040_gpu_logreg_add039"": 0.16145611392049694,...",True,0.111405,True,0.076546,...,0.972366,NaN,NaN,0.970086,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
5,Z19_040_033_038_036gpu_036blend_039_044_042_04...,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970048,None,True,NaN,True,NaN,...,0.971894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
7,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
9,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Z20_component_diagnostics_xgb_and_core,nm_softmax_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.969527,"{""027_blend_add026"": 0.49613240081968846, ""026...",True,0.042539,True,0.058864,...,0.968232,NaN,NaN,0.969527,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
11,Z20_component_diagnostics_xgb_and_core,avg,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.968865,None,True,NaN,True,NaN,...,0.964376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,J_039_only,hc_nonnegative_raw,039_cat_v3_seed2026_qbin_variant,1,0.968705,"{""039_cat_v3_seed2026_qbin_variant"": 1.0}",False,NaN,False,NaN,...,0.971616,0.968705,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,J_039_only,avg,039_cat_v3_seed2026_qbin_variant,1,0.968705,None,False,NaN,False,NaN,...,0.971616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,J_039_only,nm_softmax_raw,039_cat_v3_seed2026_qbin_variant,1,0.968705,"{""039_cat_v3_seed2026_qbin_variant"": 1.0}",False,NaN,False,NaN,...,0.971616,NaN,NaN,0.968705,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,X_049_045_040_038_033,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970264,"{""049_gpu_logreg_add048"": 0.19068397962763695,...",True,0.190684,False,NaN,...,0.973925,0.970264,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,W_049_045_040_038,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970264,"{""049_gpu_logreg_add048"": 0.18640369818787422,...",True,0.186404,False,NaN,...,0.973901,0.970264,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,W_049_045_040_038,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970255,"{""049_gpu_logreg_add048"": 0.2388205117412317, ...",True,0.238821,False,NaN,...,0.973829,NaN,NaN,0.970255,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
4,Z15_045_040_038,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970253,"{""045_gpu_logreg_add044"": 0.5144616346780971, ...",False,NaN,False,NaN,...,0.973937,0.970253,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Z19_040_033_038_036gpu_036blend_039_044_042_04...,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970253,"{""040_gpu_logreg_add039"": 0.08407327347212103,...",True,0.365774,True,0.000000,...,0.973551,0.970253,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Z16_045_040_033_038,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970252,"{""045_gpu_logreg_add044"": 0.32558062578057534,...",False,NaN,False,NaN,...,0.974022,0.970252,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Z17_045_040_033_038_044_042,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970246,"{""045_gpu_logreg_add044"": 0.1953383167534802, ...",False,NaN,False,NaN,...,0.974252,0.970246,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,W_049_045_040_038,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",4,0.970231,None,True,NaN,False,NaN,...,0.973841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,V_049_045_038,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,03...",3,0.970223,"{""049_gpu_logreg_add048"": 0.2628329356047728, ...",True,0.262833,False,NaN,...,0.973804,0.970223,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Z14_047_048_049_045_040_038_033,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.970220,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.233447,True,0.083548,...,0.972366,0.970220,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,X_049_045_040_038_033,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970219,"{""049_gpu_logreg_add048"": 0.21931056260523232,...",True,0.219311,False,NaN,...,0.973804,NaN,NaN,0.970219,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
12,Z15_045_040_038,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970218,"{""045_gpu_logreg_add044"": 0.48768090588066687,...",False,NaN,False,NaN,...,0.973937,NaN,NaN,0.970218,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
13,Z13_047_048_049_040_038,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.970213,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.322251,True,0.000000,...,0.973478,0.970213,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Z06_048_049_045_040_038_033,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.970212,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0851...",True,0.230418,True,0.085110,...,0.972318,0.970212,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Z18_041_old_best_like_plus_new049,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970211,"{""040_gpu_logreg_add039"": 0.14146687686396553,...",True,0.136492,False,NaN,...,0.973551,0.970211,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,V_049_045_038,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,03...",3,0.970209,"{""049_gpu_logreg_add048"": 0.24629912303424575,...",True,0.246299,False,NaN,...,0.973792,NaN,NaN,0.970209,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
17,Z15_045_040_038,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",3,0.970207,None,False,NaN,False,NaN,...,0.974046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,R_049_040_038,hc_nonnegative_raw,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970205,"{""049_gpu_logreg_add048"": 0.2545167072366898, ...",True,0.254517,False,NaN,...,0.973974,0.970205,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Z05_048_049_040_038,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",4,0.970198,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0194...",True,0.404311,True,0.019421,...,0.973551,0.970198,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Z05_048_049_040_038,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",4,0.970188,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0912...",True,0.339552,True,0.091253,...,0.972451,NaN,NaN,0.970188,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
21,V_049_045_038,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,03...",3,0.970186,None,True,NaN,False,NaN,...,0.973647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Z13_047_048_049_040_038,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.970177,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.038111,True,0.028387,...,0.973732,NaN,NaN,0.970177,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
23,T_049_038_033,hc_nonnegative_raw,"049_gpu_logreg_add048,038_gpu_logreg_add037,03...",3,0.970171,"{""049_gpu_logreg_add048"": 0.30762936199208474,...",True,0.307629,False,NaN,...,0.973321,0.970171,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,T_049_038_033,nm_softmax_raw,"049_gpu_logreg_add048,038_gpu_logreg_add037,03...",3,0.970169,"{""049_gpu_logreg_add048"": 0.3560545297149199, ...",True,0.356055,False,NaN,...,0.973236,NaN,NaN,0.970169,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
25,R_049_040_038,nm_softmax_raw,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970169,"{""049_gpu_logreg_add048"": 0.3530603097122465, ...",True,0.353060,False,NaN,...,0.973937,NaN,NaN,0.970169,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
26,O_049_038,hc_nonnegative_raw,"049_gpu_logreg_add048,038_gpu_logreg_add037",2,0.970165,"{""049_gpu_logreg_add048"": 0.3834830154135431, ...",True,0.383483,False,NaN,...,0.973913,0.970165,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Z16_045_040_033_038,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970164,"{""045_gpu_logreg_add044"": 0.25, ""040_gpu_logre...",False,NaN,False,NaN,...,0.973611,NaN,NaN,0.970164,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
28,Z16_045_040_033_038,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970164,None,False,NaN,False,NaN,...,0.973611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,R_049_040_038,avg,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970162,None,True,NaN,False,NaN,...,0.973913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,O_049_038,nm_softmax_raw,"049_gpu_logreg_add048,038_gpu_logreg_add037",2,0.970153,"{""049_gpu_logreg_add048"": 0.45751802420368753,...",True,0.457518,False,NaN,...,0.973780,NaN,NaN,0.970153,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
31,Z17_045_040_033_038_044_042,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970145,"{""045_gpu_logreg_add044"": 0.19161509400530638,...",False,NaN,False,NaN,...,0.973611,NaN,NaN,0.970145,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
32,X_049_045_040_038_033,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970145,None,True,NaN,False,NaN,...,0.973454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,O_049_038,avg,"049_gpu_logreg_add048,038_gpu_logreg_add037",2,0.970136,None,True,NaN,False,NaN,...,0.973708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Z08_047_038,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.970135,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.974336,0.970135,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Z01_048_038,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,038_gpu_lo...",2,0.970135,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 1.9751...",False,NaN,True,0.000020,...,0.974336,NaN,NaN,0.970135,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
36,D_038_only,nm_softmax_raw,038_gpu_logreg_add037,1,0.970135,"{""038_gpu_logreg_add037"": 1.0}",False,NaN,False,NaN,...,0.974336,NaN,NaN,0.970135,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
37,Z08_047_038,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.970135,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.974336,NaN,NaN,0.970135,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
38,D_038_only,hc_nonnegative_raw,038_gpu_logreg_add037,1,0.970135,"{""038_gpu_logreg_add037"": 1.0}",False,NaN,False,NaN,...,0.974336,0.970135,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,D_038_only,avg,038_gpu_logreg_add037,1,0.970135,None,False,NaN,False,NaN,...,0.974336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,T_049_038_033,avg,"049_gpu_logreg_add048,038_gpu_logreg_add037,03...",3,0.970118,None,True,NaN,False,NaN,...,0.973297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Z17_045_040_033_038_044_042,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970117,None,False,NaN,False,NaN,...,0.973732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Z19_040_033_038_036gpu_036blend_039_044_042_04...,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970086,"{""040_gpu_logreg_add039"": 0.16145611392049694,...",True,0.111405,True,0.076546,...,0.972366,NaN,NaN,0.970086,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
43,Z01_048_038,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,038_gpu_lo...",2,0.970055,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.1423...",False,NaN,True,0.142302,...,0.972052,0.970055,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Z19_040_033_038_036gpu_036blend_039_044_042_04...,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970048,None,True,NaN,True,NaN,...,0.971894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
46,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Z06_048_049_045_040_038_033,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.970012,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.1660...",True,0.149002,True,0.166031,...,0.970758,NaN,NaN,0.970012,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
48,Z06_048_049_045_040_038_033,avg,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.969984,None,True,NaN,True,NaN,...,0.970734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
50,Z05_048_049_040_038,avg,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",4,0.969758,None,True,NaN,True,NaN,...,0.969392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Z14_047_048_049_045_040_038_033,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969607,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.107023,True,0.131908,...,0.968365,NaN,NaN,0.969607,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
53,Z14_047_048_049_045_040_038_033,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969557,None,True,NaN,True,NaN,...,0.967784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Z13_047_048_049_040_038,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",5,0.969089,None,True,NaN,True,NaN,...,0.964992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Z01_048_038,avg,"048_ovr_xgb_seed2027_fe_foldvariant,038_gpu_lo...",2,0.968738,None,False,NaN,True,NaN,...,0.963541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Z08_047_038,avg,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.967877,None,False,NaN,False,NaN,...,0.959625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z20_component_diagnostics_xgb_and_core,hc_nonnegative_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.970250,"{""027_blend_add026"": 0.09266904710786944, ""026...",True,0.510185,True,0.000000,...,0.973079,0.970250,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z18_041_old_best_like_plus_new049,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970211,"{""040_gpu_logreg_add039"": 0.14146687686396553,...",True,0.136492,False,NaN,...,0.973551,0.970211,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
4,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
6,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Z20_component_diagnostics_xgb_and_core,nm_softmax_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.969527,"{""027_blend_add026"": 0.49613240081968846, ""026...",True,0.042539,True,0.058864,...,0.968232,NaN,NaN,0.969527,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
8,Z20_component_diagnostics_xgb_and_core,avg,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.968865,None,True,NaN,True,NaN,...,0.964376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z19_040_033_038_036gpu_036blend_039_044_042_04...,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970253,"{""040_gpu_logreg_add039"": 0.08407327347212103,...",True,0.365774,True,0.000000,...,0.973551,0.970253,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z18_041_old_best_like_plus_new049,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970211,"{""040_gpu_logreg_add039"": 0.14146687686396553,...",True,0.136492,False,NaN,...,0.973551,0.970211,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Z19_040_033_038_036gpu_036blend_039_044_042_04...,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970086,"{""040_gpu_logreg_add039"": 0.16145611392049694,...",True,0.111405,True,0.076546,...,0.972366,NaN,NaN,0.970086,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
4,K_036_gpu_only,avg,036_gpu_logreg_add035,1,0.970067,None,False,NaN,False,NaN,...,0.973188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,K_036_gpu_only,hc_nonnegative_raw,036_gpu_logreg_add035,1,0.970067,"{""036_gpu_logreg_add035"": 1.0}",False,NaN,False,NaN,...,0.973188,0.970067,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,K_036_gpu_only,nm_softmax_raw,036_gpu_logreg_add035,1,0.970067,"{""036_gpu_logreg_add035"": 1.0}",False,NaN,False,NaN,...,0.973188,NaN,NaN,0.970067,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
7,Z19_040_033_038_036gpu_036blend_039_044_042_04...,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970048,None,True,NaN,True,NaN,...,0.971894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
9,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
11,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z19_040_033_038_036gpu_036blend_039_044_042_04...,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970253,"{""040_gpu_logreg_add039"": 0.08407327347212103,...",True,0.365774,True,0.000000,...,0.973551,0.970253,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z18_041_old_best_like_plus_new049,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970211,"{""040_gpu_logreg_add039"": 0.14146687686396553,...",True,0.136492,False,NaN,...,0.973551,0.970211,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Z19_040_033_038_036gpu_036blend_039_044_042_04...,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970086,"{""040_gpu_logreg_add039"": 0.16145611392049694,...",True,0.111405,True,0.076546,...,0.972366,NaN,NaN,0.970086,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
4,L_036_blend_only,hc_nonnegative_raw,036_blend_add035,1,0.970073,"{""036_blend_add035"": 1.0}",False,NaN,False,NaN,...,0.972499,0.970073,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,L_036_blend_only,nm_softmax_raw,036_blend_add035,1,0.970073,"{""036_blend_add035"": 1.0}",False,NaN,False,NaN,...,0.972499,NaN,NaN,0.970073,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
6,L_036_blend_only,avg,036_blend_add035,1,0.970073,None,False,NaN,False,NaN,...,0.972499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Z19_040_033_038_036gpu_036blend_039_044_042_04...,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970048,None,True,NaN,True,NaN,...,0.971894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
9,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
11,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z20_component_diagnostics_xgb_and_core,hc_nonnegative_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.970250,"{""027_blend_add026"": 0.09266904710786944, ""026...",True,0.510185,True,0.000000,...,0.973079,0.970250,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
3,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Z20_component_diagnostics_xgb_and_core,nm_softmax_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.969527,"{""027_blend_add026"": 0.49613240081968846, ""026...",True,0.042539,True,0.058864,...,0.968232,NaN,NaN,0.969527,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
5,Z20_component_diagnostics_xgb_and_core,avg,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.968865,None,True,NaN,True,NaN,...,0.964376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
2,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,X_049_045_040_038_033,hc_nonnegative_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970264,"{""049_gpu_logreg_add048"": 0.19068397962763695,...",True,0.190684,False,NaN,...,0.973925,0.970264,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z19_040_033_038_036gpu_036blend_039_044_042_04...,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970253,"{""040_gpu_logreg_add039"": 0.08407327347212103,...",True,0.365774,True,0.000000,...,0.973551,0.970253,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Z16_045_040_033_038,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970252,"{""045_gpu_logreg_add044"": 0.32558062578057534,...",False,NaN,False,NaN,...,0.974022,0.970252,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Z17_045_040_033_038_044_042,hc_nonnegative_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970246,"{""045_gpu_logreg_add044"": 0.1953383167534802, ...",False,NaN,False,NaN,...,0.974252,0.970246,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,P_049_033,hc_nonnegative_raw,"049_gpu_logreg_add048,033_blend_add032",2,0.970227,"{""049_gpu_logreg_add048"": 0.5959595959595959, ...",True,0.595960,False,NaN,...,0.972982,0.970227,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,P_049_033,nm_softmax_raw,"049_gpu_logreg_add048,033_blend_add032",2,0.970224,"{""049_gpu_logreg_add048"": 0.5870104343871553, ...",True,0.587010,False,NaN,...,0.972970,NaN,NaN,0.970224,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
7,S_049_040_033,hc_nonnegative_raw,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970222,"{""049_gpu_logreg_add048"": 0.4105671033185198, ...",True,0.410567,False,NaN,...,0.973176,0.970222,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Z14_047_048_049_045_040_038_033,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.970220,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.233447,True,0.083548,...,0.972366,0.970220,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,X_049_045_040_038_033,nm_softmax_raw,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970219,"{""049_gpu_logreg_add048"": 0.21931056260523232,...",True,0.219311,False,NaN,...,0.973804,NaN,NaN,0.970219,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
10,Z06_048_049_045_040_038_033,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.970212,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0851...",True,0.230418,True,0.085110,...,0.972318,0.970212,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Z18_041_old_best_like_plus_new049,hc_nonnegative_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970211,"{""040_gpu_logreg_add039"": 0.14146687686396553,...",True,0.136492,False,NaN,...,0.973551,0.970211,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,P_049_033,avg,"049_gpu_logreg_add048,033_blend_add032",2,0.970199,None,True,NaN,False,NaN,...,0.972970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,S_049_040_033,nm_softmax_raw,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970197,"{""049_gpu_logreg_add048"": 0.35748134880005844,...",True,0.357481,False,NaN,...,0.973248,NaN,NaN,0.970197,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
14,T_049_038_033,hc_nonnegative_raw,"049_gpu_logreg_add048,038_gpu_logreg_add037,03...",3,0.970171,"{""049_gpu_logreg_add048"": 0.30762936199208474,...",True,0.307629,False,NaN,...,0.973321,0.970171,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,T_049_038_033,nm_softmax_raw,"049_gpu_logreg_add048,038_gpu_logreg_add037,03...",3,0.970169,"{""049_gpu_logreg_add048"": 0.3560545297149199, ...",True,0.356055,False,NaN,...,0.973236,NaN,NaN,0.970169,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
16,Z16_045_040_033_038,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970164,"{""045_gpu_logreg_add044"": 0.25, ""040_gpu_logre...",False,NaN,False,NaN,...,0.973611,NaN,NaN,0.970164,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
17,Z16_045_040_033_038,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",4,0.970164,None,False,NaN,False,NaN,...,0.973611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,S_049_040_033,avg,"049_gpu_logreg_add048,040_gpu_logreg_add039,03...",3,0.970161,None,True,NaN,False,NaN,...,0.973285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Z17_045_040_033_038_044_042,nm_softmax_raw,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970145,"{""045_gpu_logreg_add044"": 0.19161509400530638,...",False,NaN,False,NaN,...,0.973611,NaN,NaN,0.970145,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
20,X_049_045_040_038_033,avg,"049_gpu_logreg_add048,045_gpu_logreg_add044,04...",5,0.970145,None,True,NaN,False,NaN,...,0.973454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,T_049_038_033,avg,"049_gpu_logreg_add048,038_gpu_logreg_add037,03...",3,0.970118,None,True,NaN,False,NaN,...,0.973297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Z17_045_040_033_038_044_042,avg,"045_gpu_logreg_add044,040_gpu_logreg_add039,03...",6,0.970117,None,False,NaN,False,NaN,...,0.973732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Z19_040_033_038_036gpu_036blend_039_044_042_04...,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970086,"{""040_gpu_logreg_add039"": 0.16145611392049694,...",True,0.111405,True,0.076546,...,0.972366,NaN,NaN,0.970086,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
24,Z19_040_033_038_036gpu_036blend_039_044_042_04...,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",10,0.970048,None,True,NaN,True,NaN,...,0.971894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,E_033_only,hc_nonnegative_raw,033_blend_add032,1,0.970040,"{""033_blend_add032"": 1.0}",False,NaN,False,NaN,...,0.972571,0.970040,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,E_033_only,avg,033_blend_add032,1,0.970040,None,False,NaN,False,NaN,...,0.972571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,E_033_only,nm_softmax_raw,033_blend_add032,1,0.970040,"{""033_blend_add032"": 1.0}",False,NaN,False,NaN,...,0.972571,NaN,NaN,0.970040,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
28,Z09_047_033,hc_nonnegative_raw,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.970040,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.972571,0.970040,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Z09_047_033,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.970040,"{""047_xgb_multiclass_fe_objective_foldvariant""...",False,NaN,False,NaN,...,0.972571,NaN,NaN,0.970040,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
30,Z02_048_033,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,033_blend_...",2,0.970040,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 1.8166...",False,NaN,True,0.000018,...,0.972571,NaN,NaN,0.970040,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
31,Z02_048_033,hc_nonnegative_raw,"048_ovr_xgb_seed2027_fe_foldvariant,033_blend_...",2,0.970040,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.0, ""...",False,NaN,True,0.000000,...,0.972571,0.970040,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Z18_041_old_best_like_plus_new049,nm_softmax_raw,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,"{""040_gpu_logreg_add039"": 0.09090909090909091,...",True,0.090909,False,NaN,...,0.973817,NaN,NaN,0.970039,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
33,Z18_041_old_best_like_plus_new049,avg,"040_gpu_logreg_add039,033_blend_add032,038_gpu...",11,0.970039,None,True,NaN,False,NaN,...,0.973817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Z06_048_049_045_040_038_033,nm_softmax_raw,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.970012,"{""048_ovr_xgb_seed2027_fe_foldvariant"": 0.1660...",True,0.149002,True,0.166031,...,0.970758,NaN,NaN,0.970012,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
35,Z06_048_049_045_040_038_033,avg,"048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_lo...",6,0.969984,None,True,NaN,True,NaN,...,0.970734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
37,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Z14_047_048_049_045_040_038_033,nm_softmax_raw,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969607,"{""047_xgb_multiclass_fe_objective_foldvariant""...",True,0.107023,True,0.131908,...,0.968365,NaN,NaN,0.969607,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
39,Z14_047_048_049_045_040_038_033,avg,"047_xgb_multiclass_fe_objective_foldvariant,04...",7,0.969557,None,True,NaN,True,NaN,...,0.967784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Z02_048_033,avg,"048_ovr_xgb_seed2027_fe_foldvariant,033_blend_...",2,0.968327,None,False,NaN,True,NaN,...,0.961486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Z09_047_033,avg,"047_xgb_multiclass_fe_objective_foldvariant,03...",2,0.967331,None,False,NaN,False,NaN,...,0.957437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z20_component_diagnostics_xgb_and_core,hc_nonnegative_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.970250,"{""027_blend_add026"": 0.09266904710786944, ""026...",True,0.510185,True,0.000000,...,0.973079,0.970250,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
3,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Z20_component_diagnostics_xgb_and_core,nm_softmax_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.969527,"{""027_blend_add026"": 0.49613240081968846, ""026...",True,0.042539,True,0.058864,...,0.968232,NaN,NaN,0.969527,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
5,Z20_component_diagnostics_xgb_and_core,avg,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.968865,None,True,NaN,True,NaN,...,0.964376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,M_031_only,avg,031_blend_add030,1,0.970033,None,False,NaN,False,NaN,...,0.972571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,M_031_only,nm_softmax_raw,031_blend_add030,1,0.970033,"{""031_blend_add030"": 1.0}",False,NaN,False,NaN,...,0.972571,NaN,NaN,0.970033,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
3,M_031_only,hc_nonnegative_raw,031_blend_add030,1,0.970033,"{""031_blend_add030"": 1.0}",False,NaN,False,NaN,...,0.972571,0.970033,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
5,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z20_component_diagnostics_xgb_and_core,hc_nonnegative_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.970250,"{""027_blend_add026"": 0.09266904710786944, ""026...",True,0.510185,True,0.000000,...,0.973079,0.970250,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
3,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Z20_component_diagnostics_xgb_and_core,nm_softmax_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.969527,"{""027_blend_add026"": 0.49613240081968846, ""026...",True,0.042539,True,0.058864,...,0.968232,NaN,NaN,0.969527,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
5,Z20_component_diagnostics_xgb_and_core,avg,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.968865,None,True,NaN,True,NaN,...,0.964376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
2,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,set_name,method,keys,n_models,balanced_accuracy,weights_json,includes_049,weight_049,includes_048,weight_048,...,recall_STAR,hc_score_internal,hc_n_steps,nm_score_internal,nm_success,nm_message,C,risk,alpha,l1_ratio
0,Z21_full_all_loaded,hc_nonnegative_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.970277,"{""015_realmlp_seed42"": 0.025633413531209702, ""...",True,0.249955,True,0.000000,...,0.972910,0.970277,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z20_component_diagnostics_xgb_and_core,hc_nonnegative_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.970250,"{""027_blend_add026"": 0.09266904710786944, ""026...",True,0.510185,True,0.000000,...,0.973079,0.970250,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Z21_full_all_loaded,nm_softmax_raw,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969814,"{""015_realmlp_seed42"": 0.027756865420468166, ""...",True,0.039721,True,0.041723,...,0.970057,NaN,NaN,0.969814,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
3,Z21_full_all_loaded,avg,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...",28,0.969688,None,True,NaN,True,NaN,...,0.969368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Z20_component_diagnostics_xgb_and_core,nm_softmax_raw,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.969527,"{""027_blend_add026"": 0.49613240081968846, ""026...",True,0.042539,True,0.058864,...,0.968232,NaN,NaN,0.969527,True,Optimization terminated successfully.,NaN,NaN,NaN,NaN
5,Z20_component_diagnostics_xgb_and_core,avg,"027_blend_add026,026_realmlp_v5,028_cat_v3,039...",11,0.968865,None,True,NaN,True,NaN,...,0.964376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# ============================================================
# 5. Save best safe blend
# ============================================================

safe_blend_df = safe_blend_df.sort_values("balanced_accuracy", ascending=False).reset_index(drop=True)
best_row = safe_blend_df.iloc[0].to_dict()
best_set_name = best_row["set_name"]
best_method = best_row["method"]
best_keys = best_row["keys"].split(",")

print("Best safe blend:")
print(json.dumps(best_row, indent=2, ensure_ascii=False))

if best_method == "avg":
    best_oof_proba, best_pred_proba = average_proba(best_keys, oof, pred)
else:
    weights_json = json.loads(best_row["weights_json"])
    w = np.array([weights_json[k] for k in best_keys], dtype=float)
    best_oof_proba = normalize_rows(sum(w[i] * oof[best_keys[i]] for i in range(len(best_keys))))
    best_pred_proba = normalize_rows(sum(w[i] * pred[best_keys[i]] for i in range(len(best_keys))))

validate_proba("best_oof_proba", best_oof_proba, len(train), n_classes)
validate_proba("best_pred_proba", best_pred_proba, len(test), n_classes)

best_oof_score = balanced_accuracy_score(y, best_oof_proba.argmax(axis=1))
print("best_oof_score:", best_oof_score)

best_oof_npy = OUTDIR / f"oof_{EXP_ID}_best_blend_proba.npy"
best_pred_npy = OUTDIR / f"pred_{EXP_ID}_best_blend_proba.npy"
np.save(best_oof_npy, best_oof_proba.astype(np.float32))
np.save(best_pred_npy, best_pred_proba.astype(np.float32))

best_labels = le.inverse_transform(best_pred_proba.argmax(axis=1))
submission = pd.DataFrame({ID_COL: test[ID_COL].values, TARGET_COL: best_labels})
assert submission.shape[0] == sample.shape[0]
assert submission.columns.tolist() == sample.columns.tolist()
assert submission[ID_COL].equals(sample[ID_COL])

best_submission_path = OUTDIR / f"submission_{EXP_ID}_best_blend.csv"
submission.to_csv(best_submission_path, index=False)

best_info = {
    "exp_id": EXP_ID,
    "best_set_name": best_set_name,
    "best_method": best_method,
    "best_keys": best_keys,
    "cv_score": float(best_oof_score),
    "weights_json": best_row.get("weights_json"),
    "oof_path": str(best_oof_npy),
    "pred_path": str(best_pred_npy),
    "submission_path": str(best_submission_path),
    "row": best_row,
    "note": "Best safe blend excludes in-sample meta screening methods.",
}
for short_name, target_key in TRACK_KEYS.items():
    best_info[f"includes_{short_name}"] = target_key in best_keys
    best_info[f"weight_{short_name}"] = best_row.get(f"weight_{short_name}")

save_json(best_info, OUTDIR / "best_blend_info.json")

saved_submission_record = {
    "set_name": best_set_name,
    "method": best_method,
    "cv": float(best_oof_score),
    "keys": ",".join(best_keys),
    "weights_json": best_row.get("weights_json"),
    "submission": best_submission_path.name,
    "oof_proba": best_oof_npy.name,
    "pred_proba": best_pred_npy.name,
}
for short_name, target_key in TRACK_KEYS.items():
    saved_submission_record[f"includes_{short_name}"] = target_key in best_keys
    saved_submission_record[f"weight_{short_name}"] = best_row.get(f"weight_{short_name}")

saved_submission_df = pd.DataFrame([saved_submission_record])
display(saved_submission_df)
saved_submission_df.to_csv(OUTDIR / "saved_submission_candidates.csv", index=False)

Best safe blend:
{
  "set_name": "Z21_full_all_loaded",
  "method": "hc_nonnegative_raw",
  "keys": "015_realmlp_seed42,017_realmlp_bias,018_xgb_shared003,019_blend_best,020_blend_bias,024_seed_ensemble_blend,026_realmlp_v5,027_blend_add026,028_cat_v3,029_blend_add028,030_ovr_xgb,031_blend_add030,032_ovr_tabm,033_blend_add032,034_gpu_logreg_default,035_shared001_updated,036_gpu_logreg_add035,036_blend_add035,037_tabicl_v2,038_gpu_logreg_add037,039_cat_v3_seed2026_qbin_variant,040_gpu_logreg_add039,042_realmlp_v5_seed2026_foldvariant,044_shared001_updated_seed2027_foldvariant,045_gpu_logreg_add044,047_xgb_multiclass_fe_objective_foldvariant,048_ovr_xgb_seed2027_fe_foldvariant,049_gpu_logreg_add048",
  "n_models": 28,
  "balanced_accuracy": 0.9702769901284838,
  "weights_json": "{\"015_realmlp_seed42\": 0.025633413531209702, \"017_realmlp_bias\": 0.0, \"018_xgb_shared003\": 0.0, \"019_blend_best\": 0.0, \"020_blend_bias\": 0.0, \"024_seed_ensemble_blend\": 0.0, \"026_realmlp_v5\": 0.09740697141859689, \"027_blend_add026\": 0.025633413531209702, \"028_cat_v3\": 0.03539727950591619, \"029_blend_add028\": 0.02762543746736932, \"030_ovr_xgb\": 0.0, \"031_blend_add030\": 0.025633413531209702, \"032_ovr_tabm\": 0.025633413531209702, \"033_blend_add032\": 0.025633413531209702, \"034_gpu_logreg_default\": 0.009861504634453547, \"035_shared001_updated\": 0.025633413531209702, \"036_gpu_logreg_add035\": 0.005699182747658558, \"036_blend_add035\": 0.11425909520959307, \"037_tabicl_v2\": 0.0, \"038_gpu_logreg_add037\": 0.0, \"039_cat_v3_seed2026_qbin_variant\": 0.1045843272073356, \"040_gpu_logreg_add039\": 0.12251438730414618, \"042_realmlp_v5_seed2026_foldvariant\": 0.025633413531209702, \"044_shared001_updated_seed2027_foldvariant\": 0.025633413531209702, \"045_gpu_logreg_add044\": 0.02762942151524164, \"047_xgb_multiclass_fe_objective_foldvariant\": 0.0, \"048_ovr_xgb_seed2027_fe_foldvariant\": 0.0, \"049_gpu_logreg_add048\": 0.24995508474001138}",
  "includes_049": true,
  "weight_049": 0.24995508474001138,
  "includes_048": true,
  "weight_048": 0.0,
  "includes_047": true,
  "weight_047": 0.0,
  "includes_045": true,
  "weight_045": 0.02762942151524164,
  "includes_044": true,
  "weight_044": 0.025633413531209702,
  "includes_042": true,
  "weight_042": 0.025633413531209702,
  "includes_040": true,
  "weight_040": 0.12251438730414618,
  "includes_039": true,
  "weight_039": 0.1045843272073356,
  "includes_038": true,
  "weight_038": 0.0,
  "includes_037": true,
  "weight_037": 0.0,
  "includes_036_gpu": true,
  "weight_036_gpu": 0.005699182747658558,
  "includes_036_blend": true,
  "weight_036_blend": 0.11425909520959307,
  "includes_035": true,
  "weight_035": 0.025633413531209702,
  "includes_034": true,
  "weight_034": 0.009861504634453547,
  "includes_033": true,
  "weight_033": 0.025633413531209702,
  "includes_032": true,
  "weight_032": 0.025633413531209702,
  "includes_031": true,
  "weight_031": 0.025633413531209702,
  "includes_030": true,
  "weight_030": 0.0,
  "includes_029": true,
  "weight_029": 0.02762543746736932,
  "includes_028": true,
  "weight_028": 0.03539727950591619,
  "recall_GALAXY": 0.9613198050227827,
  "recall_QSO": 0.9766012480472585,
  "recall_STAR": 0.9729099173154103,
  "hc_score_internal": 0.9702769901284838,
  "hc_n_steps": 26.0,
  "nm_score_internal": NaN,
  "nm_success": NaN,
  "nm_message": NaN,
  "C": NaN,
  "risk": NaN,
  "alpha": NaN,
  "l1_ratio": NaN
}
best_oof_score: 0.9702769901284838

,set_name,method,cv,keys,weights_json,submission,oof_proba,pred_proba,includes_049,weight_049,...,includes_032,weight_032,includes_031,weight_031,includes_030,weight_030,includes_029,weight_029,includes_028,weight_028
0,Z21_full_all_loaded,hc_nonnegative_raw,0.970277,"015_realmlp_seed42,017_realmlp_bias,018_xgb_sh...","{""015_realmlp_seed42"": 0.025633413531209702, ""...",submission_exp_20260614_050_blend_add047_048_0...,oof_exp_20260614_050_blend_add047_048_049_chec...,pred_exp_20260614_050_blend_add047_048_049_che...,True,0.249955,...,True,0.025633,True,0.025633,True,0.0,True,0.027625,True,0.035397

In [7]:
# ============================================================
# 6. Save summary / memo
# ============================================================

reference_scores = {
    "050_context": "blend add047/048/049 check based on 046",
    "049_gpu_logreg_add048_cv": 0.9701958734042008,
    "049_gpu_logreg_add048_public_lb": 0.97046,
    "048_ovr_xgb_variant_cv": 0.9636973807714805,
    "048_ovr_xgb_variant_public_lb": 0.96444,
    "047_xgb_multiclass_variant_cv": 0.9596874103404002,
    "047_xgb_multiclass_variant_public_lb": 0.96027,
    "046_blend_add042_044_045_cv": 0.9702533348410616,
    "046_blend_add042_044_045_public_lb": 0.97042,
    "045_gpu_logreg_add044_cv": 0.9702445493383917,
    "045_gpu_logreg_add044_public_lb": 0.97040,
    "044_shared001_updated_variant_cv": 0.9686035095582338,
    "044_shared001_updated_variant_public_lb": 0.97000,
    "042_realmlp_v5_variant_cv": 0.9689482884928097,
    "042_realmlp_v5_variant_public_lb": 0.96943,
    "041_blend_add039_gpu040_cv": 0.9702371689099357,
    "041_blend_add039_gpu040_public_lb": 0.97050,
    "040_gpu_logreg_add039_cv": 0.9702017877238539,
    "040_gpu_logreg_add039_public_lb": 0.97069,
    "038_gpu_logreg_add037_cv": 0.9701353365798572,
    "038_gpu_logreg_add037_public_lb": 0.97060,
    "033_cv": 0.9700400336552478,
    "033_public_lb": 0.97043,
    "036_gpu_logreg_add035_cv": 0.9700674063284508,
    "036_gpu_logreg_add035_public_lb": 0.97037,
    "036_blend_add035_cv": 0.9700727843277738,
    "036_blend_add035_public_lb": 0.97023,
    "031_blend_add030_cv": 0.9700333620193362,
    "031_blend_add030_public_lb": 0.97043,
}

best_focus_safe = {}
for short_name, df in focus_blend_tables.items():
    best_focus_safe[short_name] = None if len(df) == 0 else df.iloc[0].to_dict()

judgement = {
    "reference_scores": reference_scores,
    "individual_best": {
        "key": individual_df.iloc[0]["key"],
        "cv": float(individual_df.iloc[0]["recomputed_oof_cv"]),
        "public_lb": float(individual_df.iloc[0]["public_lb"]),
    },
    "best_safe_blend": best_info,
    "best_focus_safe": best_focus_safe,
    "main_questions": {
        "does_049_help_probability_blend": "Check focus_049 safe blends and weight_049 versus 040/038/045/046 references.",
        "does_048_help_direct_probability_blend": "Check focus_048 safe blends and weight_048. 048 may help directly or only through 049.",
        "does_047_help_despite_weak_standalone": "Check focus_047 safe blends and weight_047. If non-trivial, consider a later GPU LogReg stacker add047 diagnostic.",
        "does_033_remain_private_hedge": "Check blend sets containing 033 versus stacker-heavy 040/049 cluster.",
        "should_promote_050_best_blend": "Only if best safe blend improves CV and Public LB over 040. Ignore in-sample meta screening rows for submission decisions.",
    },
    "automatic_view": {
        "best_safe_includes_049": bool(best_info.get("includes_049")),
        "best_safe_weight_049": best_info.get("weight_049"),
        "best_safe_includes_048": bool(best_info.get("includes_048")),
        "best_safe_weight_048": best_info.get("weight_048"),
        "best_safe_includes_047": bool(best_info.get("includes_047")),
        "best_safe_weight_047": best_info.get("weight_047"),
        "best_safe_includes_045": bool(best_info.get("includes_045")),
        "best_safe_weight_045": best_info.get("weight_045"),
        "best_safe_includes_040": bool(best_info.get("includes_040")),
        "best_safe_weight_040": best_info.get("weight_040"),
        "best_safe_includes_038": bool(best_info.get("includes_038")),
        "best_safe_weight_038": best_info.get("weight_038"),
        "best_safe_includes_033": bool(best_info.get("includes_033")),
        "best_safe_weight_033": best_info.get("weight_033"),
        "best_safe_cv": float(best_info["cv_score"]),
        "040_reference_cv": reference_scores["040_gpu_logreg_add039_cv"],
        "040_reference_public_lb": reference_scores["040_gpu_logreg_add039_public_lb"],
        "049_reference_cv": reference_scores["049_gpu_logreg_add048_cv"],
        "049_reference_public_lb": reference_scores["049_gpu_logreg_add048_public_lb"],
        "047_stack_add_rule": (
            "If 047 gets non-trivial weight in a safe blend and the blend improves CV or Public LB, "
            "run a later GPU LogReg stacker add047 diagnostic. Otherwise keep 047 dropped."
        ),
        "promotion_rule": (
            "Promote 050 only if the best safe probability blend beats 040 on CV and confirms on Public LB. "
            "Do not promote in-sample LogReg/Ridge/ElasticNet diagnostic rows."
        ),
    },
}
save_json(judgement, OUTDIR / "role_judgement.json")

summary = {
    "competition": COMPETITION,
    "exp_id": EXP_ID,
    "status": "completed",
    "purpose": "Blend/correlation check after adding 047, 048, and 049 to the 046 candidate pool",
    "npy_dir": str(NPY_DIR),
    "model_keys": model_keys,
    "class_names": class_names,
    "resolved_specs": resolved_specs,
    "individual_scores": individual_df.to_dict(orient="records"),
    "pairwise_oof_correlation": pairwise_df.to_dict(orient="records"),
    "pairwise_oof_correlation_focus": {k: v.to_dict(orient="records") for k, v in focus_pairwise_tables.items()},
    "blend_diagnostics": blend_df.to_dict(orient="records"),
    "safe_blend_diagnostics": safe_blend_df.to_dict(orient="records"),
    "safe_blend_diagnostics_focus": {k: v.to_dict(orient="records") for k, v in focus_blend_tables.items()},
    "best_blend_info": best_info,
    "saved_submission_candidates": saved_submission_df.to_dict(orient="records"),
    "role_judgement": judgement,
}
summary_path = OUTDIR / "blend_add047_048_049_summary.json"
save_json(summary, summary_path)

memo = {
    "experiment": {
        "id": EXP_ID,
        "title": "Blend check after adding 047/048/049 to 046 pool",
        "competition": COMPETITION,
        "status": "completed",
        "metric": "balanced_accuracy_score",
        "created_at": "2026-06-14",
    },
    "objective": {
        "summary": (
            "Load OOF/pred probabilities from npy-files, add 047 multiclass XGB diagnostic, "
            "048 improved OVR XGB variant, and 049 GPU LogReg add048 stacker, then decide whether a direct safe probability blend "
            "can improve over the current 040 best."
        ),
        "success_criteria": [
            "load existing OOF/pred npy files including 047/048/049 and current references 040/038/033/045",
            "recompute individual balanced accuracy",
            "compute pairwise OOF correlations with focus tables for 049/048/047/040/038/033",
            "evaluate add047/add048/add049 blend sets",
            "separate safe blends from in-sample meta screening",
            "save best safe blend OOF/pred npy",
            "save best safe blend submission",
        ],
    },
    "inputs": {"npy_dir": str(NPY_DIR), "models": resolved_specs, "blend_sets": BLEND_SETS},
    "outputs": {
        "individual_scores": "individual_scores.csv",
        "pairwise_oof_correlation": "pairwise_oof_correlation.csv",
        "pairwise_oof_correlation_focus_prefix": "pairwise_oof_correlation_focus_*.csv",
        "blend_diagnostics": "blend_diagnostics.csv",
        "safe_blend_diagnostics": "safe_blend_diagnostics.csv",
        "safe_blend_diagnostics_focus_prefix": "safe_blend_diagnostics_focus_*.csv",
        "best_blend_info": "best_blend_info.json",
        "best_oof_proba": best_oof_npy.name,
        "best_pred_proba": best_pred_npy.name,
        "best_submission": best_submission_path.name,
        "summary": summary_path.name,
    },
    "judgement": {
        "status": "completed_pending_manual_review",
        "initial_view": (
            "040 is current best. 050 should only replace it if safe probability blend improves CV and Public LB. "
            "049 is the main new diagnostic target; 048 is a direct OVR-XGB material; 047 is low-priority and should only be escalated "
            "to GPU LogReg stacker add047 if it receives non-trivial safe-blend weight."
        ),
        "automatic_view": judgement["automatic_view"],
        "next_action": [
            "Review individual_scores.csv and confirm 049/048/047 recomputed OOF CV",
            "Review safe_blend_diagnostics_focus_049.csv, focus_048.csv, focus_047.csv, focus_040.csv, focus_038.csv, focus_033.csv",
            "If 047 has meaningful safe-blend weight and the blend improves CV/LB, consider GPU LogReg stacker add047 next",
            "Submit only best safe blend, not in-sample meta rows",
            "Keep 040 as slot_1 unless 050 best safe blend confirms on Public LB",
        ],
    },
}

memo_path = OUTDIR / "memo.yml"
if yaml is not None:
    with open(memo_path, "w", encoding="utf-8") as f:
        yaml.safe_dump(memo, f, allow_unicode=True, sort_keys=False)
else:
    with open(memo_path, "w", encoding="utf-8") as f:
        f.write(json.dumps(memo, indent=2, ensure_ascii=False, default=str))

print("Saved files:")
for p in sorted(OUTDIR.glob("*")):
    print(" -", p.name)

Saved files:
 - best_blend_info.json
 - blend_add047_048_049_summary.json
 - blend_diagnostics.csv
 - individual_scores.csv
 - memo.yml
 - oof_exp_20260614_050_blend_add047_048_049_check_best_blend_proba.npy
 - pairwise_oof_correlation.csv
 - pairwise_oof_correlation_focus_030.csv
 - pairwise_oof_correlation_focus_031.csv
 - pairwise_oof_correlation_focus_033.csv
 - pairwise_oof_correlation_focus_038.csv
 - pairwise_oof_correlation_focus_040.csv
 - pairwise_oof_correlation_focus_042.csv
 - pairwise_oof_correlation_focus_044.csv
 - pairwise_oof_correlation_focus_045.csv
 - pairwise_oof_correlation_focus_047.csv
 - pairwise_oof_correlation_focus_048.csv
 - pairwise_oof_correlation_focus_049.csv
 - pred_exp_20260614_050_blend_add047_048_049_check_best_blend_proba.npy
 - role_judgement.json
 - safe_blend_diagnostics.csv
 - safe_blend_diagnostics_focus_028.csv
 - safe_blend_diagnostics_focus_029.csv
 - safe_blend_diagnostics_focus_030.csv
 - safe_blend_diagnostics_focus_031.csv
 - safe_blend_diagnostics_focus_032.csv
 - safe_blend_diagnostics_focus_033.csv
 - safe_blend_diagnostics_focus_034.csv
 - safe_blend_diagnostics_focus_035.csv
 - safe_blend_diagnostics_focus_036_blend.csv
 - safe_blend_diagnostics_focus_036_gpu.csv
 - safe_blend_diagnostics_focus_037.csv
 - safe_blend_diagnostics_focus_038.csv
 - safe_blend_diagnostics_focus_039.csv
 - safe_blend_diagnostics_focus_040.csv
 - safe_blend_diagnostics_focus_042.csv
 - safe_blend_diagnostics_focus_044.csv
 - safe_blend_diagnostics_focus_045.csv
 - safe_blend_diagnostics_focus_047.csv
 - safe_blend_diagnostics_focus_048.csv
 - safe_blend_diagnostics_focus_049.csv
 - saved_submission_candidates.csv
 - submission_exp_20260614_050_blend_add047_048_049_check_best_blend.csv